// AUTO-GENERATED by analysis/e8_unitary_voltage_lift.js
// GAP certificate sha256: 9cc8926a936ccbb0958d419fc01e31f507f94eacf7b428e9cce7bfa6bdacf178
// Exact logical-address implementation of the 120-state affine relation lift.
`default_nettype none

module e8_unitary_voltage_lift_affine(
  input wire [3:0] u_block, input wire [2:0] u_slot,
  input wire [3:0] v_block, input wire [2:0] v_slot,
  output wire valid, output wire adjacent);
  wire same_block = (u_block == v_block);
  wire reverse = (u_block > v_block);
  wire [3:0] low_block = reverse ? v_block : u_block;
  wire [3:0] high_block = reverse ? u_block : v_block;
  wire [2:0] left_slot = reverse ? v_slot : u_slot;
  wire [2:0] right_slot = reverse ? u_slot : v_slot;
  wire [5:0] point = {right_slot[0],right_slot[1],right_slot[2],left_slot[0],left_slot[1],left_slot[2]};
  reg [3:0] relation_type;
  always @* begin
    relation_type = 4'd0;
    case ({low_block,high_block})
      8'h01: relation_type = 4'd1;
      8'h02: relation_type = 4'd2;
      8'h03: relation_type = 4'd3;
      8'h04: relation_type = 4'd4;
      8'h07: relation_type = 4'd5;
      8'h09: relation_type = 4'd6;
      8'h0a: relation_type = 4'd7;
      8'h0e: relation_type = 4'd8;
      8'h12: relation_type = 4'd9;
      8'h13: relation_type = 4'd10;
      8'h15: relation_type = 4'd4;
      8'h18: relation_type = 4'd5;
      8'h19: relation_type = 4'd6;
      8'h1b: relation_type = 4'd7;
      8'h1e: relation_type = 4'd11;
      8'h23: relation_type = 4'd4;
      8'h26: relation_type = 4'd4;
      8'h27: relation_type = 4'd5;
      8'h28: relation_type = 4'd6;
      8'h2c: relation_type = 4'd7;
      8'h2e: relation_type = 4'd12;
      8'h34: relation_type = 4'd5;
      8'h35: relation_type = 4'd6;
      8'h36: relation_type = 4'd4;
      8'h3d: relation_type = 4'd7;
      8'h3e: relation_type = 4'd7;
      8'h45: relation_type = 4'd1;
      8'h46: relation_type = 4'd2;
      8'h47: relation_type = 4'd2;
      8'h49: relation_type = 4'd13;
      8'h4a: relation_type = 4'd12;
      8'h4d: relation_type = 4'd8;
      8'h56: relation_type = 4'd9;
      8'h58: relation_type = 4'd2;
      8'h59: relation_type = 4'd13;
      8'h5b: relation_type = 4'd12;
      8'h5d: relation_type = 4'd11;
      8'h67: relation_type = 4'd2;
      8'h68: relation_type = 4'd13;
      8'h6c: relation_type = 4'd12;
      8'h6d: relation_type = 4'd12;
      8'h78: relation_type = 4'd1;
      8'h79: relation_type = 4'd1;
      8'h7a: relation_type = 4'd8;
      8'h7c: relation_type = 4'd8;
      8'h89: relation_type = 4'd1;
      8'h8b: relation_type = 4'd8;
      8'h8c: relation_type = 4'd11;
      8'h9a: relation_type = 4'd11;
      8'h9b: relation_type = 4'd11;
      8'hab: relation_type = 4'd1;
      8'hac: relation_type = 4'd2;
      8'had: relation_type = 4'd3;
      8'hae: relation_type = 4'd8;
      8'hbc: relation_type = 4'd9;
      8'hbd: relation_type = 4'd10;
      8'hbe: relation_type = 4'd11;
      8'hcd: relation_type = 4'd4;
      8'hce: relation_type = 4'd12;
      8'hde: relation_type = 4'd7;
      default: relation_type = 4'd0;
    endcase
  end
  reg [5:0] mask0, mask1;
  reg rhs0, rhs1;
  always @* begin
    mask0 = 6'd0; mask1 = 6'd0; rhs0 = 1'b0; rhs1 = 1'b0;
    case (relation_type)
      4'd1: begin mask0 = 6'h24; rhs0 = 1'b0; mask1 = 6'h12; rhs1 = 1'b0; end
      4'd2: begin mask0 = 6'h12; rhs0 = 1'b0; mask1 = 6'h2d; rhs1 = 1'b0; end
      4'd3: begin mask0 = 6'h14; rhs0 = 1'b0; mask1 = 6'h2b; rhs1 = 1'b1; end
      4'd4: begin mask0 = 6'h24; rhs0 = 1'b0; mask1 = 6'h1b; rhs1 = 1'b0; end
      4'd5: begin mask0 = 6'h22; rhs0 = 1'b0; mask1 = 6'h1d; rhs1 = 1'b1; end
      4'd6: begin mask0 = 6'h3c; rhs0 = 1'b0; mask1 = 6'h22; rhs1 = 1'b1; end
      4'd7: begin mask0 = 6'h36; rhs0 = 1'b0; mask1 = 6'h2d; rhs1 = 1'b0; end
      4'd8: begin mask0 = 6'h16; rhs0 = 1'b0; mask1 = 6'h3d; rhs1 = 1'b0; end
      4'd9: begin mask0 = 6'h12; rhs0 = 1'b1; mask1 = 6'h35; rhs1 = 1'b0; end
      4'd10: begin mask0 = 6'h14; rhs0 = 1'b1; mask1 = 6'h33; rhs1 = 1'b1; end
      4'd11: begin mask0 = 6'h16; rhs0 = 1'b1; mask1 = 6'h25; rhs1 = 1'b1; end
      4'd12: begin mask0 = 6'h26; rhs0 = 1'b0; mask1 = 6'h3d; rhs1 = 1'b1; end
      4'd13: begin mask0 = 6'h3c; rhs0 = 1'b1; mask1 = 6'h12; rhs1 = 1'b1; end
      default: begin mask0 = 6'd0; mask1 = 6'd0; rhs0 = 1'b0; rhs1 = 1'b0; end
    endcase
  end
  wire local_relation = left_slot[2] ^ right_slot[2];
  wire cross_relation = (relation_type != 0) && (^(point & mask0) == rhs0) && (^(point & mask1) == rhs1);
  assign valid = (u_block < 15) && (v_block < 15);
  assign adjacent = valid && (same_block ? local_relation : cross_relation);
endmodule

module e8_unitary_voltage_lift_rom(
  input wire [3:0] u_block, input wire [2:0] u_slot,
  input wire [3:0] v_block, input wire [2:0] v_slot,
  output wire valid, output wire adjacent);
  wire [6:0] u_address = {u_block,u_slot};
  wire [6:0] v_address = {v_block,v_slot};
  reg [127:0] row;
  always @* begin
    case (u_address)
      7'd0: row = 128'h002100000081280014000041122111f0;
      7'd1: row = 128'h008400000042820041000082481222f0;
      7'd2: row = 128'h004800000024410028000014218444f0;
      7'd3: row = 128'h001200000018140082000028844888f0;
      7'd4: row = 128'h0012000000182800410000142112110f;
      7'd5: row = 128'h0048000000248200140000288421220f;
      7'd6: row = 128'h0084000000424100820000411248440f;
      7'd7: row = 128'h0021000000811400280000824884880f;
      7'd8: row = 128'h0088000081002814000041004488f011;
      7'd9: row = 128'h0011000042008241000082002244f022;
      7'd10: row = 128'h0022000024004128000014008811f044;
      7'd11: row = 128'h0044000018001482000028001122f088;
      7'd12: row = 128'h00440000180028410000140088440f11;
      7'd13: row = 128'h00220000240082140000280011880f22;
      7'd14: row = 128'h00110000420041820000410044220f44;
      7'd15: row = 128'h00880000810014280000820022110f88;
      7'd16: row = 128'h00140081000000281441000041f08421;
      7'd17: row = 128'h00280042000000824182000082f04812;
      7'd18: row = 128'h00820024000000412814000014f01284;
      7'd19: row = 128'h00410018000000148228000028f02148;
      7'd20: row = 128'h004100180000002841140000140f8412;
      7'd21: row = 128'h008200240000008214280000280f4821;
      7'd22: row = 128'h002800420000004182410000410f1248;
      7'd23: row = 128'h001400810000001428820000820f2184;
      7'd24: row = 128'h008181000000000000412814f0412814;
      7'd25: row = 128'h004242000000000000828241f0828241;
      7'd26: row = 128'h002424000000000000144128f0144128;
      7'd27: row = 128'h001818000000000000281482f0281482;
      7'd28: row = 128'h0018180000000000001428410f142841;
      7'd29: row = 128'h0024240000000000002882140f288214;
      7'd30: row = 128'h0042420000000000004141820f414182;
      7'd31: row = 128'h0081810000000000008214280f821428;
      7'd32: row = 128'h0000210000148400212111f012000041;
      7'd33: row = 128'h0000840000284800121222f048000082;
      7'd34: row = 128'h0000480000821200848444f021000014;
      7'd35: row = 128'h0000120000412100484888f084000028;
      7'd36: row = 128'h00001200004184001212110f21000014;
      7'd37: row = 128'h00004800008248002121220f84000028;
      7'd38: row = 128'h00008400002812004848440f12000041;
      7'd39: row = 128'h00002100001421008484880f48000082;
      7'd40: row = 128'h00008800140084210088f01144004100;
      7'd41: row = 128'h00001100280048120044f02222008200;
      7'd42: row = 128'h00002200820012840011f04488001400;
      7'd43: row = 128'h00004400410021480022f08811002800;
      7'd44: row = 128'h000044004100841200440f1188001400;
      7'd45: row = 128'h000022008200482100880f2211002800;
      7'd46: row = 128'h000011002800124800220f4444004100;
      7'd47: row = 128'h000088001400218400110f8822008200;
      7'd48: row = 128'h000014140000008421f0842141410000;
      7'd49: row = 128'h000028280000004812f0481282820000;
      7'd50: row = 128'h000082820000001284f0128414140000;
      7'd51: row = 128'h000041410000002148f0214828280000;
      7'd52: row = 128'h0000414100000084120f841214140000;
      7'd53: row = 128'h0000828200000048210f482128280000;
      7'd54: row = 128'h0000282800000012480f124841410000;
      7'd55: row = 128'h0000141400000021840f218482820000;
      7'd56: row = 128'h0000002100211111f021002100120012;
      7'd57: row = 128'h0000008400842222f012001200480048;
      7'd58: row = 128'h0000004800484444f084008400210021;
      7'd59: row = 128'h0000001200128888f048004800840084;
      7'd60: row = 128'h00000012001211110f12001200210021;
      7'd61: row = 128'h00000048004822220f21002100840084;
      7'd62: row = 128'h00000084008444440f48004800120012;
      7'd63: row = 128'h00000021002188880f84008400480048;
      7'd64: row = 128'h00000088210011f01188210000441200;
      7'd65: row = 128'h00000011840022f02244120000224800;
      7'd66: row = 128'h00000022480044f04411840000882100;
      7'd67: row = 128'h00000044120088f08822480000118400;
      7'd68: row = 128'h000000441200110f1144120000882100;
      7'd69: row = 128'h000000224800220f2288210000118400;
      7'd70: row = 128'h000000118400440f4422480000441200;
      7'd71: row = 128'h000000882100880f8811840000224800;
      7'd72: row = 128'h000000008888f0111100888800004444;
      7'd73: row = 128'h000000001111f0222200444400002222;
      7'd74: row = 128'h000000002222f0444400111100008888;
      7'd75: row = 128'h000000004444f0888800222200001111;
      7'd76: row = 128'h0000000044440f111100444400008888;
      7'd77: row = 128'h0000000022220f222200888800001111;
      7'd78: row = 128'h0000000011110f444400222200004444;
      7'd79: row = 128'h0000000088880f888800111100002222;
      7'd80: row = 128'h0021122111f042008100001800000081;
      7'd81: row = 128'h0084481222f024001800002400000042;
      7'd82: row = 128'h0048218444f018004200008100000024;
      7'd83: row = 128'h0012844888f081002400004200000018;
      7'd84: row = 128'h00122112110f42001800008100000018;
      7'd85: row = 128'h00488421220f24008100004200000024;
      7'd86: row = 128'h00841248440f18002400001800000042;
      7'd87: row = 128'h00214884880f81004200002400000081;
      7'd88: row = 128'h00884488f01142810000180000008100;
      7'd89: row = 128'h00112244f02224180000240000004200;
      7'd90: row = 128'h00228811f04418420000810000002400;
      7'd91: row = 128'h00441122f08881240000420000001800;
      7'd92: row = 128'h004488440f1142180000810000001800;
      7'd93: row = 128'h002211880f2224810000420000002400;
      7'd94: row = 128'h001144220f4418240000180000004200;
      7'd95: row = 128'h008822110f8881420000240000008100;
      7'd96: row = 128'h001441f0842100428118000000810000;
      7'd97: row = 128'h002882f0481200241824000000420000;
      7'd98: row = 128'h008214f0128400184281000000240000;
      7'd99: row = 128'h004128f0214800812442000000180000;
      7'd100: row = 128'h0041140f841200421881000000180000;
      7'd101: row = 128'h0082280f482100248142000000240000;
      7'd102: row = 128'h0028410f124800182418000000420000;
      7'd103: row = 128'h0014820f218400814224000000810000;
      7'd104: row = 128'h0081f041281400000018428181000000;
      7'd105: row = 128'h0042f082824100000024241842000000;
      7'd106: row = 128'h0024f014412800000081184224000000;
      7'd107: row = 128'h0018f028148200000042812418000000;
      7'd108: row = 128'h00180f14284100000081421818000000;
      7'd109: row = 128'h00240f28821400000042248124000000;
      7'd110: row = 128'h00420f41418200000018182442000000;
      7'd111: row = 128'h00810f82142800000024814281000000;
      7'd112: row = 128'h00f08118428100000000000081184281;
      7'd113: row = 128'h00f04224241800000000000042242418;
      7'd114: row = 128'h00f02481184200000000000024811842;
      7'd115: row = 128'h00f01842812400000000000018428124;
      7'd116: row = 128'h000f1881421800000000000018814218;
      7'd117: row = 128'h000f2442248100000000000024422481;
      7'd118: row = 128'h000f4218182400000000000042181824;
      7'd119: row = 128'h000f8124814200000000000081248142;
      default: row = 128'd0;
    endcase
  end
  assign valid = (u_block < 15) && (v_block < 15);
  assign adjacent = valid && row[v_address];
endmodule

module e8_unitary_voltage_lift_miter(
  input wire [3:0] u_block, input wire [2:0] u_slot,
  input wire [3:0] v_block, input wire [2:0] v_slot, output wire mismatch);
  wire av, aa, rv, ra;
  e8_unitary_voltage_lift_affine a(u_block,u_slot,v_block,v_slot,av,aa);
  e8_unitary_voltage_lift_rom r(u_block,u_slot,v_block,v_slot,rv,ra);
  assign mismatch = (av != rv) || (aa != ra);
endmodule

`default_nettype wire
