// AUTO-GENERATED by analysis/e8_unitary_hole_coset_rtl.js
// GAP/GRAPE certificate sha256: c8085492fe7ea68d20ff07e686ae9eb4ab54016e1c884e1eb0e53e072675812d
// Exact q=3 maximum-spread hole graph: 120 vertices, degree 20.
// The compact circuit stores 1,920 coordinate bits; the independent
// row-ROM reference stores 14,400 adjacency bits.
`default_nettype none

module e8_hole_f3_add(input wire [1:0] a, input wire [1:0] b, output wire [1:0] y);
  wire [2:0] sum = {1'b0,a} + {1'b0,b};
  assign y = (sum >= 3) ? sum - 3 : sum[1:0];
endmodule

module e8_hole_f3_neg(input wire [1:0] a, output wire [1:0] y);
  assign y = (a == 0) ? 0 : ((a == 1) ? 2 : 1);
endmodule

module e8_hole_f3_mul(input wire [1:0] a, input wire [1:0] b, output wire [1:0] y);
  assign y = (a == 0 || b == 0) ? 0 : ((a == 1) ? b : ((b == 1) ? a : 1));
endmodule

module e8_hole_f9_add(input wire [3:0] x, input wire [3:0] y, output wire [3:0] z);
  e8_hole_f3_add ar(.a(x[1:0]), .b(y[1:0]), .y(z[1:0]));
  e8_hole_f3_add ai(.a(x[3:2]), .b(y[3:2]), .y(z[3:2]));
endmodule

// x * conjugate(y), with alpha^2 = alpha+1.
module e8_hole_f9_hermitian_term(input wire [3:0] x, input wire [3:0] y, output wire [3:0] z);
  wire [1:0] yc, yd_neg;
  e8_hole_f3_add conj_real(.a(y[1:0]), .b(y[3:2]), .y(yc));
  e8_hole_f3_neg conj_alpha(.a(y[3:2]), .y(yd_neg));
  wire [1:0] ac, bd, ad, bc, real_sum, alpha_ab;
  e8_hole_f3_mul m_ac(.a(x[1:0]), .b(yc), .y(ac));
  e8_hole_f3_mul m_bd(.a(x[3:2]), .b(yd_neg), .y(bd));
  e8_hole_f3_mul m_ad(.a(x[1:0]), .b(yd_neg), .y(ad));
  e8_hole_f3_mul m_bc(.a(x[3:2]), .b(yc), .y(bc));
  e8_hole_f3_add add_real(.a(ac), .b(bd), .y(real_sum));
  e8_hole_f3_add add_alpha0(.a(ad), .b(bc), .y(alpha_ab));
  e8_hole_f3_add add_alpha1(.a(alpha_ab), .b(bd), .y(z[3:2]));
  assign z[1:0] = real_sum;
endmodule

module e8_unitary_hole_coordinate_rom(input wire [6:0] id, output reg valid, output reg [15:0] coordinate);
  always @* begin
    valid = 1'b1;
    case (id)
      7'd0: coordinate = 16'h1110;
      7'd1: coordinate = 16'h2011;
      7'd2: coordinate = 16'ha051;
      7'd3: coordinate = 16'h1210;
      7'd4: coordinate = 16'h1510;
      7'd5: coordinate = 16'h1021;
      7'd6: coordinate = 16'h1201;
      7'd7: coordinate = 16'h0121;
      7'd8: coordinate = 16'h01a1;
      7'd9: coordinate = 16'h2201;
      7'd10: coordinate = 16'ha201;
      7'd11: coordinate = 16'h0111;
      7'd12: coordinate = 16'h6411;
      7'd13: coordinate = 16'h2891;
      7'd14: coordinate = 16'h9421;
      7'd15: coordinate = 16'ha691;
      7'd16: coordinate = 16'h99a1;
      7'd17: coordinate = 16'h6951;
      7'd18: coordinate = 16'h4451;
      7'd19: coordinate = 16'ha881;
      7'd20: coordinate = 16'h84a1;
      7'd21: coordinate = 16'h1681;
      7'd22: coordinate = 16'h8911;
      7'd23: coordinate = 16'h4921;
      7'd24: coordinate = 16'h4291;
      7'd25: coordinate = 16'h4161;
      7'd26: coordinate = 16'h2691;
      7'd27: coordinate = 16'haa01;
      7'd28: coordinate = 16'h1661;
      7'd29: coordinate = 16'h0511;
      7'd30: coordinate = 16'h4541;
      7'd31: coordinate = 16'h4a81;
      7'd32: coordinate = 16'h5a10;
      7'd33: coordinate = 16'h5021;
      7'd34: coordinate = 16'h1441;
      7'd35: coordinate = 16'h5011;
      7'd36: coordinate = 16'h6a61;
      7'd37: coordinate = 16'h2961;
      7'd38: coordinate = 16'h2481;
      7'd39: coordinate = 16'haa10;
      7'd40: coordinate = 16'h6591;
      7'd41: coordinate = 16'h1991;
      7'd42: coordinate = 16'h9a91;
      7'd43: coordinate = 16'h9561;
      7'd44: coordinate = 16'ha510;
      7'd45: coordinate = 16'ha021;
      7'd46: coordinate = 16'h9241;
      7'd47: coordinate = 16'h9181;
      7'd48: coordinate = 16'h5501;
      7'd49: coordinate = 16'h0a11;
      7'd50: coordinate = 16'h0521;
      7'd51: coordinate = 16'h8261;
      7'd52: coordinate = 16'h5a01;
      7'd53: coordinate = 16'h8191;
      7'd54: coordinate = 16'h9851;
      7'd55: coordinate = 16'h46a1;
      7'd56: coordinate = 16'h94a1;
      7'd57: coordinate = 16'h6451;
      7'd58: coordinate = 16'h4951;
      7'd59: coordinate = 16'h89a1;
      7'd60: coordinate = 16'h0211;
      7'd61: coordinate = 16'h1101;
      7'd62: coordinate = 16'h5101;
      7'd63: coordinate = 16'h0221;
      7'd64: coordinate = 16'h02a1;
      7'd65: coordinate = 16'h2101;
      7'd66: coordinate = 16'h2021;
      7'd67: coordinate = 16'h2110;
      7'd68: coordinate = 16'h2a10;
      7'd69: coordinate = 16'h1011;
      7'd70: coordinate = 16'h5051;
      7'd71: coordinate = 16'h2210;
      7'd72: coordinate = 16'h66a1;
      7'd73: coordinate = 16'h1491;
      7'd74: coordinate = 16'h9651;
      7'd75: coordinate = 16'h5991;
      7'd76: coordinate = 16'h9811;
      7'd77: coordinate = 16'h6821;
      7'd78: coordinate = 16'h4611;
      7'd79: coordinate = 16'h5481;
      7'd80: coordinate = 16'h8621;
      7'd81: coordinate = 16'h2981;
      7'd82: coordinate = 16'h8851;
      7'd83: coordinate = 16'h48a1;
      7'd84: coordinate = 16'h0a21;
      7'd85: coordinate = 16'ha501;
      7'd86: coordinate = 16'h6281;
      7'd87: coordinate = 16'h1881;
      7'd88: coordinate = 16'h6141;
      7'd89: coordinate = 16'h2841;
      7'd90: coordinate = 16'ha011;
      7'd91: coordinate = 16'h5510;
      7'd92: coordinate = 16'h8581;
      7'd93: coordinate = 16'h8a41;
      7'd94: coordinate = 16'h68a1;
      7'd95: coordinate = 16'h8651;
      7'd96: coordinate = 16'h6541;
      7'd97: coordinate = 16'ha441;
      7'd98: coordinate = 16'h4a61;
      7'd99: coordinate = 16'h2461;
      7'd100: coordinate = 16'h9a41;
      7'd101: coordinate = 16'h1941;
      7'd102: coordinate = 16'h9581;
      7'd103: coordinate = 16'ha0a1;
      7'd104: coordinate = 16'h8561;
      7'd105: coordinate = 16'ha961;
      7'd106: coordinate = 16'h8a91;
      7'd107: coordinate = 16'h2510;
      7'd108: coordinate = 16'h5841;
      7'd109: coordinate = 16'h1861;
      7'd110: coordinate = 16'h2641;
      7'd111: coordinate = 16'h5201;
      7'd112: coordinate = 16'h5661;
      7'd113: coordinate = 16'h0151;
      7'd114: coordinate = 16'h6a81;
      7'd115: coordinate = 16'h0251;
      7'd116: coordinate = 16'h4591;
      7'd117: coordinate = 16'ha101;
      7'd118: coordinate = 16'h1a10;
      7'd119: coordinate = 16'h50a1;
      default: begin valid = 1'b0; coordinate = 16'h0000; end
    endcase
  end
endmodule

module e8_unitary_hole_adj_compact(
  input wire [6:0] u_id, input wire [6:0] v_id, output wire valid, output wire adjacent);
  wire u_valid, v_valid;
  wire [15:0] u, v;
  e8_unitary_hole_coordinate_rom ur(.id(u_id), .valid(u_valid), .coordinate(u));
  e8_unitary_hole_coordinate_rom vr(.id(v_id), .valid(v_valid), .coordinate(v));
  wire [3:0] t0, t1, t2, t3, s0, s1, form;
  e8_hole_f9_hermitian_term h0(.x(u[3:0]), .y(v[3:0]), .z(t0));
  e8_hole_f9_hermitian_term h1(.x(u[7:4]), .y(v[7:4]), .z(t1));
  e8_hole_f9_hermitian_term h2(.x(u[11:8]), .y(v[11:8]), .z(t2));
  e8_hole_f9_hermitian_term h3(.x(u[15:12]), .y(v[15:12]), .z(t3));
  e8_hole_f9_add a0(.x(t0), .y(t1), .z(s0));
  e8_hole_f9_add a1(.x(t2), .y(t3), .z(s1));
  e8_hole_f9_add a2(.x(s0), .y(s1), .z(form));
  assign valid = u_valid && v_valid;
  assign adjacent = valid && (u_id != v_id) && (form == 4'b0000);
endmodule

// Independent full-row implementation retained as the formal golden model.
module e8_unitary_hole_adj_rom(
  input wire [6:0] u_id, input wire [6:0] v_id, output wire valid, output wire adjacent);
  reg [119:0] row;
  wire valid_u = (u_id < 120);
  wire valid_v = (v_id < 120);
  wire [6:0] safe_v = valid_v ? v_id : 0;
  always @* begin
    case (u_id)
      7'd0: row = 120'h802401002000021a10400001a040e6;
      7'd1: row = 120'h40104400100000aa048000021280d9;
      7'd2: row = 120'h408110008000014019400004a03119;
      7'd3: row = 120'h80404400400000a509000008403a26;
      7'd4: row = 120'h8201100200000140268000100e8426;
      7'd5: row = 120'h4104010100000215220000200d0a19;
      7'd6: row = 120'h130010080000840a00048040481983;
      7'd7: row = 120'h04c100040000280a00080880052643;
      7'd8: row = 120'h40800500800050000000914448c644;
      7'd9: row = 120'h06110010000028050010110080c9a8;
      7'd10: row = 120'h820005020000500000010a90312990;
      7'd11: row = 120'h10a010200000840500210200320668;
      7'd12: row = 120'h07000108002100000904440016604c;
      7'd13: row = 120'h10340040000a00004900088009948c;
      7'd14: row = 120'h802050002014000000005501159301;
      7'd15: row = 120'h11440080000a000084801100226312;
      7'd16: row = 120'h4100500100140000000228a0c264a0;
      7'd17: row = 120'h04a001200021000004a22000c19812;
      7'd18: row = 120'h10c0040408400000220844009850b0;
      7'd19: row = 120'h043040400280000062008040642170;
      7'd20: row = 120'h401500001500000000014602645c02;
      7'd21: row = 120'h054040800280000090410200988c05;
      7'd22: row = 120'h80450000450000000002a0489b0148;
      7'd23: row = 120'h121004100840000010522000670205;
      7'd24: row = 120'h8020000024801404a00700e6004001;
      7'd25: row = 120'h4010000010124804880830d9100002;
      7'd26: row = 120'h408000008145000024170c19000104;
      7'd27: row = 120'h804000004012480844100f26400008;
      7'd28: row = 120'h82000002014500001828f026000410;
      7'd29: row = 120'h41000001048014085020c319010020;
      7'd30: row = 120'h200008230004001480408683480140;
      7'd31: row = 120'h08000210c100002480804943012480;
      7'd32: row = 120'h0800020611000028410212a800c300;
      7'd33: row = 120'h20000808a004001842012168300c00;
      7'd34: row = 120'h08008023000010400450684c145000;
      7'd35: row = 120'h20002080340000810410948c012480;
      7'd36: row = 120'h20002041440000820809291200c300;
      7'd37: row = 120'h08008008a00010400a0a1612c30000;
      7'd38: row = 120'h20080010c000410010a284b0145000;
      7'd39: row = 120'h080200803010020110214870480140;
      7'd40: row = 120'h080200414010020220069205300c00;
      7'd41: row = 120'h200800061000410021056105c30000;
      7'd42: row = 120'h030000080a00005160eb0005001040;
      7'd43: row = 120'h00c000040028012148d43012040080;
      7'd44: row = 120'h021000100028012287280c0c800200;
      7'd45: row = 120'h00a000200a0000529314c030020800;
      7'd46: row = 120'h000a002300010401528c0440a00005;
      7'd47: row = 120'h0000a010c0400801454c4080028012;
      7'd48: row = 120'h0000a006104008028ab2010000300c;
      7'd49: row = 120'h000a0008a0010402a17022000c0030;
      7'd50: row = 120'h0008024c0800200418900c0c028012;
      7'd51: row = 120'h000802b0080020082508301200300c;
      7'd52: row = 120'h0000884c002080042460c030a00005;
      7'd53: row = 120'h000088b0002080081a0700050c0030;
      7'd54: row = 120'h003000400000a28980cc0328082000;
      7'd55: row = 120'h014000800000a286433000c3208000;
      7'd56: row = 120'h00000a803082000640cc8800000a28;
      7'd57: row = 120'h00000a4140820009833110000000c3;
      7'd58: row = 120'h0002204c02080009940000c3000a28;
      7'd59: row = 120'h000220b002080006680003280000c3;
      7'd60: row = 120'h200409c00a040e6000240240000021;
      7'd61: row = 120'h080046c001280d900018018000000a;
      7'd62: row = 120'h080190140a03119000242400000014;
      7'd63: row = 120'h200064140403a260c000180000000a;
      7'd64: row = 120'h2009102800e84260001a4000000014;
      7'd65: row = 120'h0806012800d0a190c0018000000021;
      7'd66: row = 120'h100a10c00481983002400021000840;
      7'd67: row = 120'h0401a0c0005264300180000a000280;
      7'd68: row = 120'h08008500548c644000002421000500;
      7'd69: row = 120'h04090200580c9a80cc000000000280;
      7'd70: row = 120'h20080501231299000002400a000500;
      7'd71: row = 120'h1000980123206680f0000000000840;
      7'd72: row = 120'h040a0114016604c002400014021000;
      7'd73: row = 120'h10040a14009948c30000000a00a000;
      7'd74: row = 120'h200058005159301000000254014000;
      7'd75: row = 120'h100620005226312c0018000000a000;
      7'd76: row = 120'h080250028c264a000001800a014000;
      7'd77: row = 120'h040089028c19812030180000021000;
      7'd78: row = 120'h1000a42809850b0001800014840000;
      7'd79: row = 120'h04004a280642170300000021280000;
      7'd80: row = 120'h080502012645c02000000194500000;
      7'd81: row = 120'h040260012988c05c00240000280000;
      7'd82: row = 120'h2005200289b0148000001821500000;
      7'd83: row = 120'h10080602867020500c240000840000;
      7'd84: row = 120'h40100086600c300101028902100002;
      7'd85: row = 120'h802000899300c0010200aa01004001;
      7'd86: row = 120'h80400051900c300200815088400008;
      7'd87: row = 120'h4080001a6c30000002806284000104;
      7'd88: row = 120'h410000626300c00200411460010020;
      7'd89: row = 120'h820000259c30000001420550000410;
      7'd90: row = 120'h00c0005a100300c4150a0100040080;
      7'd91: row = 120'h03000064a0c0030416042200001040;
      7'd92: row = 120'h021000a4c00300c828904080800200;
      7'd93: row = 120'h00a0009b00c0030828600440020800;
      7'd94: row = 120'h0030008d40000c3654011000082000;
      7'd95: row = 120'h0140007030000c39a8008800208000;
      7'd96: row = 120'h045436000021521000000000021521;
      7'd97: row = 120'h08583900098220230c000180000000;
      7'd98: row = 120'h11234900084050a00000000084050a;
      7'd99: row = 120'h2123860000a6801330000240000000;
      7'd100: row = 120'h105163000014854000000000014854;
      7'd101: row = 120'h205293000648088c01801800000000;
      7'd102: row = 120'h068c9400029400a00000000029400a;
      7'd103: row = 120'h0a8c68000060984031802400000000;
      7'd104: row = 120'h05261c000500294000000000500294;
      7'd105: row = 120'h09292c000219060c02418000000000;
      7'd106: row = 120'h1289c100050a02100000000050a021;
      7'd107: row = 120'h2286c200080165000e424000000000;
      7'd108: row = 120'h426033501000000040100002982202;
      7'd109: row = 120'h81930c6020000000402000010a6801;
      7'd110: row = 120'h819033844000000080080008648088;
      7'd111: row = 120'h426cc0248000000000280004060984;
      7'd112: row = 120'h42630c890000000080040020219060;
      7'd113: row = 120'h819cc01a0000000000140010801650;
      7'd114: row = 120'hf801410002a12800000000002a1280;
      7'd115: row = 120'hf4028200011012600001a580000000;
      7'd116: row = 120'hec041400084a84000000000084a840;
      7'd117: row = 120'hdc0828000404419000025a40000000;
      7'd118: row = 120'hbd9000019000000000000026110126;
      7'd119: row = 120'h7e6000026000000000000019404419;
      default: row = 120'h000000000000000000000000000000;
    endcase
  end
  assign valid = valid_u && valid_v;
  assign adjacent = valid && row[safe_v];
endmodule

`default_nettype wire
