// ======================================================================
// HoloTrade frontier v3: five requested continuations + hypercube math spine
// ======================================================================
const assert=require("node:assert/strict");const test=require("node:test");const path=require("node:path");
const root=path.resolve(__dirname,"..");global.window=global;
const S=require(path.join(root,"js/substrate.js"));const catalog=require(path.join(root,"data/catalog.js"));const EnergyEngine=require(path.join(root,"js/energy.js"));const {Fleet}=require(path.join(root,"js/fleet.js"));const {PricingEngine}=require(path.join(root,"js/pricing.js"));
const E=require(path.join(root,"js/evidence.js"));require(path.join(root,"js/uor.js"));const {ExecutionEngine}=require(path.join(root,"js/execution.js"));require(path.join(root,"js/execution-evidence.js"));const P=require(path.join(root,"js/projection.js"));const C=require(path.join(root,"js/w33-transition-certificate.js"));const Sig=require(path.join(root,"js/signing.js"));const W=require(path.join(root,"js/w33-scheduler.js"));const Challenge=require(path.join(root,"js/challenge-market.js"));
const R=require(path.join(root,"js/result-contract.js"));const Q=require(path.join(root,"js/hypercube.js"));const Venue=require(path.join(root,"js/spread-venue-market.js"));const T=require(path.join(root,"js/transparency.js"));const Cap=require(path.join(root,"js/capability-market.js"));const Risk=require(path.join(root,"js/capability-risk.js"));const Replay=require(path.join(root,"js/replay-quorum.js"));
function build(seed="v3"){const energy=new EnergyEngine(catalog.DATACENTERS,`${seed}-energy`);const fleet=new Fleet({datacenters:catalog.DATACENTERS,hardware:catalog.HARDWARE,workloads:catalog.WORKLOADS,operators:catalog.OPERATORS,size:120,seed:`${seed}-fleet`});const pricing=new PricingEngine(fleet,energy,catalog.WORKLOADS);const exec=new ExecutionEngine(fleet,pricing,energy,catalog.WORKLOADS);return{exec};}
function register(exec,id,extra={}){return exec.registerEvidence({id,subject:id,status:E.STATUS.VERIFIED,evidenceClass:E.EVIDENCE_CLASS.REPO_CERTIFICATE,scope:E.SCOPE.REGRESSION,claim:`v3 evidence ${id}`,createdAt:1,...extra});}
function typedProjection(exec,seed="typed"){register(exec,`cert:${seed}`);const contract=new R.ResultContract({id:`contract:${seed}`,schemaId:"urn:holotrade:test-result:v1"});const projection=R.bindProjection({id:`projection:${seed}`,workloadId:"genomics",inputs:[new P.ResourceRef({id:`input:${seed}`,role:"source",digest:`sha256:${"a".repeat(64)}`})],evidenceRefs:[`cert:${seed}`],evidencePolicy:E.POLICY.VERIFIED,outputKind:"dataset"},contract);return{contract,projection};}

test("semantic result contract is a first-class pinned resource and SHA-256 identity is provenance-independent",()=>{const{exec}=build("result");const{contract,projection}=typedProjection(exec,"result");assert.ok(projection.inputs.some((x)=>x.role==="result-contract"&&x.digest===contract.digest));const pe=new P.ProjectionEngine(exec);const created=pe.createPlan(projection,{requestedSeconds:1});assert.ok(created.plan.artifacts.some((a)=>a.digest===contract.digest));const node=exec.place(created.plan,{limit:8})[0].node;assert.equal(exec.launch(created.plan,node).ok,true);const receipt=exec.meter(1).find((r)=>r.planId===created.plan.id);const value={answer:42,nested:{b:2,a:1}};const emission=R.emit(pe,projection,created.plan,receipt,{contract,value});assert.equal(emission.output.result.schema,R.RESULT_SCHEMA);assert.equal(R.verifyCommitment(emission.output.result,contract,{nested:{a:1,b:2},answer:42}).ok,true);assert.equal(R.resultDigestOf(emission),emission.output.result.digest);assert.notEqual(R.commit({answer:43},contract).digest,emission.output.result.digest);const cert=C.buildCertificate({projection,plan:created.plan,receipt,emission,executionEngine:exec,projectionEngine:pe});assert.equal(cert.status,"PASS");});

test("Q4 controller certificate closes Gray/e-cube and antipodal face-edge Reye counts without claiming a W33 vertex cube",()=>{const cert=Q.certificate();assert.equal(cert.valid,true);assert.equal(cert.counts.vertices,16);assert.equal(cert.counts.edges,32);assert.equal(cert.counts.faces,24);assert.equal(cert.counts.edgeClasses,16);assert.equal(cert.counts.faceClasses,12);assert.equal(cert.counts.incidences,48);for(let a=0;a<16;a++)for(let b=0;b<16;b++){const r=Q.eCubeRoute(a,b);assert.equal(r.shortest,true);assert.equal(r.distance,Q.hamming(a,b));}const overlay=Q.sectorOverlay(W.spreadCertificate(0).anchorLines);assert.equal(new Set(Object.values(overlay.dimensions)).size,4);assert.equal(overlay.canonical,false);});

test("spread venue graph has 360 one-line pairs, 270 four-line pairs, and canonical ten line-preserving Johnson-antipode hedges per anchor",()=>{const global=Venue.globalCertificate();assert.equal(global.valid,true);assert.deepEqual(global.pairHistogram,{oneLine:360,fourLines:270});const a=Venue.anchorCertificate(0);assert.equal(a.valid,true);assert.equal(a.hedges.length,10);assert.ok(a.hedges.every((h)=>h.legs.length===2&&h.remoteDistance===3&&h.legOverlap===1&&h.tripleCommon[0]===h.lineId));for(const lineId of a.anchorLines){const f=Venue.lineFiberCertificate(lineId);assert.equal(f.valid,true);assert.equal(f.fiber.length,9);assert.equal(f.oneLineTriangles.length,3);}const book=new Venue.SpreadVenueBook();for(let i=0;i<36;i++)book.mark(i,1+i/100);const quotes=book.quoteHedges(0);assert.equal(quotes.length,10);assert.ok(quotes.every((x)=>Number.isFinite(x.twoLegCost)&&Number.isFinite(x.basis)));});

test("risk-adjusted capability cover can reject the cheapest high-correction-risk bundle while preserving exact coverage",()=>{const{exec}=build("risk");register(exec,"cert:cheap",{evidenceClass:E.EVIDENCE_CLASS.MODEL_RESULT});register(exec,"cert:safe-a",{evidenceClass:E.EVIDENCE_CLASS.FORMAL_WITNESS});register(exec,"cert:safe-b",{evidenceClass:E.EVIDENCE_CLASS.FORMAL_WITNESS});const profile=Cap.profileResource({nodeId:"RISK-NODE",hardwareKind:"gpu",capabilities:["fp16"],evidenceRefs:["cert:safe-a"]});const offers=[new Cap.CapabilityOffer({id:"cheap-combo",vendor:"cheap",capabilities:["int8","sparse"],hardwareKinds:["gpu"],evidenceRefs:["cert:cheap"],price:1,metadata:{correctionRisk:1}}),new Cap.CapabilityOffer({id:"safe-int8",vendor:"safe",capabilities:["int8"],hardwareKinds:["gpu"],evidenceRefs:["cert:safe-a"],price:2,metadata:{correctionRisk:0}}),new Cap.CapabilityOffer({id:"safe-sparse",vendor:"safe",capabilities:["sparse"],hardwareKinds:["gpu"],evidenceRefs:["cert:safe-b"],price:2,metadata:{correctionRisk:0}})];const exchange=new Cap.CapabilityExchange(offers);assert.deepEqual(exchange.bestBundle(profile,["int8","sparse"]).offerIds,["cheap-combo"]);const adjusted=Risk.bestRiskAdjustedBundle(exchange,profile,["int8","sparse"],{ledger:exec.evidenceLedger,weights:{price:1,evidence:1,locality:0,correction:10}});assert.equal(adjusted.complete,true);assert.deepEqual(adjusted.offerIds,["safe-int8","safe-sparse"]);assert.equal(adjusted.totalPrice,4);});

test("threshold DSSE can be anchored in an RFC6962-style signed Merkle checkpoint and tampering is refused",()=>{const s1=Sig.generateKeyPair(),s2=Sig.generateKeyPair(),logKey=Sig.generateKeyPair();const log=new T.TransparencyLog({privateKey:logKey.privateKey,publicKey:logKey.publicKey,logId:"test-log"});const payload1={kind:"certificate",n:1},payload2={kind:"certificate",n:2};const e1=Sig.signDSSE(payload1,[s1,s2]),e2=Sig.signDSSE(payload2,[s1,s2]);log.appendEnvelope(e1);log.appendEnvelope(e2);const bundle=log.inclusion(0,1234);const trusted=new Map([["s1",s1.publicKey],["s2",s2.publicKey]]);const verified=T.verifyTransparentThreshold(e1,trusted,bundle,{threshold:2,expectedPayload:payload1,logPublicKey:logKey.publicKey});assert.equal(verified.ok,true);assert.equal(verified.transparency.included,true);assert.equal(verified.externalPublicLog,false);const bad={...bundle,path:bundle.path.map((x,i)=>i?x:{...x,hash:Buffer.alloc(32).toString("base64")})};assert.equal(T.verifyTransparentThreshold(e1,trusted,bad,{threshold:2,expectedPayload:payload1,logPublicKey:logKey.publicKey}).ok,false);});

test("three independent executions on distinct W33 sectors produce a priced certified semantic replay quorum",()=>{const{exec}=build("replay-v3");const{contract,projection}=typedProjection(exec,"replay-v3");const pe=new P.ProjectionEngine(exec);const planned=Replay.planSectorQuorum(pe,exec,projection,{quorum:3,requestedSeconds:1,maxCandidates:48,perSectorLimit:8});assert.equal(planned.distinctNodes,true);assert.equal(planned.distinctSectors,true);assert.equal(planned.selected.length,3);assert.equal(new Set(planned.selected.map((x)=>x.q4Dimension)).size,3);const executed=Replay.executeSectorQuorum(pe,exec,projection,planned,{contract,resultValue:{answer:"same deterministic result"}});assert.equal(executed.bundles.length,3);assert.ok(executed.actualCost>0);assert.equal(new Set(executed.bundles.map((b)=>b.certificate.element.digest)).size,3,"provenance identities differ across independent executions");assert.equal(new Set(executed.bundles.map((b)=>R.resultDigestOf(b.emission))).size,1,"semantic result identity agrees");const q=Replay.verifyExecutedQuorum(executed,{bounty:5});assert.equal(q.verified,true);assert.equal(q.distinctNodes,3);assert.equal(q.distinctSectors,3);assert.ok(q.totalActualCost>0);});
