#!/usr/bin/env node
// Emit a complete 40-node / 240-link Containerlab topology for W(3,3).
// Generation is tested; deployment is intentionally reported separately.

"use strict";

const { EDGES } = require("./w33-scheduler.js");

function nodeName(index) {
  return `w33-${String(index).padStart(2, "0")}`;
}

function containerlabYaml() {
  const lines = [
    "# Generated by scheduler/containerlab-export.js",
    "# Exact graph export: 40 Linux nodes, 240 W(3,3) point-graph links.",
    "# GENERATION_TESTED=true; CONTAINERLAB_DEPLOYED=false in the frozen A/B packet.",
    "name: holotrade-w33",
    "topology:",
    "  defaults:",
    "    kind: linux",
    "    image: alpine:3.20",
    "    cmd: sleep infinity",
    "  nodes:",
  ];
  for (let node = 0; node < 40; node++) lines.push(`    ${nodeName(node)}: {}`);
  lines.push("  links:");
  const nextPort = Array(40).fill(1);
  for (const [a, b] of EDGES) {
    const aPort = nextPort[a]++;
    const bPort = nextPort[b]++;
    lines.push(`    - endpoints: [\"${nodeName(a)}:eth${aPort}\", \"${nodeName(b)}:eth${bPort}\"]`);
  }
  if (!nextPort.every((port) => port === 13)) throw new Error("W(3,3) export lost 12-regularity");
  return `${lines.join("\n")}\n`;
}

if (require.main === module) process.stdout.write(containerlabYaml());

module.exports = { nodeName, containerlabYaml };
