#!/usr/bin/env python3
"""First genuinely noncommutative attack on the depth-five seed cover.

The full depth-five quotient is a set cover with 5,294 seed/leaf orbits and
6,129 tile orbits.  Subgroup-induced LP cuts leave the relaxation unchanged at
12.671477..., so this script changes relaxations rather than subgroups.

PAIRWISE CONFLICT GRAPH.
Two tile orbits are *co-coverable* when some seed orbit covers both.  The set of
tiles covered by one seed is therefore a clique in the co-coverability graph H.
Any k-seed cover induces a clique cover of H, equivalently a k-colouring of its
conflict complement C. Hence

    depth5 seeds >= chi(C) >= omega(C),
    depth5 seeds >= theta(H).

The integer packing model below searches omega(C): choose tile orbits so that
no seed orbit covers two chosen tiles.  Any feasible packing is an exact lower
bound even if the maximisation times out.  In parallel a small induced
Lovasz-theta SDP is solved numerically as an exploratory (not rigorous) probe.

TERWILLIGER ALGEBRA.
For the W33 point graph we build the subconstituent/Terwilliger algebra at one
point, generated by A and the three dual distance idempotents E_i*.  Its exact
algebra and centre dimensions, plus a generic central spectrum on the standard
40-space, are frozen.  This is the local noncommutative algebra intended for a
future block-diagonal Schrijver/N+ relaxation.

The theta value is explicitly labelled numerical unless independently replaced
by a rational PSD certificate.  The packing bound is exact.
"""
from __future__ import annotations
import itertools, json, math, random
from pathlib import Path

import numpy as np
import sympy as sp

import depth5_induced_subgroup_cuts as old

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/depth5_terwilliger_theta_attack.json'


def rank_mod_cols(cols,p=1000003):
    if not cols:return 0
    A=np.stack(cols,axis=1).astype(np.int64)%p
    m,n=A.shape;r=0
    for c in range(n):
        z=next((i for i in range(r,m) if A[i,c]),None)
        if z is None:continue
        if z!=r:A[[r,z]]=A[[z,r]]
        A[r]=(A[r]*pow(int(A[r,c]),-1,p))%p
        for i in range(m):
            if i!=r and A[i,c]:A[i]=(A[i]-int(A[i,c])*A[r])%p
        r+=1
        if r==m:break
    return r


def terwilliger(pts,lines):
    A=np.zeros((40,40),dtype=np.int64)
    for L in lines:
        for a,b in itertools.combinations(L,2):A[a,b]=A[b,a]=1
    assert set(A.sum(axis=1))=={12}
    x=0; d0={x};d1=set(np.flatnonzero(A[x]));d2=set(range(40))-d0-d1
    assert [len(d0),len(d1),len(d2)]==[1,12,27]
    E=[]
    for S in (d0,d1,d2):
        M=np.zeros((40,40),dtype=np.int64)
        for i in S:M[i,i]=1
        E.append(M)
    gens=[A]+E
    I=np.eye(40,dtype=np.int64)
    basis=[I];flat=[I.reshape(-1)]
    changed=True
    while changed:
        changed=False
        snapshot=list(basis)
        for B in snapshot:
            for G in gens:
                C=B@G;v=C.reshape(-1)
                if rank_mod_cols(flat+[v])>len(flat):
                    basis.append(C);flat.append(v);changed=True
    exact_rank=sp.Matrix(np.stack(flat,axis=1).tolist()).rank();assert exact_rank==len(basis)
    d=len(basis)
    # Centre = coefficient vectors whose linear combination commutes with generators.
    blocks=[]
    for G in gens:
        blocks.append(np.stack([(B@G-G@B).reshape(-1) for B in basis],axis=1))
    C=sp.Matrix(np.vstack(blocks).tolist())
    zns=C.nullspace(); zdim=len(zns)
    Zm=[]
    for z in zns:
        M=sp.zeros(40,40)
        for c,B in zip(z,basis):
            if c:M+=c*sp.Matrix(B.tolist())
        Zm.append(M)
    # Find a deterministic centre element separating as many standard-module
    # central eigenspaces as possible.
    best=None
    for shift in range(1,8):
        M=sum(((i+shift)*Zm[i] for i in range(zdim)),sp.zeros(40,40))
        fac=sp.factor_list(M.charpoly().as_expr())[1]
        score=len(fac)
        if best is None or score>best[0]:best=(score,M,fac,shift)
    score,M,fac,shift=best
    factors=[{'factor':str(f),'multiplicity':int(e),'degree':int(sp.degree(f))} for f,e in fac]
    return {'baseVertex':0,'distanceLayerSizes':[1,12,27],'algebraDimension':d,
            'centerDimension':zdim,'genericCenterShift':shift,
            'genericCenterCharpolyFactors':factors,'noncommutative':d>zdim}


def greedy_packing(A,tries=600):
    bits=[]
    for t in range(A.shape[0]):
        b=0
        for o in A.indices[A.indptr[t]:A.indptr[t+1]]:b|=1<<int(o)
        bits.append(b)
    rng=random.Random(1701);best=[]
    order0=sorted(range(len(bits)),key=lambda t:(bits[t].bit_count(),t))
    for it in range(tries):
        order=order0[:] if it==0 else list(range(len(bits)))
        if it: rng.shuffle(order)
        used=0;pick=[]
        for t in order:
            if bits[t]&used==0:
                pick.append(t);used|=bits[t]
        if len(pick)>len(best):best=pick
    return best,bits


def numerical_theta(bits,packing,maxn=90):
    try:
        import cvxpy as cp
    except Exception as e:
        return {'status':'SKIPPED','reason':repr(e)}
    K=set(packing)
    score=[]
    for v,b in enumerate(bits):
        if v in K:continue
        # conflict count against the exact packing (disjoint supports)
        c=sum((b&bits[u])==0 for u in packing)
        score.append((-c,b.bit_count(),v))
    S=list(packing)+[v for _c,_w,v in sorted(score)[:max(0,maxn-len(packing))]]
    n=len(S);X=cp.Variable((n,n),symmetric=True)
    cons=[X >> 0, cp.trace(X)==1]
    coedges=0
    for i in range(n):
        for j in range(i+1,n):
            if bits[S[i]]&bits[S[j]]:
                cons.append(X[i,j]==0);cons.append(X[j,i]==0);coedges+=1
    prob=cp.Problem(cp.Maximize(cp.sum(X)),cons)
    try:
        val=prob.solve(solver='CLARABEL',verbose=False)
    except Exception:
        val=prob.solve(solver='SCS',eps=1e-6,max_iters=100000,verbose=False)
    return {'status':str(prob.status),'subsetSize':n,'coCoverEdges':coedges,
            'thetaHNumerical':None if val is None else float(val),
            'rigorous':False,
            'reading':'Numerical primal SDP probe only; do not round this into a theorem without a rational PSD certificate.'}


def main():
    from ortools.sat.python import cp_model
    pts,idx,iso,supports,charts,edge_reg=old.geometry()
    Talg=terwilliger(pts,iso)
    leaf_id,A=old.full_orbit_machine(pts,iso)
    assert A.shape==(6129,5294)
    greedy,bits=greedy_packing(A)

    # Exact set-packing search. A feasible solution of value k proves the cover
    # needs at least k seeds regardless of optimality status.
    csc=A.tocsc();m=cp_model.CpModel();y=[m.NewBoolVar(f'y{t}') for t in range(A.shape[0])]
    for o in range(A.shape[1]):
        rows=csc.indices[csc.indptr[o]:csc.indptr[o+1]]
        if len(rows)>1:m.Add(sum(y[int(t)] for t in rows)<=1)
    m.Maximize(sum(y))
    for t in greedy:m.AddHint(y[t],1)
    s=cp_model.CpSolver();s.parameters.max_time_in_seconds=900;s.parameters.num_search_workers=8;s.parameters.random_seed=20260901
    st=s.Solve(m);name=s.StatusName(st)
    best=int(round(s.ObjectiveValue())) if name in ('OPTIMAL','FEASIBLE') else len(greedy)
    pick=[t for t in range(A.shape[0]) if name in ('OPTIMAL','FEASIBLE') and s.Value(y[t])]
    if not pick:pick=greedy
    assert all(bits[a]&bits[b]==0 for a,b in itertools.combinations(pick,2))

    theta=numerical_theta(bits,pick)
    out={'schema':'holotrade.depth5-terwilliger-theta-attack.v1','valid':True,
      'depth5':{'leafOrbits':5294,'tileOrbits':6129,'previousLP':12.671477085143657,'previousLowerBound':13,'bestKnownCover':22},
      'terwilliger':Talg,
      'conflictPacking':{'greedySize':len(greedy),'solverStatus':name,'feasiblePackingSize':len(pick),
                         'solverObjective':best,'solverBestUpperBound':float(s.BestObjectiveBound()) if name in ('OPTIMAL','FEASIBLE') else None,
                         'tileOrbitIndices':pick,
                         'exactCoverLowerBound':len(pick),
                         'strictlyImproves13':len(pick)>=14},
      'thetaProbe':theta,
      'theorem':('The pairwise conflict formulation is valid: every seed covers a clique of the co-coverability graph, so every pairwise-incompatible tile packing is an exact seed lower bound and Lovasz theta of the co-coverability graph is an SDP lower bound on the clique-cover number. The reported packing is checked directly against the full 6129x5294 coverage relation.'),
      'boundary':('Only the integer packing size is an exact new lower-bound certificate. The finite Terwilliger algebra is exact. The small theta solve is numerical exploration until rational PSD certification; no numerical theta value is promoted to the depth-five lower bound.')}
    OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps({'valid':True,'Terwilliger':[Talg['algebraDimension'],Talg['centerDimension']],
      'packing':len(pick),'packingStatus':name,'theta':theta.get('thetaHNumerical'),'improves':len(pick)>=14},sort_keys=True))

if __name__=='__main__':main()
