#!/usr/bin/env python3
"""
The 27 lines of the cost quadrangle ARE the 27 opposite points of W(3,3): the
same torsor under the qutrit Pauli group. The open item from 8982d36, closed.

WHAT WAS OPEN.  8982d36 proved the 40 distinguished ovoids of the expensive
geometry are the 40 points of W(3,3) as PSp(4,3)-sets, by an equivariant
bijection checked on every generator. Its boundary then said plainly:
"Establishing psi does NOT establish that the 27 appearing here is the same 27
as [THE_27_FOLD_WAY]'s -- that remains open and is the next thing to build."
This builds it.

THE TWO 27s.  W33-Theory's Passes 368-371 fix a point p0 of W(3,3), split the 40
as 1 + 12 + 27, and show the elation group -- order 27, exponent 3, nonabelian,
the Kantor-Sahoo-Sastry Heisenberg group, i.e. the single-qutrit Pauli group
<X, Z, wI> -- acts REGULARLY on the 27 opposite points. Mine are the 27 lines of
GQ(4,2), the maximal anticommuting sets of the 45 expensive instructions
(605f5e5). Different objects, both of size 27, and only Stab(p0) preserves both,
so that is where they must be compared.

    Stab(p0)                                       648    [25920/40]
    orbits on the 27 OPPOSITE points               [27]   transitive
    orbits on MY 27 GQ-LINES                       [27]   transitive

THE ELATION GROUP ACTS REGULARLY ON BOTH.  Inside Stab(p0), a Sylow 3-subgroup
has order 81, and it contains an order-27 subgroup that is exponent 3 and
NONabelian -- the Heisenberg group of the reference:

    order 27, exponent 3, nonabelian
    regular on the 27 opposite points               yes    [their result]
    regular on MY 27 GQ-lines                       yes    [new]

A group acting regularly on two sets makes them isomorphic as G-sets, and the
bijection is explicit rather than abstract:

    equivariant bijection chi: 27 opposite points -> 27 GQ-lines
    bijective                                       yes
    intertwines the whole elation group             yes

So the 27 lines of the cost quadrangle and the 27 of the cubic surface are one
torsor, and the item left open in 8982d36 is closed.

WHAT NOW SITS ON A SINGLE 27.  The two tracks had attached different algebra to
what is now provably the same set:

    their side   an order-27 exponent-3 group acting REGULARLY on it
                 -- the single-qutrit Pauli group, a 3-GROUP
    this side    order-32 extraspecial 2^{1+4}_- groups INDEXED by it,
                 one per line, sharing the centre -I -- 2-GROUPS (34f2a84)

One 27 carrying a qutrit Pauli torsor and indexing 27 qubit-shaped Pauli groups.
That was a coincidence of counts when 34f2a84 and fe4fb77 noticed it; it is now
a statement about one object.

A LIMIT ON THE SEARCH, STATED.  THE_27_FOLD_WAY reports that the order-27
subgroups of a Sylow 3-subgroup are exactly four Frattini-hyperplane preimages,
of which the elementary abelian one fails to be regular. The enumeration here
looked only at subgroups generated by TWO elements of order 3, and found exactly
one -- the exponent-3 extraspecial. That is the one the result needs, and the
others are presumably the exponent-9 cases which two order-3 elements will not
generate; but all four were NOT enumerated here, so this reproduces their
regularity result for one subgroup rather than re-deriving their classification.

SCOPE.  Exhaustive where it counts: PSp(4,3) built out to all 25,920 distinct
actions, Stab(p0) as the full 648, transitivity by orbit computation, regularity
by checking the action is free and transitive, and chi verified against every
element of the elation group. CITED and not derived: the identification of the
elation group with the single-qutrit Pauli group, the 1+12+27 split, and the
classification of order-27 subgroups -- all from W33-Theory Passes 368-371
(analysis/THE_27_FOLD_WAY.md). This closes the 27 question only; it says nothing
about whether the 36 here are BT810's spreads, which remains by invariants.
tau_2 is untouched.
"""

import collections
import itertools
import json
import os
import random
import sys

ROOT = r"C:\Repos\Holotrade"
Q = 3
D = 4


def main():
    def mul(A, B):
        return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(D)) % Q
                           for j in range(D)) for i in range(D))

    I = tuple(tuple(1 if i == j else 0 for j in range(D)) for i in range(D))
    mI = tuple(tuple((-1 if i == j else 0) % Q for j in range(D))
               for i in range(D))

    def form(u, v):
        return (u[0] * v[2] - u[2] * v[0] + u[1] * v[3] - u[3] * v[1]) % Q

    E = [tuple(1 if k == j else 0 for k in range(D)) for j in range(D)]

    def tv(vv, lam):
        return tuple(tuple(((1 if i == j else 0)
                            + lam * form(E[j], vv) * vv[i]) % Q
                           for j in range(D)) for i in range(D))

    def minv(A):
        Aug = [[A[i][j] for j in range(D)]
               + [1 if i == j else 0 for j in range(D)] for i in range(D)]
        r = 0
        for c in range(D):
            p = next((i for i in range(r, D) if Aug[i][c] % Q), None)
            Aug[r], Aug[p] = Aug[p], Aug[r]
            iv = pow(Aug[r][c], -1, Q)
            Aug[r] = [(x * iv) % Q for x in Aug[r]]
            for i in range(D):
                if i != r and Aug[i][c] % Q:
                    f = Aug[i][c]
                    Aug[i] = [(Aug[i][j] - f * Aug[r][j]) % Q
                              for j in range(2 * D)]
            r += 1
        return tuple(tuple(Aug[i][D + j] for j in range(D)) for i in range(D))

    vecs = [v for v in itertools.product(range(Q), repeat=D) if any(v)]
    T = sorted({tv(v, l) for v in vecs for l in (1, 2)} - {I})
    dist, fr = {I: 0}, [I]
    d0 = 0
    while fr:
        nx = []
        for A in fr:
            for M2 in T:
                C = mul(M2, A)
                if C not in dist:
                    dist[C] = d0 + 1
                    nx.append(C)
        fr = nx
        if nx:
            d0 += 1

    def rk(A):
        M2 = [[(A[i][j] - (1 if i == j else 0)) % Q for j in range(D)]
              for i in range(D)]
        r = 0
        for c in range(D):
            p = next((i for i in range(r, D) if M2[i][c] % Q), None)
            if p is None:
                continue
            M2[r], M2[p] = M2[p], M2[r]
            iv = pow(M2[r][c], -1, Q)
            M2[r] = [(x * iv) % Q for x in M2[r]]
            for i in range(D):
                if i != r and M2[i][c] % Q:
                    f = M2[i][c]
                    M2[i] = [(M2[i][j] - f * M2[r][j]) % Q for j in range(D)]
            r += 1
        return r

    reps = sorted({min(A, mul(mI, A)) for A, L in dist.items()
                   if L == 3 and rk(A) == 2})
    NA = len(reps)
    adjm = [[0] * NA for _ in range(NA)]
    for i, j in itertools.combinations(range(NA), 2):
        if mul(reps[i], reps[j]) == mul(mI, mul(reps[j], reps[i])):
            adjm[i][j] = adjm[j][i] = 1
    cl = []

    def bk(R, P, X):
        if not P and not X:
            cl.append(frozenset(R))
            return
        for v in list(P):
            bk(R | {v}, {u for u in P if adjm[v][u]},
               {u for u in X if adjm[v][u]})
            P = P - {v}
            X = X | {v}

    bk(set(), set(range(NA)), set())
    LN = [frozenset(c) for c in cl if len(c) == 5]
    M = len(LN)
    Li = {l: i for i, l in enumerate(LN)}

    def nm(v):
        i = next(k for k, x in enumerate(v) if x % Q)
        z = pow(v[i] % Q, -1, Q)
        return tuple((z * x) % Q for x in v)

    pts = sorted({nm(v) for v in vecs})
    pidx = {p: i for i, p in enumerate(pts)}
    idx45 = {}
    for i, g in enumerate(reps):
        idx45[g] = i
        idx45[mul(mI, g)] = i

    proj = {}
    seenm, fr = {I}, [I]
    while fr:
        nx = []
        for A in fr:
            for t in T:
                B = mul(t, A)
                if B not in seenm:
                    seenm.add(B)
                    nx.append(B)
        fr = nx
    for A in seenm:
        a40 = tuple(pidx[nm(tuple(sum(A[i][k] * p[k] for k in range(D)) % Q
                                  for i in range(D)))] for p in pts)
        Ai = minv(A)
        c = tuple(idx45[mul(mul(A, reps[i]), Ai)] for i in range(NA))
        a27 = tuple(Li[frozenset(c[p] for p in LN[j])] for j in range(M))
        proj[(a40, a27)] = A

    coll = [[1 if (i != j and form(pts[i], pts[j]) % Q == 0) else 0
             for j in range(40)] for i in range(40)]
    p0 = 0
    opp = [j for j in range(40) if j != p0 and not coll[p0][j]]
    stab = [k for k in proj if k[0][p0] == p0]
    ID = (tuple(range(40)), tuple(range(M)))

    def comp(a, b):
        return (tuple(a[0][x] for x in b[0]), tuple(a[1][x] for x in b[1]))

    def gen(gs):
        G, f2 = {ID}, [ID]
        while f2:
            nx = []
            for a in f2:
                for g in gs:
                    c2 = comp(a, g)
                    if c2 not in G:
                        G.add(c2)
                        nx.append(c2)
            f2 = nx
        return G

    def ordof(k):
        o, cur = 1, k
        while cur != ID:
            cur = comp(k, cur)
            o += 1
        return o

    def orbs(acts, dom):
        dom = list(dom)
        sx, out = set(), []
        for x in dom:
            if x in sx:
                continue
            o, f2 = {x}, [x]
            while f2:
                n2 = []
                for y in f2:
                    for a in acts:
                        z = a[y]
                        if z not in o:
                            o.add(z)
                            n2.append(z)
                f2 = n2
            sx |= o
            out.append(len(o))
        return sorted(out)

    o_opp = orbs([k[0] for k in stab], opp)
    o_27 = orbs([k[1] for k in stab], range(M))

    three = [k for k in stab if ordof(k) == 3]
    rnd = random.Random(11)
    P = None
    for _ in range(4000):
        a, b = rnd.sample(three, 2)
        G = gen([a, b])
        if len(G) == 81:
            P = G
            break
    subs = set()
    Pl = [k for k in P if ordof(k) == 3]
    for a, b in itertools.combinations(Pl, 2):
        G = frozenset(gen([a, b]))
        if len(G) == 27:
            subs.add(G)

    def regular(acts, dom):
        if len(acts) != len(dom):
            return False
        x0 = dom[0]
        sx = set()
        for k in acts:
            y = k[x0]
            if y in sx:
                return False
            sx.add(y)
        return len(sx) == len(dom)

    found = None
    for G in subs:
        Gl = list(G)
        ex = max(ordof(k) for k in Gl)
        ab = all(comp(a, b) == comp(b, a) for a in Gl for b in Gl)
        r1 = regular([k[0] for k in Gl], opp)
        r2 = regular([k[1] for k in Gl], list(range(M)))
        if ex == 3 and not ab and r1 and r2:
            found = (G, ex, ab, r1, r2)
            break

    chi_ok = equi_ok = False
    if found:
        Gl = list(found[0])
        b1 = {k[0][opp[0]]: i for i, k in enumerate(Gl)}
        b2 = {k[1][0]: i for i, k in enumerate(Gl)}
        inv2 = {v: kk for kk, v in b2.items()}
        chi = {p: inv2[b1[p]] for p in opp}
        chi_ok = len(set(chi.values())) == M
        equi_ok = all(chi[k[0][p]] == k[1][chi[p]] for k in Gl for p in opp)

    print("MY 27 IS THEIR 27")
    print("=" * 72)
    print("  W(3,3) 40 points split 1 + %d + %d about p0"
          % (sum(coll[p0]), len(opp)))
    print("  Stab(p0) %d ; orbits on the 27 OPPOSITE points %s"
          % (len(stab), o_opp))
    print("             orbits on MY 27 GQ-LINES          %s" % o_27)
    print()
    print("  Sylow 3-subgroup of Stab(p0): order %d" % len(P))
    print("  order-27 subgroups found (from pairs of order-3 elements): %d"
          % len(subs))
    if found:
        print("     order 27, exponent %d, NONabelian" % found[1])
        print("     regular on the 27 opposite points   %s  [their result]"
              % found[3])
        print("     regular on MY 27 GQ-lines           %s  [new]" % found[4])
        print()
        print("  equivariant bijection chi: 27 opposite points -> 27 GQ-lines")
        print("     bijective                            %s" % chi_ok)
        print("     intertwines the whole elation group  %s" % equi_ok)
    print()
    print("  So the 27 lines of the cost quadrangle and the 27 of the cubic")
    print("  surface are ONE TORSOR. 8982d36's open item is closed.")
    print()
    print("  What now sits on a single 27: an order-27 exponent-3 QUTRIT Pauli")
    print("  group acting REGULARLY on it (their track), and order-32")
    print("  extraspecial 2^{1+4}_- QUBIT-shaped groups INDEXED by it, one per")
    print("  line, sharing the centre -I (34f2a84). A 3-group and 27 2-groups")
    print("  on one object -- a coincidence of counts before, a fact now.")

    ok = (len(stab) == 648 and o_opp == [27] and o_27 == [27] and len(opp) == 27
          and P is not None and len(P) == 81 and found is not None
          and chi_ok and equi_ok and NA == 45 and M == 27)

    if "--write" in sys.argv:
        p = os.path.join(ROOT, "data", "my_27_is_their_27.json")
        with open(p, "w") as fh:
            json.dump({
                "schema": "holotrade.my-27-is-their-27.v1",
                "valid": bool(ok),
                "whatWasOpen": ("8982d36 proved the 40 distinguished ovoids are "
                                "the 40 points of W(3,3) as PSp(4,3)-sets, then "
                                "said plainly that this does NOT establish that "
                                "the 27 appearing there is the same 27 as "
                                "THE_27_FOLD_WAY's, and that building it was the "
                                "next thing to do"),
                "theTwo27s": {
                    "theirs": ("W33-Theory Passes 368-371: fix p0, the 40 split "
                               "1+12+27, and the elation group -- order 27, "
                               "exponent 3, nonabelian, the "
                               "Kantor-Sahoo-Sastry Heisenberg group = the "
                               "single-qutrit Pauli group <X,Z,wI> -- acts "
                               "REGULARLY on the 27 opposite points"),
                    "mine": ("the 27 lines of GQ(4,2), the maximal "
                             "anticommuting sets of the 45 expensive "
                             "instructions (605f5e5)"),
                    "whyStabP0": ("only Stab(p0) preserves both, so that is "
                                  "where they must be compared"),
                },
                "stabiliser": {
                    "order": len(stab),
                    "orbitsOnOppositePoints": o_opp,
                    "orbitsOnMy27Lines": o_27,
                },
                "elationGroup": {
                    "sylow3Order": len(P),
                    "order27SubgroupsFound": len(subs),
                    "exponent": found[1] if found else None,
                    "nonabelian": (not found[2]) if found else None,
                    "regularOnOppositePoints": found[3] if found else None,
                    "regularOnMy27Lines": found[4] if found else None,
                },
                "equivariantBijection": {
                    "bijective": chi_ok,
                    "intertwinesElationGroup": equi_ok,
                    "reading": ("a group acting regularly on two sets makes them "
                                "isomorphic as G-sets, and here the bijection is "
                                "explicit rather than abstract"),
                },
                "whatSitsOnOne27": ("their side: an order-27 exponent-3 group "
                                    "acting REGULARLY on it, the single-qutrit "
                                    "Pauli group, a 3-GROUP. This side: order-32 "
                                    "extraspecial 2^{1+4}_- groups INDEXED by "
                                    "it, one per line, sharing the centre -I, "
                                    "2-GROUPS (34f2a84). One 27 carrying a "
                                    "qutrit Pauli torsor and indexing 27 "
                                    "qubit-shaped Pauli groups -- a coincidence "
                                    "of counts when first noticed, now a "
                                    "statement about one object"),
                "limitOnTheSearch": ("THE_27_FOLD_WAY reports the order-27 "
                                     "subgroups of a Sylow 3-subgroup are "
                                     "exactly four Frattini-hyperplane "
                                     "preimages, the elementary abelian one "
                                     "failing to be regular. The enumeration "
                                     "here looked only at subgroups generated by "
                                     "TWO elements of order 3 and found exactly "
                                     "one, the exponent-3 extraspecial -- the "
                                     "one the result needs. The others are "
                                     "presumably the exponent-9 cases, which two "
                                     "order-3 elements will not generate, but "
                                     "all four were NOT enumerated here: this "
                                     "reproduces their regularity result for one "
                                     "subgroup, it does not re-derive their "
                                     "classification"),
                "boundary": ("PSp(4,3) built out to all 25,920 distinct actions, "
                             "Stab(p0) as the full 648, transitivity by orbit "
                             "computation, regularity by checking the action is "
                             "free and transitive, and chi verified against every "
                             "element of the elation group. CITED not derived: "
                             "the identification of the elation group with the "
                             "single-qutrit Pauli group, the 1+12+27 split, and "
                             "the classification of order-27 subgroups, all from "
                             "W33-Theory Passes 368-371. This closes the 27 "
                             "question ONLY -- whether the 36 here are BT810's "
                             "spreads is still by invariants. tau_2 is "
                             "untouched"),
            }, fh, indent=2)
        print("\n  written: %s" % os.path.relpath(p, ROOT))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
