#!/usr/bin/env python3
"""
The transpose is a symmetry the corpus named and never searched. Searching it
is the FOURTH null on 114 -- and it does establish two things about 115.

WHY THIS SYMMETRY.  tensor_symmetric_blocker.py records the stabiliser of the
depth-2 problem as Aut(W33) wr C2, of order 51840^2 * 2, and then searches only
inside cyclic subgroups acting by the twisted diagonal (p,q) -> (g(p), h(q))
with h a power of g. The "wr C2" is the TRANSPOSE, (p,q) -> (q,p), and it is a
genuine symmetry of the constraint set: S meets every tile L x M if and only if
S^T does. It was named in that file and never used. This uses it.

WHAT WAS RUN.  For each cycle type of g in Aut(W(3,3)) acting on the 40 points
-- keyed by CYCLE TYPE, as tensor_symmetric_blocker.py warns, not by element
order -- the group

        < (g,g) , swap >

acts on the 1600 cells; a blocker invariant under it needs one Boolean per
ORBIT. Classes with more than 420 orbits are skipped as too large to decide,
which drops the identity (820 orbits, i.e. the pure transpose) and one other.
Every class is run at 115 FIRST, because 115 is achievable and a class that
cannot reach it cannot contain the optimum either, so its verdict at 114 is
void.

THE RESULT AT 114 IS NULL, and that is the fourth lever to come back null after
the clock, the group and the encoding. In both classes whose control resolves
SAT, 114 returns UNKNOWN at 600 s.

WHAT IT DOES ESTABLISH, and neither fact was in the corpus:

  1. A TRANSPOSE-SYMMETRIC BLOCKER OF SIZE 115 EXISTS. Two classes return
     OPTIMAL at 115. The corpus's 115 was found inside < (g,h) > with no swap,
     so this says the known optimum is compatible with the FULL stabiliser
     including the wreathing C2 -- it is not an artifact of breaking that
     symmetry.

  2. FIVE CLASSES CANNOT HOST A 115 AT ALL, proved INFEASIBLE rather than timed
     out. Since tau_2 <= 115, those symmetry classes provably exclude every
     optimal blocker. That is a structural statement about which symmetries a
     near-optimal blocker can carry, and it is why their 114 verdicts are
     reported as void rather than as evidence.

HOW TO READ A VOID ROW.  A class with 115 INFEASIBLE and 114 INFEASIBLE has NOT
shown anything about tau_2. It has shown that the class is too restrictive to
contain a blocker of either size. Reporting those two INFEASIBLEs as if they
narrowed tau_2 would be the mistake this file exists to avoid; the control is
what separates a measurement from a coincidence.

SCOPE.  Exact within each symmetry class: OPTIMAL and INFEASIBLE are proofs
about invariant blockers, UNKNOWN is a statement about the solver. Nothing here
constrains tau_2 itself, which stays open in [111, 115]. The pure transpose
(820 orbits) and the 436-orbit class are not decided; the pure transpose was run
separately at 115, 114 and 113 and returned UNKNOWN at every size, so it is
recorded as void too.
"""

import argparse
import itertools
import json
import os
import time

Q = 3
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def geometry():
    def nm(v):
        i = next(k for k, x in enumerate(v) if x % Q)
        z = pow(v[i] % Q, -1, Q)
        return tuple((z * x) % Q for x in v)

    pts = sorted({nm(v) for v in itertools.product(range(Q), repeat=4)
                  if any(v)})
    idx = {p: i for i, p in enumerate(pts)}

    def sf(u, v):
        return (u[0] * v[1] - u[1] * v[0] + u[2] * v[3] - u[3] * v[2]) % Q

    lines = set()
    for a, b in itertools.combinations(range(40), 2):
        if sf(pts[a], pts[b]):
            continue
        S = set()
        for x in range(Q):
            for y in range(Q):
                if x or y:
                    S.add(idx[nm(tuple((x * pts[a][k] + y * pts[b][k]) % Q
                                       for k in range(4)))])
        if len(S) == 4:
            lines.add(tuple(sorted(S)))
    return pts, idx, sf, sorted(lines)


def automorphisms(pts, idx, sf):
    """Aut(W(3,3)) on the 40 points, generated by symplectic transvections."""
    def nm(v):
        i = next(k for k, x in enumerate(v) if x % Q)
        z = pow(v[i] % Q, -1, Q)
        return tuple((z * x) % Q for x in v)

    def tv(v):
        out = []
        for p in range(40):
            t = sf(pts[p], v)
            out.append(idx[nm(tuple((pts[p][k] + t * v[k]) % Q
                                    for k in range(4)))])
        return tuple(out)

    ident = tuple(range(40))
    gens = [g for g in (tv(v) for v in pts) if g != ident]
    G, frontier = {ident}, [ident]
    while frontier:
        nf = []
        for a in frontier:
            for g in gens:
                b = tuple(g[a[i]] for i in range(40))
                if b not in G:
                    G.add(b)
                    nf.append(b)
        frontier = nf
    return sorted(G)


def cycle_type(g):
    seen, c = set(), []
    for i in range(40):
        if i in seen:
            continue
        l, j = 0, i
        while j not in seen:
            seen.add(j)
            j = g[j]
            l += 1
        c.append(l)
    return tuple(sorted(c, reverse=True))


def orbits_of(g):
    seen = [False] * 1600
    orbs = []
    for c in range(1600):
        if seen[c]:
            continue
        o, stack = set(), [c]
        while stack:
            u = stack.pop()
            if u in o:
                continue
            o.add(u)
            seen[u] = True
            p, q = divmod(u, 40)
            stack.append(g[p] * 40 + g[q])
            stack.append(q * 40 + p)
        orbs.append(sorted(o))
    return orbs


def solve(lines, orbs, N, budget):
    from ortools.sat.python import cp_model
    m = cp_model.CpModel()
    b = [m.NewBoolVar("b%d" % i) for i in range(len(orbs))]
    inorb = [0] * 1600
    for i, o in enumerate(orbs):
        for c in o:
            inorb[c] = i
    for L in lines:
        for M in lines:
            m.AddBoolOr([b[i] for i in {inorb[p * 40 + q]
                                        for p in L for q in M}])
    m.Add(sum(len(orbs[i]) * b[i] for i in range(len(orbs))) == N)
    sv = cp_model.CpSolver()
    sv.parameters.num_workers = 8
    sv.parameters.max_time_in_seconds = budget
    t0 = time.time()
    st = sv.Solve(m)
    return sv.StatusName(st), time.time() - t0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--max-orbits", type=int, default=420)
    ap.add_argument("--control-budget", type=float, default=120.0)
    ap.add_argument("--target-budget", type=float, default=600.0)
    args = ap.parse_args()

    pts, idx, sf, lines = geometry()
    G = automorphisms(pts, idx, sf)
    byt = {}
    for g in G:
        byt.setdefault(cycle_type(g), g)

    print("THE TRANSPOSE CLASS: < (g,g), swap >")
    print("=" * 74)
    print("  |Aut on points| = %d, cycle types = %d" % (len(G), len(byt)))
    print("  control at 115 FIRST -- a class that cannot reach 115 cannot")
    print("  contain the optimum, so its 114 verdict is VOID.")
    print()
    rows = []
    for ct, g in sorted(byt.items(), key=lambda kv: -len(kv[0])):
        orbs = orbits_of(g)
        if len(orbs) > args.max_orbits:
            rows.append({"cycleType": list(ct), "orbits": len(orbs),
                         "skipped": True})
            print("  orbits=%4d  ct=%-34s  SKIPPED (too large to decide)"
                  % (len(orbs), str(ct)[:34]))
            continue
        s115, _ = solve(lines, orbs, 115, args.control_budget)
        if s115 == "UNKNOWN":
            rows.append({"cycleType": list(ct), "orbits": len(orbs),
                         "at115": s115, "at114": None, "informative": False})
            print("  orbits=%4d  ct=%-34s  115=UNKNOWN -> VOID"
                  % (len(orbs), str(ct)[:34]))
            continue
        s114, _ = solve(lines, orbs, 114, args.target_budget)
        informative = (s115 in ("OPTIMAL", "FEASIBLE"))
        rows.append({"cycleType": list(ct), "orbits": len(orbs),
                     "at115": s115, "at114": s114,
                     "informative": informative})
        print("  orbits=%4d  ct=%-34s  115=%-11s 114=%-11s %s"
              % (len(orbs), str(ct)[:34], s115, s114,
                 "" if informative else "-> VOID (no 115 in class)"))

    hosts = [r for r in rows if r.get("at115") in ("OPTIMAL", "FEASIBLE")]
    excl = [r for r in rows if r.get("at115") == "INFEASIBLE"]
    decided114 = [r for r in hosts if r.get("at114") in ("OPTIMAL", "FEASIBLE")]

    print()
    print("  classes hosting a 115: %d   classes provably excluding 115: %d"
          % (len(hosts), len(excl)))
    print("  114 found in an informative class: %s"
          % ("YES" if decided114 else "NO -- fourth lever null"))

    ok = len(hosts) >= 1 and len(excl) >= 1
    print()
    print("VALID: %s" % ok)

    if args.write:
        assert ok, "checks failed -- refusing to write"
        rec = {
            "schema": "holotrade.transpose-class-115-not-114.v1",
            "valid": True,
            "autOrderOnPoints": len(G),
            "cycleTypes": len(byt),
            "rows": rows,
            "classesHosting115": len(hosts),
            "classesProvablyExcluding115": len(excl),
            "found114": bool(decided114),
            "whySymmetry": (
                "tensor_symmetric_blocker.py records the stabiliser of the "
                "depth-2 problem as Aut(W33) wr C2 and then searches only inside "
                "cyclic subgroups acting by the twisted diagonal (p,q) -> "
                "(g(p), h(q)) with h a power of g. The 'wr C2' is the TRANSPOSE, "
                "and it is a genuine symmetry of the constraint set since S meets "
                "every tile L x M exactly when S^T does. That file named it and "
                "never used it; this file uses it."),
            "theNullAt114": (
                "in both classes whose control resolves SAT, 114 returns UNKNOWN "
                "at 600 s. That is the FOURTH lever to come back null on 114, "
                "after the clock (36d3b4b), the group (cf9ecf7) and the encoding "
                "(e3ffec2)."),
            "whatItEstablishes": (
                "first, a TRANSPOSE-SYMMETRIC BLOCKER OF SIZE 115 EXISTS -- two "
                "classes return OPTIMAL at 115. The corpus's 115 was found inside "
                "<(g,h)> with no swap, so the known optimum is compatible with the "
                "FULL stabiliser including the wreathing C2 and is not an artifact "
                "of breaking that symmetry. Second, FIVE CLASSES CANNOT HOST A 115 "
                "AT ALL, proved INFEASIBLE rather than timed out; since tau_2 <= "
                "115 those symmetry classes provably exclude every optimal "
                "blocker, which is a structural statement about which symmetries a "
                "near-optimal blocker can carry."),
            "howToReadAVoidRow": (
                "a class with 115 INFEASIBLE and 114 INFEASIBLE has shown nothing "
                "about tau_2 -- only that the class is too restrictive to contain "
                "a blocker of either size. Reporting those two INFEASIBLEs as if "
                "they narrowed tau_2 would be the mistake this file exists to "
                "avoid. The control is what separates a measurement from a "
                "coincidence."),
            "pureTransposeIsVoidToo": (
                "the pure transpose -- g = identity, 820 orbits -- exceeds the "
                "orbit cap and is skipped here, but was run separately as a direct "
                "820-variable model at 115, 114 and 113 and returned UNKNOWN at "
                "every size. Fewer variables did not help because the constraints "
                "get denser, so it is void as well."),
            "boundary": (
                "exact WITHIN each symmetry class: OPTIMAL and INFEASIBLE are "
                "proofs about invariant blockers, UNKNOWN is a statement about the "
                "solver and not about the class. Nothing here constrains tau_2 "
                "itself, which stays open in [111, 115]. Classes are keyed by "
                "CYCLE TYPE rather than element order, as tensor_symmetric_blocker "
                ".py warns; classes above the orbit cap are recorded as skipped "
                "rather than silently dropped."),
        }
        p = os.path.join(ROOT, "data", "transpose_class_115_not_114.json")
        with open(p, "w", encoding="utf-8") as fh:
            json.dump(rec, fh, indent=2)
        print("written: %s" % p)


if __name__ == "__main__":
    main()
