#!/usr/bin/env python3
"""
THE CENTRE OF THE A8^3 PAULI GROUP 3^(1+12) IS THE REVERSE ORBIFOLD BACK TO E8^3:
E8^3 -> A8^3 IS THE EXACT LATTICE ANALOGUE OF LEECH -> MOONSHINE.

4104251 showed the three two-qutrit Pauli groups act on the Niemeier A8^3 lattice VOA
as ONE extraspecial group 3^(1+12), whose centre acts on the glue sector c by
omega^(c_1 mod 3). This file identifies that centre.

ORBIFOLD DUALITY. A Z_n orbifold V -> V~ carries a dual Z_n acting on the i-th twisted
sector by zeta^i, and orbifolding V~ by it returns V. In 68df33f the diagonal W(3,3)
twist of E8^3 (twisted weight 4/9 per factor, 4/3 in total) orbifolds V_{E8^3} to the
Niemeier A8^3 theory. The claim checked here: the centre of the Pauli 3^(1+12) IS that
dual Z_3, i.e. orbifolding V_{A8^3} by it gives back V_{E8^3}.

THE COMPUTATION IS EXACT, AT THE LEVEL OF GLUE CODES. For A8, A8*/A8 = Z_9 with
    q(k) = k(9-k)/18  (half-norm mod 1),     b(j,k) = -jk/9  (mod 1).
The Niemeier lattice N(A8^3) is the glue code C < Z_9^3 generated by the permutations
of (1,1,4): 27 words, self-dual and even. A central element acting on sector c by
omega^(c_1) is the lattice shift by a class u with b(u,c) = c_1/3 mod 1; u = (6,0,0)
works, since -6 c_1/9 = c_1/3 mod 1. For such a shift the orbifold is again a lattice
theory:
    L_0 = { c in C : b(u,c) in Z }      (the invariant sectors),
    N'  = L_0 + <u>                      (add the twisted coset),
and N' is even unimodular whenever u has order 3 and q(u) is integral (q(6) = 1).
Norm-2 vectors of a glued lattice come only from the A8 roots (216) and from words
with a single nonzero entry of class 3 or 6 (84 minimal vectors each; any word with
two nonzero entries has norm at least 16/9 + 8/9 > 2, so it contributes none).

RESULT. N' contains all six words (3,0,0), (6,0,0), (0,3,0), (0,6,0), (0,0,3), (0,0,6), so
it has 216 + 6*84 = 720 roots and each A8 is completed to an E8 (72 + 84 + 84 = 240).
The Niemeier lattice with root system E8^3 is unique, so N' = E8^3.

WHY THIS MATTERS. The two Z_3 orbifolds with the six-qutrit register are now exactly
parallel:
    V_Leech --(fixed-point-free Z_3)--> V^natural,  3^(1+12).2Suz.2,  centre 3B returns Leech
    V_E8^3  --(diagonal W(3,3) twist)--> V_A8^3,    3^(1+12) (Pauli), centre returns E8^3
Both have twisted weight 4/3, 729 ground states and commutator geometry W(11,3). They
differ in the normaliser (2.Suz against the W(3,3) Clifford structure) and in V_1:
abelian for Leech, sl9^3 for A8^3.

The Chen-Lam-Shimakura realisation (arXiv:1606.05961) shows the Leech side produces
the Monster 3-locals 3^(1+12).2Suz.2. This file shows the E8^3 side produces the same
extraspecial core, built from W(3,3) Pauli groups.

LITERATURE CHECKS MADE FOR THIS FILE.
  - Sagaki-Shimakura (arXiv:1402.0143, Claim 2 of section 3.4) EXCLUDE A8^3 from
    Miyamoto's Z_3 orbifold: the factor-permuting order-3 automorphism has fixed
    rank 8, not a multiple of 6. This independently confirms that the cyclic route
    from A8^3 is closed, consistent with 6a881ef5c and 4104251.
  - A search summary attributed to Hoehn-Scheithauer ("the Z2-twist of V_K where K is
    the Niemeier lattice with root lattice ...") refers to A_3^8, not A_8^3. It does not
    concern this lattice; that was checked against the source.

SCOPE. Exact glue-code computation plus standard orbifold duality. It identifies the
centre of the Pauli 3^(1+12) as the reverse-orbifold Z_3. It does not construct the full
non-cyclic 3^(1+12) orbifold and makes no claim that it yields V^natural.
"""

import argparse
import itertools
import json
import os
from fractions import Fraction as Fr

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def q(k):
    k %= 9
    return Fr(k * (9 - k), 18)


def b(j, k):
    return Fr(-(j % 9) * (k % 9), 9)


def Q(c):
    return sum((q(k) for k in c), Fr(0))


def B(c, d):
    return sum((b(x, y) for x, y in zip(c, d)), Fr(0))


def integral(x):
    return x.denominator == 1


def span(gens):
    words = {(0, 0, 0)}
    frontier = [(0, 0, 0)]
    while frontier:
        nxt = []
        for w in frontier:
            for g in gens:
                z = tuple((a + c) % 9 for a, c in zip(w, g))
                if z not in words:
                    words.add(z)
                    nxt.append(z)
        frontier = nxt
    return sorted(words)


def norm(c):
    return 2 * Q(c)                                        # minimal norm in the coset, mod 2Z


def min_norm(c):
    """exact minimal norm of an A8^3 coset: sum over factors of k(9-k)/9."""
    return sum((Fr((k % 9) * (9 - k % 9), 9) for k in c), Fr(0))


def roots(code):
    single = [c for c in code if sum(1 for k in c if k) == 1 and min_norm(c) == 2]
    for c in code:                                         # no other word may reach norm 2
        if sum(1 for k in c if k) >= 2:
            assert min_norm(c) > 2, c
    return 216 + 84 * len(single), sorted(single)


def self_dual_even(code):
    return (len(code) == 27 and all(integral(B(c, d)) for c in code for d in code)
            and all(integral(Q(c)) for c in code))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    checks = {}
    C = span([(1, 1, 4), (1, 4, 1), (4, 1, 1)])
    r_N, single_N = roots(C)
    print("  N(A8^3): %d glue words, self-dual & even: %s, roots %d" % (len(C), self_dual_even(C), r_N))
    checks["A8_cubed_glue_is_niemeier"] = self_dual_even(C) and r_N == 216

    # the centre of the Pauli 3^(1+12): acts on sector c by omega^(c_1 mod 3)
    candidates = [u for u in itertools.product(range(9), repeat=3)
                  if all((B(u, c) - Fr(c[0] % 3, 3)).denominator == 1 for c in C)]
    u = (6, 0, 0)
    assert u in candidates
    print("  shift classes u realising the Pauli centre (b(u,c) = c_1/3): %d, e.g. %s" % (len(candidates), u))
    checks["u_has_order_3_and_integral_q"] = all(3 * x % 9 == 0 for x in u) and integral(Q(u))

    L0 = [c for c in C if integral(B(u, c))]
    Np = span(L0 + [u])
    r_Np, single_Np = roots(Np)
    print("  invariant sectors L_0: %d words;  N' = L_0 + <u>: %d words, self-dual & even: %s" % (
        len(L0), len(Np), self_dual_even(Np)))
    print("  single-entry class-3/6 words in N': %s" % single_Np)
    print("  roots of N': %d  (E8^3 has 720)" % r_Np)
    checks["invariant_part_has_index_3"] = len(L0) == 9
    checks["orbifold_lattice_is_even_unimodular"] = self_dual_even(Np)
    checks["orbifold_lattice_has_720_roots"] = r_Np == 720
    checks["each_A8_completes_to_E8"] = sorted(single_Np) == sorted(
        [(3, 0, 0), (6, 0, 0), (0, 3, 0), (0, 6, 0), (0, 0, 3), (0, 0, 6)])
    # Every class in u + C induces the same automorphism, but the lattice L_0 + <v> is only the orbifold
    # for representatives of order 3 with integral q; each of those must again give E8^3.
    valid_reps = [v for v in candidates if any(v) and all(3 * x % 9 == 0 for x in v) and integral(Q(v))]
    outcomes = set()
    for v in valid_reps:
        Nv = span([c for c in C if integral(B(v, c))] + [v])
        outcomes.add((self_dual_even(Nv), roots(Nv)[0]))
    print("  order-3 representatives of the centre with integral q: %d, orbifold outcomes (even unimodular, roots): %s" % (
        len(valid_reps), sorted(outcomes)))
    checks["every_valid_representative_gives_E8_cubed"] = len(valid_reps) > 0 and outcomes == {(True, 720)}
    # teeth: a shift that is NOT the Pauli centre (order 9, u=(1,0,0)) is not a Z_3 action on the sectors
    teeth = [c for c in C if not integral(3 * B((1, 0, 0), c))]
    checks["teeth_order_nine_shift_is_not_the_centre"] = len(teeth) > 0

    for k, v in checks.items():
        print("  %-44s %s" % (k, v))
    valid = all(checks.values())
    print("VALID:", valid)
    if args.write:
        payload = {
            "claim": "The centre of the Pauli 3^(1+12) acting on the Niemeier A8^3 lattice VOA is the dual Z_3 of the E8^3 -> A8^3 "
                     "orbifold of 68df33f: the shift orbifold of N(A8^3) by u = (6,0,0) has 27 glue words, is even unimodular, "
                     "and has 216 + 6*84 = 720 roots, each A8 completing to E8, so it is E8^3. Hence E8^3 -> A8^3 is the exact "
                     "lattice analogue of Leech -> Moonshine, with the same extraspecial 3^(1+12) core.",
            "glue": {"A8cubed_words": len(C), "invariant_words": len(L0), "orbifold_words": len(Np),
                     "orbifold_single_entry_words": [list(x) for x in single_Np]},
            "roots": {"A8cubed": r_N, "orbifold": r_Np},
            "centreShift": list(u), "centreRealisations": len(candidates),
            "parallel": {"Leech_to_Moonshine": "3^(1+12).2Suz.2, centre 3B, reverse orbifold returns V_Leech",
                         "E8cubed_to_A8cubed": "3^(1+12) Pauli, centre = glue grading omega^(c_1), reverse orbifold returns V_E8^3"},
            "literature": {"Sagaki-Shimakura arXiv:1402.0143": "A8^3 excluded from Miyamoto Z3 orbifold (fixed rank 8 not in 6Z)",
                           "Hoehn-Scheithauer (rank-14 GKM)": "their Z2-twist refers to root lattice A_3^8, not A_8^3",
                           "Chen-Lam-Shimakura arXiv:1606.05961": "Leech Z3 orbifold is Moonshine; 3^(1+12).2Suz.2 3-locals"},
            "checks": checks, "valid": valid,
            "status": "exact glue-code computation with standard orbifold duality; no claim about the full non-cyclic orbifold",
            "sources": ["Holotrade 68df33f", "Holotrade 4104251", "TOE 6a881ef5c", "TOE 865e04b18"]}
        with open(os.path.join(ROOT, "data", "w33_pauli_centre_reverse_orbifold.json"), "w") as f:
            json.dump(payload, f, indent=1)
        print("written")


if __name__ == "__main__":
    main()
