#!/usr/bin/env python3
"""
THE THREE TWO-QUTRIT PAULI GROUPS OF THE A8^3 NIEMEIER THEORY ARE ONE EXTRASPECIAL
GROUP 3^(1+12), AND IT IS THE ONLY KIND OF SYMMETRY THAT CAN EMPTY V_1.

Joins three results from the other track with 68df33f:
  865e04b18  w33_a8cubed_monster_s3_twining          (factor 3-cycle twining = T_3C)
  6a881ef5c  w33_a8cubed_monster_orbifold_surgery... (factor-cycle orbifold is not Moonshine)
  54482d426  the E8 A8 fixed algebra carries the two-qutrit Pauli fine grading
  196cc86dc  three orthogonal W(3,3)s sit inside the Leech / 2.Suz tight shell

1. THE CYCLIC OBSTRUCTION IS UNIVERSAL. V_1 of the Niemeier A8^3 lattice theory is
   sl9^3 (the glue sectors have weights 0, 2, 3, so none reaches weight one). By
   Kreknin's theorem (after Borel-Mostow and Jacobson), a Lie algebra admitting a
   fixed-point-free automorphism of finite order is solvable. A semisimple algebra
   therefore has nonzero fixed points under EVERY finite-order automorphism. Those
   fixed currents survive in every cyclic orbifold, while V^natural_1 = 0. So no
   cyclic orbifold of V_{A8^3} is Moonshine, not just the naive factor cycle of
   6a881ef5c. The same argument excludes every Niemeier lattice with roots; only
   Leech, whose V_1 is abelian, escapes - and it does (Chen-Lam-Shimakura).
   Checked here on the Pauli group itself: EVERY nonidentity element fixes a
   26-dimensional subalgebra of sl9.

2. THE ESCAPE ROUTE IS NON-CYCLIC. The two-qutrit Pauli group acts on sl9 with ZERO
   fixed points: its commutant in gl9 is the scalars, because the Heisenberg
   representation is irreducible. That is the fine grading of 54482d426 with no
   degree-zero component. So the full Pauli group on each factor empties V_1, and
   no cyclic subgroup of it does.

3. THE THREE GROUPS DO NOT ACT INDEPENDENTLY. Pass 2026-09-15 (Pauli stack, section 4)
   notes that the A8^3 glue "does not identify the three F3^4 adjoint Pauli labels",
   which is correct for the labels, since adjoint currents carry centre charge zero.
   As AUTOMORPHISMS of V_{A8^3}, though, the Pauli group elements also act on the glue
   sectors, where the centre of SU(9) is visible. On the sector of 9-ality k, the
   central element omega*I = zeta_9^3*I acts by omega^k. The A8^3 glue code,
   generated by the permutations of (1,1,4), reduces mod 3 to the DIAGONAL line
   <(1,1,1)>, because 4 = 1 mod 3. So the three factor centres act identically on
   every sector, and exactly a Z_3 of the Z_3^3 of centres survives. The group the
   three Pauli groups generate is the CENTRAL product
       3^(1+4) o 3^(1+4) o 3^(1+4) = 3^(1+12),
   extraspecial of order 3^13, with commutator form Omega + Omega + Omega on F3^12:
   the orthogonal sum of three W(3,3) forms.

4. WHAT THAT GROUP IS. 3^(1+12) is O_3 of the Monster's 3B normaliser
   3^(1+12).2Suz.2, and an orthogonal three-W(3,3) decomposition of F3^12 is exactly
   the structure 196cc86dc finds inside the Leech / 2.Suz tight shell. It also
   matches McKay's E8 observation: the A8 Kac class of the W(3,3) twist is the
   removal of the mark-3 BRANCH node of affine E8 (68df33f), and McKay's labelling
   places the Monster class 3C at that node (Glauberman-Norton; Lam-Yamada-Yamauchi),
   whose twining the other track found to be T_3C.

SCOPE. Items 1-3 are proved and verified here. Item 4 is structural identification,
not a construction: this file does NOT build the 3^(1+12) orbifold, does not check its
anomaly, and does not compute its twisted sectors, whose weight-one states could
repopulate V_1. What it establishes is that a non-cyclic 3^(1+12) of exactly the
Monster's shape is the only kind of symmetry of V_{A8^3} that can empty V_1. If its
orbifold exists, is holomorphic and has V_1 = 0, the Frenkel-Lepowsky-Meurman
uniqueness conjecture would identify it with V^natural. That is the precise open
problem this file isolates.
"""

import argparse
import importlib.util
import itertools
import json
import os

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W = np.exp(2j * np.pi / 3)
TOL = 1e-9


def key(M):
    return tuple(np.round(M.real, 6).ravel()) + tuple(np.round(M.imag, 6).ravel())


def qutrit():
    X = np.zeros((3, 3), dtype=complex)
    for j in range(3):
        X[(j + 1) % 3, j] = 1
    Z = np.diag([1, W, W * W])
    return X, Z


def fixed_dim(mats):
    """dimension of {M in gl9 : g M g^-1 = M for all g in mats}."""
    rows = [np.kron(g, np.linalg.inv(g).T) - np.eye(g.shape[0] ** 2) for g in mats]
    A = np.vstack(rows)
    s = np.linalg.svd(A, compute_uv=False)
    return int(np.sum(s < 1e-8)) + max(0, A.shape[1] - len(s))


def f3_rank(M):
    A = np.array(M, dtype=np.int64) % 3
    r = 0
    for c in range(A.shape[1]):
        p = next((i for i in range(r, A.shape[0]) if A[i, c]), None)
        if p is None:
            continue
        A[[r, p]] = A[[p, r]]
        A[r] = A[r] * pow(int(A[r, c]), -1, 3) % 3
        for i in range(A.shape[0]):
            if i != r and A[i, c]:
                A[i] = (A[i] - A[i, c] * A[r]) % 3
        r += 1
    return r


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    checks, out = {}, {}
    X, Z = qutrit()
    I3 = np.eye(3)
    gens = {"X1": np.kron(X, I3), "Z1": np.kron(Z, I3), "X2": np.kron(I3, X), "Z2": np.kron(I3, Z)}
    G = list(gens.values())

    # the two-qutrit Pauli group inside SL9
    checks["generators_in_SL9"] = all(abs(np.linalg.det(g) - 1) < TOL for g in G)
    seen = {key(np.eye(9, dtype=complex)): np.eye(9, dtype=complex)}
    frontier = [np.eye(9, dtype=complex)]
    while frontier:
        nxt = []
        for M in frontier:
            for g in G:
                P = g @ M
                k = key(P)
                if k not in seen:
                    seen[k] = P
                    nxt.append(P)
        frontier = nxt
    group = list(seen.values())
    centre = [P for P in group if np.allclose(P, P[0, 0] * np.eye(9), atol=TOL)]
    print("  two-qutrit Pauli group in SL9: order %d, centre order %d" % (len(group), len(centre)))
    checks["pauli_group_order_3_5"] = len(group) == 243 and len(centre) == 3

    # commutators: omega on (X_a, Z_a), trivial across qutrits
    def comm(a, b):
        return a @ b @ np.linalg.inv(a) @ np.linalg.inv(b)
    names = list(gens)
    cm = {}
    for a, b in itertools.product(names, repeat=2):
        C = comm(gens[a], gens[b])
        lam = C[0, 0]
        assert np.allclose(C, lam * np.eye(9), atol=TOL)
        e = int(round(np.angle(lam) / (2 * np.pi / 3))) % 3
        cm[(a, b)] = e
    Omega = np.array([[cm[(a, b)] for b in names] for a in names], dtype=np.int64)
    print("  single-factor commutator exponents (order X1 Z1 X2 Z2):", Omega.tolist())
    checks["single_factor_form_is_W33_symplectic"] = f3_rank(Omega) == 4 and \
        np.array_equal((Omega + Omega.T) % 3, np.zeros((4, 4), dtype=np.int64)) and all(Omega[i, i] == 0 for i in range(4))

    # 1 and 2: fixed points on gl9 / sl9
    full = fixed_dim(G)                                    # commutant of the whole group
    cyc = sorted({fixed_dim([P]) for P in group if not np.allclose(P, P[0, 0] * np.eye(9), atol=TOL)})
    print("  fixed subspace in gl9 of the full Pauli group: %d  -> in sl9: %d" % (full, full - 1))
    print("  fixed subspace in gl9 of each nonscalar element: %s -> in sl9: %s" % (cyc, [c - 1 for c in cyc]))
    checks["full_pauli_group_fixes_nothing_in_sl9"] = full == 1
    checks["every_cyclic_subgroup_fixes_26_dims"] = cyc == [27]

    # 3. the glue code and the centre action
    gen = [(1, 1, 4), (1, 4, 1), (4, 1, 1)]
    C = sorted({tuple((a * gen[0][i] + b * gen[1][i] + c * gen[2][i]) % 9 for i in range(3))
                for a, b, c in itertools.product(range(9), repeat=3)})
    mod3 = sorted({tuple(x % 3 for x in w) for w in C})
    h = lambda k: k * (9 - k) / 18
    weights = sorted({round(sum(h(k) for k in w), 9) for w in C})
    print("  A8^3 glue: %d sectors, weights %s, reduced mod 3: %s" % (len(C), weights, mod3))
    checks["glue_order_27"] = len(C) == 27
    checks["no_weight_one_glue_so_V1_is_sl9_cubed"] = 1.0 not in weights
    checks["glue_mod_3_is_diagonal"] = mod3 == [(0, 0, 0), (1, 1, 1), (2, 2, 2)]
    # centre element (omega^a1, omega^a2, omega^a3) acts on sector c by omega^(a . c)
    kernel = [a for a in itertools.product(range(3), repeat=3)
              if all(sum(ai * ci for ai, ci in zip(a, c)) % 9 % 3 == 0 for c in C)]
    print("  centre elements acting trivially on every sector: %d of 27 (effective centre order %d)" % (len(kernel), 27 // len(kernel)))
    checks["three_centres_identified_to_one_Z3"] = len(kernel) == 9 and all(sum(a) % 3 == 0 for a in kernel)

    # the effective commutator form on F3^12
    Big = np.zeros((12, 12), dtype=np.int64)
    for f in range(3):
        Big[4 * f:4 * f + 4, 4 * f:4 * f + 4] = Omega
    rank12 = f3_rank(Big)
    print("  effective commutator form on F3^12: rank %d (Omega + Omega + Omega)" % rank12)
    checks["extraspecial_3_1_12"] = rank12 == 12
    out["groupOrder"] = "3^13 = 3^15 / 3^2 (central product)"

    # 4. McKay: the A8 class is the mark-3 branch node of affine E8
    spec = importlib.util.spec_from_file_location("tw", os.path.join(ROOT, "analysis", "the_twisted_sectors_carry_the_rung_geometries.py"))
    tw = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(tw)
    kac, cartan = tw.kac_order3_e8()
    marks = [1, 2, 3, 4, 5, 6, 4, 2, 3]
    eighty = [(s, z) for s, d, z in kac if d == 80]
    removed = [i for i in range(9) if i not in eighty[0][1]] if len(eighty) == 1 else []
    branch = 8                                             # the node attached to the mark-6 node, mark 3
    print("  order-3 Kac class with fixed dimension 80 removes affine-E8 node(s) %s, mark %s (the branch node is %d)" % (
        removed, [marks[i] for i in removed], branch))
    checks["A8_class_is_the_mark3_branch_node"] = removed == [branch] and marks[branch] == 3
    mckay = {"1A": 1, "2A": 2, "3A": 3, "4A": 4, "5A": 5, "6A": 6, "4B": 4, "2B": 2, "3C": 3}
    out["mckayLabels"] = {"chain": ["1A", "2A", "3A", "4A", "5A", "6A", "4B", "2B"], "branch_node": "3C",
                          "orders_equal_marks": [mckay[k] for k in ["1A", "2A", "3A", "4A", "5A", "6A", "4B", "2B", "3C"]] == marks}
    checks["mckay_orders_equal_affine_marks"] = out["mckayLabels"]["orders_equal_marks"]

    for k, v in checks.items():
        print("  %-44s %s" % (k, v))
    valid = all(checks.values())
    print("VALID:", valid)
    if args.write:
        payload = {
            "claim": "As automorphisms of the Niemeier A8^3 lattice VOA, the three two-qutrit Pauli groups generate ONE extraspecial "
                     "group 3^(1+12): the glue code reduces mod 3 to the diagonal <(1,1,1)>, so the three SU(9) centres act "
                     "identically on every sector and the product is central. Its commutator form is the orthogonal sum of three "
                     "W(3,3) forms. The group fixes nothing in V_1 = sl9^3, whereas every cyclic subgroup fixes 26 dimensions per "
                     "factor, and by Kreknin every finite-order automorphism of a semisimple V_1 has fixed points. So no cyclic "
                     "orbifold of V_{A8^3} is Moonshine, and a non-cyclic 3^(1+12) - the shape of O_3 of the Monster 3B "
                     "normaliser - is the only kind of symmetry that can empty V_1.",
            "pauli": {"order": len(group), "centre": len(centre), "singleFactorForm": Omega.tolist()},
            "fixedPoints": {"fullGroupInSl9": full - 1, "eachCyclicInSl9": [c - 1 for c in cyc]},
            "glue": {"sectors": len(C), "weights": weights, "mod3": [list(x) for x in mod3], "trivialCentreElements": len(kernel)},
            "extraspecial": {"commutatorFormRankF3": rank12, "shape": "3^(1+12)", "form": "Omega + Omega + Omega (three orthogonal W(3,3))"},
            "mckay": {"a8KacClassRemovesNode": removed, "mark": [marks[i] for i in removed], "mckayClassAtThatNode": "3C",
                      "otherTrackTwining": "865e04b18: factor 3-cycle twining = T_3C"},
            "openProblem": "Construct the 3^(1+12) orbifold of V_{A8^3}: its anomaly class, its twisted sectors and their weight-one "
                           "states. If it exists, is holomorphic and has V_1 = 0, the FLM uniqueness conjecture identifies it with "
                           "V^natural.",
            "checks": checks, "valid": valid,
            "status": "items 1-3 proved and verified; item 4 is a structural identification, not a construction",
            "sources": ["Holotrade 68df33f", "TOE 865e04b18", "TOE 6a881ef5c", "TOE 54482d426", "TOE 196cc86dc",
                        "Kreknin 1963; Borel-Mostow 1955; Jacobson", "McKay E8 observation; Glauberman-Norton; Lam-Yamada-Yamauchi 2007",
                        "Chen-Lam-Shimakura arXiv:1606.05961", "Frenkel-Lepowsky-Meurman uniqueness conjecture"]}
        with open(os.path.join(ROOT, "data", "w33_a8cubed_pauli_extraspecial.json"), "w") as f:
            json.dump(payload, f, indent=1)
        print("written")


if __name__ == "__main__":
    main()
