#!/usr/bin/env python3
"""
Settled, and negatively: the eighty Gauss-sum lifts are NOT a homomorphic
section. They generate Paulis. A section exists; this natural choice is not one.

WHAT WAS OPEN.  0fb6a0f tabulated the eighty lifts in closed form,
U(v,lam) = (1/sqrt 3) sum_k w^{lam k^2} P_v^k, verified each one against all
eighty Paulis, and flagged one thing as unsettled: whether these particular
eighty form a homomorphic section. The first attempt generated the group
numerically and blew up on floating-point hashing, so the number it produced
was disclosed as an artefact rather than quoted. This settles it exactly.

THE EXACT ENCODING.  A Clifford modulo global phase is determined by its action
on Paulis, U P_v U^dag = w^{phi(v)} P_{Sv}, and composition is

    (S1, phi1) . (S2, phi2)  =  (S1 S2,  phi2 + phi1 o S2)

which is pure arithmetic in F_3 with no unitaries and no rounding. The phases
themselves are read off once, and they are cube roots of unity to 2.6e-15, so
that step is safe; everything after it is integer.

phi IS NOT LINEAR.  Zero out of eighty lifts have a linear phase function.
The cocycle identity phi(u+v) = phi(u) + phi(v) + c(Su,Sv) - c(u,v) says
linearity would need S to preserve the Pauli cocycle, which a transvection does
not, so an earlier linearity test was simply the wrong test.

Its zero-set sizes are NOT uniform, and that is worth stating plainly because I
guessed otherwise from three examples:

    zeros of phi per lift    {26: 16 lifts,  44: 64 lifts}

26 is |v^perp| - 1, the Paulis a transvection fixes pointwise, and those must
conjugate with no phase -- so 26 is a floor and the 16 lifts attaining it are
accounted for. The 64 lifts with 44 zeros have EIGHTEEN more vanishing phases
than that argument predicts, and I do not have an account of them. It is
recorded as measured, not explained.

THE RESULT.

    group generated by the eighty, exact, mod global phase   > 200,000
    elements with S = identity and phi nonzero               at least one

|Sp(4,3)| is 51,840. The generated group is far past that and contains Paulis,
so the eighty are NOT a section.

WHAT THIS DOES AND DOES NOT OVERTURN.  It does NOT touch the splitting: d6bcf30
verified at n = 1 that the qutrit Clifford extension splits, and the odd-p
result is cited, so a homomorphic section exists. What is now known is that the
obvious Gauss-sum choice is not it -- picking the natural lift of each generator
independently does not assemble into a section, which is exactly the situation a
non-trivial cocycle describes even when the extension splits.

AND THE COMPILER IS UNAFFECTED.  0fb6a0f already stated the usable claim
correctly: each lift is individually verified, so a compiled word realises its
target symplectic element up to a Pauli and a global phase, which is what a
stabilizer compiler tracks anyway. That stands. What is now closed is the
stronger hope that the Pauli correction would vanish -- for this choice of
lifts, it does not.

SCOPE.  The group generation is exact integer arithmetic in F_3 and was capped
at 200,000; the run exceeded the cap, which is enough to establish "not 51,840"
and, with a Pauli exhibited, "contains Paulis". The Pauli COUNT printed by that
run is partial because enumeration stopped at the cap, so only "at least one" is
claimed -- not a subgroup order. Constructing a corrected section, by adjusting
each lift by a Pauli so the family closes, is NOT attempted here. tau_2 is
untouched.
"""

import cmath
import collections
import itertools
import json
import os
import sys

import numpy as np

ROOT = r"C:\Repos\Holotrade"
P3 = 3
D = 4
W = cmath.exp(2j * cmath.pi / P3)
CAP = 200000


def main():
    X1 = np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]], dtype=complex)
    Z1 = np.diag([1, W, W ** 2]).astype(complex)

    def P(v):
        A = np.linalg.matrix_power(X1, v[0]) @ np.linalg.matrix_power(Z1, v[2])
        B = np.linalg.matrix_power(X1, v[1]) @ np.linalg.matrix_power(Z1, v[3])
        return np.kron(A, B)

    def form(u, v):
        return (u[0] * v[2] - u[2] * v[0] + u[1] * v[3] - u[3] * v[1]) % P3

    vecs = [v for v in itertools.product(range(P3), repeat=D) if any(v)]
    vi = {v: i for i, v in enumerate(vecs)}

    def nm(v):
        i = next(k for k, x in enumerate(v) if x % P3)
        z = pow(v[i] % P3, -1, P3)
        return tuple((z * x) % P3 for x in v)

    def lift(v, lam):
        return sum((W ** ((lam * k * k) % P3))
                   * np.linalg.matrix_power(P(v), k)
                   for k in range(P3)) / np.sqrt(P3)

    gens, maxerr, zero_counts = [], 0.0, collections.Counter()
    for v in sorted({nm(x) for x in vecs}):
        for lam in (1, 2):
            U = lift(v, lam)
            Ud = U.conj().T
            S = [[0] * D for _ in range(D)]
            for j in range(D):
                e = tuple(1 if k == j else 0 for k in range(D))
                te = tuple((e[k] + lam * form(e, v) * v[k]) % P3
                           for k in range(D))
                for i in range(D):
                    S[i][j] = te[i]
            phi = [0] * len(vecs)
            for x in vecs:
                tx = tuple((x[k] + lam * form(x, v) * v[k]) % P3
                           for k in range(D))
                L = U @ P(x) @ Ud
                R = P(tx)
                i0 = int(np.argmax(np.abs(R) > 1e-9))
                z = L.flatten()[i0] / R.flatten()[i0]
                k = int(round((cmath.phase(z) % (2 * cmath.pi))
                              / (2 * cmath.pi / P3))) % P3
                maxerr = max(maxerr, abs(z - W ** k))
                phi[vi[x]] = k
            zero_counts[sum(1 for t in phi if t == 0)] += 1
            gens.append((tuple(map(tuple, S)), tuple(phi)))

    def apply(S, x):
        return tuple(sum(S[i][k] * x[k] for k in range(D)) % P3
                     for i in range(D))

    def mul(g1, g2):
        S1, f1 = g1
        S2, f2 = g2
        S = tuple(tuple(sum(S1[i][k] * S2[k][j] for k in range(D)) % P3
                        for j in range(D)) for i in range(D))
        f = tuple((f2[vi[x]] + f1[vi[apply(S2, x)]]) % P3 for x in vecs)
        return (S, f)

    IDS = tuple(tuple(1 if i == j else 0 for j in range(D)) for i in range(D))
    ID = (IDS, tuple([0] * len(vecs)))
    seen, fr, capped = {ID}, [ID], False
    while fr and not capped:
        nx = []
        for a in fr:
            for g in gens:
                b = mul(g, a)
                if b not in seen:
                    seen.add(b)
                    nx.append(b)
            if len(seen) > CAP:
                capped = True
                break
        fr = nx
    paulis = [g for g in seen if g[0] == IDS and any(g[1])]

    print("THE GAUSS-SUM LIFTS ARE NOT A SECTION")
    print("=" * 72)
    print("  0fb6a0f flagged one thing unsettled: whether the eighty form a")
    print("  homomorphic section. The first attempt hashed floats and blew up,")
    print("  and its number was disclosed as an artefact. Exact now.")
    print()
    print("  ENCODING: U P_v U^dag = w^{phi(v)} P_{Sv}, composed by")
    print("     (S1,phi1)(S2,phi2) = (S1 S2, phi2 + phi1 o S2)")
    print("  pure F_3 arithmetic. Phases read off once, cube roots to %.1e."
          % maxerr)
    print()
    print("  phi IS NOT LINEAR (0 of 80 are), and its zero-sets are NOT")
    print("  uniform -- I guessed otherwise from three examples:")
    print("     zeros of phi per lift: %s" % dict(zero_counts))
    print("     26 = |v^perp| - 1 is a floor: a transvection fixes v^perp")
    print("     pointwise so those must carry no phase. The lifts with 44")
    print("     zeros have EIGHTEEN more than that argument predicts, and I")
    print("     have no account of them. Recorded as measured, not explained.")
    print()
    print("  group generated, exact, mod global phase:  %s%d"
          % (">" if capped else "", len(seen)))
    print("  |Sp(4,3)| = 51840")
    print("  elements with S = identity and phi nonzero: at least %d"
          % min(1, len(paulis)) if not paulis else
          "  elements with S = identity and phi nonzero: at least 1")
    print()
    print("  => the eighty are NOT a homomorphic section: they generate Paulis.")
    print()
    print("  This does NOT overturn the splitting -- d6bcf30 verified it at")
    print("  n = 1 and the odd-p result is cited, so a section EXISTS. What is")
    print("  now known is that the obvious Gauss-sum choice is not it: lifting")
    print("  each generator naturally and independently does not assemble into")
    print("  a section, which is what a nontrivial cocycle looks like even when")
    print("  the extension splits.")
    print()
    print("  THE COMPILER IS UNAFFECTED. 0fb6a0f stated the usable claim")
    print("  correctly -- each lift is verified, so a word realises its target")
    print("  up to a Pauli and a global phase, which a stabilizer compiler")
    print("  tracks anyway. What closes is the stronger hope that the Pauli")
    print("  correction would vanish. For these lifts it does not.")

    ok = (len(gens) == 80 and maxerr < 1e-9 and capped
          and len(seen) > 51840 and len(paulis) >= 1
          and set(zero_counts) == {26, 44}
          and sum(zero_counts.values()) == 80)

    if "--write" in sys.argv:
        p = os.path.join(ROOT, "data", "gauss_sum_lifts_not_a_section.json")
        with open(p, "w") as fh:
            json.dump({
                "schema": "holotrade.gauss-lifts-not-a-section.v1",
                "valid": bool(ok),
                "whatWasOpen": ("0fb6a0f tabulated the eighty lifts in closed "
                                "form and verified each, but flagged as "
                                "unsettled whether they form a homomorphic "
                                "section; the first attempt hashed floats and "
                                "its number was disclosed as an artefact"),
                "exactEncoding": {
                    "representation": "U P_v U^dag = w^{phi(v)} P_{Sv}",
                    "composition": "(S1,phi1)(S2,phi2) = (S1 S2, phi2 + phi1 o S2)",
                    "arithmetic": "pure F_3, no unitaries and no rounding",
                    "phaseReadoffError": maxerr,
                },
                "phiIsNotLinear": {
                    "linearLifts": 0,
                    "zerosPerLift": {str(k): v for k, v in zero_counts.items()},
                    "whatIsAccountedFor": ("26 is |v^perp| - 1, a FLOOR: a "
                            "transvection fixes v^perp pointwise so those "
                            "Paulis must conjugate with no phase. The lifts "
                            "with 44 zeros have eighteen more vanishing phases "
                            "than that predicts and are NOT explained here -- "
                            "recorded as measured. An earlier guess that the "
                            "count was uniformly 26 came from three examples "
                            "and was wrong"),
                    "linearityWouldRequire": ("S to preserve the Pauli cocycle, "
                                              "by phi(u+v) = phi(u) + phi(v) + "
                                              "c(Su,Sv) - c(u,v); a transvection "
                                              "does not, so an earlier linearity "
                                              "test was the wrong test"),
                },
                "result": {
                    "groupOrderExceeded": len(seen),
                    "cappedAt": CAP,
                    "hitCap": capped,
                    "spOrder": 51840,
                    "containsPaulis": len(paulis) >= 1,
                    "isASection": False,
                },
                "doesNotOverturnTheSplitting": ("d6bcf30 verified the splitting "
                                                "at n = 1 and the odd-p result "
                                                "is cited, so a homomorphic "
                                                "section EXISTS. What is now "
                                                "known is that the obvious "
                                                "Gauss-sum choice is not one: "
                                                "lifting each generator "
                                                "naturally and independently "
                                                "does not assemble into a "
                                                "section, which is what a "
                                                "nontrivial cocycle looks like "
                                                "even when the extension splits"),
                "compilerUnaffected": ("0fb6a0f stated the usable claim "
                                       "correctly: each lift is individually "
                                       "verified, so a compiled word realises "
                                       "its target up to a Pauli and a global "
                                       "phase, which is what a stabilizer "
                                       "compiler tracks anyway. What closes is "
                                       "the stronger hope that the Pauli "
                                       "correction would vanish -- for these "
                                       "lifts it does not"),
                "boundary": ("the group generation is exact integer arithmetic "
                             "in F_3, capped at 200,000; the run exceeded the "
                             "cap, which suffices for 'not 51,840', and a Pauli "
                             "is exhibited, which gives 'contains Paulis'. The "
                             "Pauli COUNT from that run is PARTIAL because "
                             "enumeration stopped at the cap, so only 'at least "
                             "one' is claimed, never a subgroup order. "
                             "Constructing a corrected section by adjusting each "
                             "lift by a Pauli is NOT attempted here. tau_2 is "
                             "untouched"),
            }, fh, indent=2)
        print("\n  written: %s" % os.path.relpath(p, ROOT))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
