#!/usr/bin/env python3
"""
CORRECTION to 0c9ac42: its correction table solved the wrong equation. The
right one gives a genuine section, and a closed form.

THE BUG.  0c9ac42 corrected each Gauss-sum lift onto the metaplectic section by
solving

    phi_gauss(v) - phi_canon(v)  =  -<a, v>          (what it solved)

but conjugating by a Pauli shifts the phase at the IMAGE, not the source:

    phi_{P_a U}(v)  =  phi_U(v) - <a, S v>

so the equation to solve is

    phi_gauss(v) - phi_canon(v)  =  +<a, S v>        (correct)

Both are solvable for every transvection -- a ranges over all of F_3^4, so 80/80
"succeeds" either way -- which is exactly why the mistake survived. What does
not survive is the test: the lifts corrected by 0c9ac42's table do NOT form a
section, generating past 120,000.

WHY IT WAS CAUGHT.  Only because the check was non-circular. Deriving a
correction from the section and then verifying it against that same section
proves nothing; generating the group the corrected lifts actually produce is a
different question, and it failed. A second slip was caught the same way: I
tried to fold the Pauli into the Gauss sum as a shifted exponent,
w^{lam (j-c)^2}, which is wrong because Pauli powers do not compose phase-free
-- P_v^c P_v^j is not P_v^{c+j} -- and that form failed too.

THE CORRECTED RESULT, verified two independent ways:

    corrections solved with d = +<a, Sv>                 80 / 80
    corrected encoding EQUALS the section element        80 / 80
    group generated by the corrected eighty              51,840
    Paulis inside                                             0
    is a section                                            yes

The first check is per-lift and direct; the second is global and would fail if
any single correction were wrong. 0c9ac42's table fails both.

AND THE CLOSED FORM SURVIVES, WITH A SIGN.  Every correction is still a scalar
multiple of v -- so it stays a power of P_v -- and

    c = -lam * Q(v)     where  Q(v) = v0 v2 + v1 v3      80 / 80

against lam * Q(v) at 32/80. The sign flip is exactly the propagated sign of the
relation, which is a small confirmation that the two errors are the same error.
Thirty-two corrections are zero: precisely the v with Q(v) = 0.

    U(v, lam)  =  P_{-lam Q(v) . v}  .  (1/sqrt 3) sum_k w^{lam k^2} P_v^k

applied as a Pauli MULTIPLICATION.

WHAT THE COMPILER GETS.  A word from e05515f is a list of (v, lam); each lifts by
the formula above; the product is exactly the canonical Clifford of the target,
with no Pauli residual and no lookup table. That is what 0c9ac42 claimed and did
not have.

SCOPE.  The section is regenerated here and is the same 51,840 with no Paulis.
The corrected table is recomputed from scratch, not patched. The closed form is
checked against all eighty. Phases are read off numerically once as cube roots
of unity; everything after is integer F_3. Only n = 2, q = 3 -- no claim about
the shift at other q or n. tau_2 is untouched.
"""

import cmath
import collections
import itertools
import json
import os
import sys

import numpy as np

ROOT = r"C:\Repos\Holotrade"
P3, D = 3, 4
W = cmath.exp(2j * cmath.pi / P3)


def main():
    X1 = np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]], dtype=complex)
    Z1 = np.diag([1, W, W ** 2]).astype(complex)

    def P(v):
        A = np.linalg.matrix_power(X1, v[0]) @ np.linalg.matrix_power(Z1, v[2])
        B = np.linalg.matrix_power(X1, v[1]) @ np.linalg.matrix_power(Z1, v[3])
        return np.kron(A, B)

    def form(u, v):
        return (u[0] * v[2] - u[2] * v[0] + u[1] * v[3] - u[3] * v[1]) % P3

    def Q(v):
        return (v[0] * v[2] + v[1] * v[3]) % P3

    vecs = [v for v in itertools.product(range(P3), repeat=D) if any(v)]
    vi = {v: i for i, v in enumerate(vecs)}
    basis = [(a, b) for a in range(P3) for b in range(P3)]
    bi = {x: i for i, x in enumerate(basis)}

    def encode(U):
        Ud = U.conj().T
        img = {}
        for x in vecs:
            L = U @ P(x) @ Ud
            for y in vecs:
                R = P(y)
                i0 = int(np.argmax(np.abs(R) > 1e-9))
                z = L.flatten()[i0] / R.flatten()[i0]
                if np.allclose(L, z * R, atol=1e-7):
                    img[x] = (y, int(round((cmath.phase(z) % (2 * cmath.pi))
                                           / (2 * cmath.pi / P3))) % P3)
                    break
            else:
                return None
        S = [[0] * D for _ in range(D)]
        for j in range(D):
            e = tuple(1 if k == j else 0 for k in range(D))
            for i in range(D):
                S[i][j] = img[e][0][i]
        return (tuple(map(tuple, S)), tuple(img[x][1] for x in vecs))

    gens = []
    for M in itertools.product(range(P3), repeat=4):
        if (M[0] * M[3] - M[1] * M[2]) % P3 == 0:
            continue
        U = np.zeros((9, 9), dtype=complex)
        for x in basis:
            y = ((M[0] * x[0] + M[1] * x[1]) % P3,
                 (M[2] * x[0] + M[3] * x[1]) % P3)
            U[bi[y], bi[x]] = 1
        gens.append(U)
    for a in range(P3):
        for b in range(P3):
            for c in range(P3):
                if a == b == c == 0:
                    continue
                gens.append(np.diag(
                    [W ** ((a * x[0] * x[0] + 2 * b * x[0] * x[1]
                            + c * x[1] * x[1]) % P3) for x in basis]
                ).astype(complex))
    F1 = np.array([[W ** (j * k) for k in range(P3)] for j in range(P3)],
                  dtype=complex) / np.sqrt(P3)
    I3 = np.eye(P3, dtype=complex)
    gens += [np.kron(F1, I3), np.kron(I3, F1), np.kron(F1, F1)]
    enc = [e for e in (encode(U) for U in gens) if e is not None]

    def apply(S, x):
        return tuple(sum(S[i][k] * x[k] for k in range(D)) % P3
                     for i in range(D))

    def mul(g1, g2):
        S1, f1 = g1
        S2, f2 = g2
        S = tuple(tuple(sum(S1[i][k] * S2[k][j] for k in range(D)) % P3
                        for j in range(D)) for i in range(D))
        return (S, tuple((f2[vi[x]] + f1[vi[apply(S2, x)]]) % P3 for x in vecs))

    IDS = tuple(tuple(1 if i == j else 0 for j in range(D)) for i in range(D))
    ID = (IDS, tuple([0] * len(vecs)))
    seen, fr = {ID}, [ID]
    while fr:
        nx = []
        for a in fr:
            for g in enc:
                b = mul(g, a)
                if b not in seen:
                    seen.add(b)
                    nx.append(b)
        fr = nx
    sec = {S: f for S, f in seen}
    sec_ok = (len(seen) == 51840
              and not [g for g in seen if g[0] == IDS and any(g[1])])

    def nm(v):
        i = next(k for k, x in enumerate(v) if x % P3)
        z = pow(v[i] % P3, -1, P3)
        return tuple((z * x) % P3 for x in v)

    def gauss(v, lam):
        return sum((W ** ((lam * k * k) % P3))
                   * np.linalg.matrix_power(P(v), k)
                   for k in range(P3)) / np.sqrt(P3)

    table, match, fit_neg, fit_pos, cens, enc2 = [], 0, 0, 0, \
        collections.Counter(), []
    for v in sorted({nm(x) for x in vecs}):
        for lam in (1, 2):
            U = gauss(v, lam)
            S, fg = encode(U)
            fc = sec[S]
            d = tuple((fg[vi[x]] - fc[vi[x]]) % P3 for x in vecs)
            a = next((a for a in itertools.product(range(P3), repeat=D)
                      if all(d[vi[x]] == form(a, apply(S, x)) % P3
                             for x in vecs)), None)
            Uc = P(a) @ U if (a and any(a)) else U
            e = encode(Uc)
            if e == (S, fc):
                match += 1
            enc2.append(e)
            c = next((c for c in range(P3)
                      if tuple((c * x) % P3 for x in v) == a), None)
            cens[(Q(v), lam, c)] += 1
            fit_neg += (c == (-lam * Q(v)) % P3)
            fit_pos += (c == (lam * Q(v)) % P3)
            table.append({"v": list(v), "lam": lam,
                          "pauliCorrection": list(a), "c": c})

    seen2, fr, capped = {ID}, [ID], False
    while fr and not capped:
        nx = []
        for x in fr:
            for g in enc2:
                b = mul(g, x)
                if b not in seen2:
                    seen2.add(b)
                    nx.append(b)
            if len(seen2) > 120000:
                capped = True
                break
        fr = nx
    pl2 = sum(1 for g in seen2 if g[0] == IDS and any(g[1]))
    corrected_is_section = (not capped and len(seen2) == 51840 and pl2 == 0)

    print("THE CORRECTION TABLE WAS WRONG")
    print("=" * 72)
    print("  0c9ac42 solved  phi_gauss - phi_canon = -<a, v>")
    print("  but conjugating by P_a shifts at the IMAGE:")
    print("     phi_{P_a U}(v) = phi_U(v) - <a, S v>")
    print("  so the equation is  phi_gauss - phi_canon = +<a, S v>.")
    print("  Both are solvable 80/80 -- a ranges over all of F_3^4 -- which is")
    print("  exactly why the mistake survived. The TEST is what fails.")
    print()
    print("  section regenerated: %d elements, no Paulis: %s"
          % (len(seen), sec_ok))
    print()
    print("  corrected encoding EQUALS the section element   %d / 80" % match)
    print("  group generated by the corrected eighty         %d" % len(seen2))
    print("  Paulis inside                                   %d" % pl2)
    print("  IS A SECTION                                    %s"
          % corrected_is_section)
    print("  (0c9ac42's table fails both: it ran past 120,000.)")
    print()
    print("  CLOSED FORM SURVIVES, WITH A SIGN:")
    print("     c = -lam * Q(v),  Q(v) = v0v2 + v1v3     %d / 80" % fit_neg)
    print("     c = +lam * Q(v)                          %d / 80" % fit_pos)
    print("  the flip is the propagated sign of the relation -- a small")
    print("  confirmation that the two errors are the same error.")
    print()
    for k in sorted(cens):
        print("     Q=%d lam=%d -> c=%d : %2d" % (k[0], k[1], k[2], cens[k]))
    print()
    print("     U(v,lam) = P_{-lam Q(v) . v} . (1/sqrt3) sum_k w^{lam k^2} P_v^k")
    print("  applied as a Pauli MULTIPLICATION -- folding it into the sum as a")
    print("  shifted Gauss sum is also wrong, since Pauli powers do not")
    print("  compose phase-free. That form failed the same test.")

    ok = (sec_ok and match == 80 and corrected_is_section and fit_neg == 80
          and all(t["c"] is not None for t in table))

    if "--write" in sys.argv:
        p = os.path.join(ROOT, "data", "correction_table_fixed.json")
        with open(p, "w") as fh:
            json.dump({
                "schema": "holotrade.correction-table-fixed.v1",
                "valid": bool(ok),
                "supersedes": "0c9ac42's correction table",
                "theBug": {
                    "whatItSolved": "phi_gauss(v) - phi_canon(v) = -<a, v>",
                    "correctRelation": "phi_gauss(v) - phi_canon(v) = +<a, S v>",
                    "why": ("conjugating by a Pauli shifts the phase at the "
                            "IMAGE: phi_{P_a U}(v) = phi_U(v) - <a, S v>"),
                    "whyItSurvived": ("both are solvable 80/80 because a ranges "
                                      "over all of F_3^4, so the solve step "
                                      "'succeeds' either way; only the section "
                                      "test distinguishes them"),
                    "howItWasCaught": ("the check was non-circular -- deriving a "
                                       "correction from the section and "
                                       "verifying it against that same section "
                                       "proves nothing, but generating the group "
                                       "the corrected lifts actually produce is "
                                       "a different question, and it failed"),
                    "secondSlipCaughtTheSameWay": ("folding the Pauli into the "
                                                   "Gauss sum as a shifted "
                                                   "exponent w^{lam (j-c)^2} is "
                                                   "also wrong: Pauli powers do "
                                                   "not compose phase-free, "
                                                   "P_v^c P_v^j is not "
                                                   "P_v^{c+j}"),
                },
                "verification": {
                    "sectionOrder": len(seen),
                    "sectionHasNoPaulis": sec_ok,
                    "correctedEncodingEqualsSection": match,
                    "outOf": 80,
                    "groupGeneratedByCorrected": len(seen2),
                    "pauliCount": pl2,
                    "isASection": corrected_is_section,
                    "twoIndependentChecks": ("the first is per-lift and direct, "
                                             "the second global and would fail "
                                             "if any single correction were "
                                             "wrong"),
                },
                "closedForm": {
                    "everyCorrectionIsAMultipleOfV": True,
                    "formula": "c = -lam * Q(v)",
                    "Q": "Q(v) = v0 v2 + v1 v3",
                    "fitsNegative": fit_neg,
                    "fitsPositive": fit_pos,
                    "outOf": 80,
                    "signIsPropagated": ("the flip is exactly the propagated "
                                         "sign of the relation, a small "
                                         "confirmation that the two errors are "
                                         "the same error"),
                    "lift": ("U(v,lam) = P_{-lam Q(v) . v} . (1/sqrt 3) sum_k "
                             "w^{lam k^2} P_v^k, applied as a Pauli "
                             "MULTIPLICATION"),
                },
                "census": {"Q=%d,lam=%d,c=%d" % k: v
                           for k, v in sorted(cens.items())},
                "table": table,
                "boundary": ("the section is regenerated here and is the same "
                             "51,840 with no Paulis; the corrected table is "
                             "recomputed from scratch, not patched; the closed "
                             "form is checked against all eighty. Phases are "
                             "read off numerically once as cube roots of unity, "
                             "everything after is integer F_3. Only n = 2, "
                             "q = 3 -- no claim about the shift at other q or n. "
                             "tau_2 is untouched"),
            }, fh, indent=2)
        print("\n  written: %s" % os.path.relpath(p, ROOT))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
