#!/usr/bin/env python3
"""Exhaustive PSp(4,3)-orbit census of W33 mass-12 and mass-16 excesses.

The earlier pencil-induction probe deliberately tried a strong conjecture:
all admissible mass-12/16 excesses might contain a point pencil. CP-SAT found
counterexamples in milliseconds. This pass does not assume pencil generation.
It enumerates *every* nonnegative integer solution of

    A e = 2 e + k 1,    sum(e)=4k,

for k=3 and k=4, then quotients the complete solution set by the exact
25,920-element PSp(4,3) action generated by the same five certified
transvections used by the preceding pass.

Each orbit is labelled pencilGenerated iff its representative lies in the
finite multiset-sum family of k point pencils. Thus exceptional load-profile
geometry becomes explicit rather than hidden behind a failed induction.

A census is promoted as exact only when OR-Tools finishes all-solution
enumeration with OPTIMAL status before the budget/cap. FEASIBLE/UNKNOWN or a
solution cap is explicitly partial and makes no completeness claim.
"""
from __future__ import annotations

import argparse
from collections import Counter, deque
import importlib.util
import itertools
import json
from pathlib import Path
import time

from ortools.sat.python import cp_model

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "analysis" / "the_mass12_mass16_excess_pencil_induction.py"
OUT = ROOT / "data" / "mass12_mass16_exact_orbit_census.json"


def load_base():
    spec = importlib.util.spec_from_file_location("excess_induction_for_census", BASE)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot import excess classifier")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    mass8, pts, lines, line_index, pencils, adj = mod.load_base()
    _, lgens, group_order = mod.five_psp_generators(mass8, pts, lines, line_index)
    assert group_order == 25920
    return mod, pencils, adj, lgens


class Collector(cp_model.CpSolverSolutionCallback):
    def __init__(self, vars_, cap):
        super().__init__()
        self.vars = vars_
        self.cap = int(cap)
        self.solutions = set()
        self.hit_cap = False

    def on_solution_callback(self):
        self.solutions.add(tuple(self.Value(v) for v in self.vars))
        if len(self.solutions) >= self.cap:
            self.hit_cap = True
            self.StopSearch()


def enumerate_mass(k, adj, *, budget, cap):
    mass = 4*k
    model = cp_model.CpModel()
    e = [model.NewIntVar(0, k, f"e{i}") for i in range(40)]
    model.Add(sum(e) == mass)
    for i in range(40):
        model.Add(sum(e[j] for j in adj[i]) == 2*e[i] + k)

    solver = cp_model.CpSolver()
    solver.parameters.enumerate_all_solutions = True
    solver.parameters.max_time_in_seconds = float(budget)
    solver.parameters.num_search_workers = 1
    solver.parameters.random_seed = 20260908 + mass
    cb = Collector(e, cap)
    start = time.time()
    result = solver.Solve(model, cb)
    elapsed = round(time.time()-start, 3)
    name = solver.StatusName(result)
    complete = (result == cp_model.OPTIMAL and not cb.hit_cap)
    return {
        "mass": mass,
        "k": k,
        "solverStatus": name,
        "complete": complete,
        "hitSolutionCap": cb.hit_cap,
        "solutionsFound": len(cb.solutions),
        "seconds": elapsed,
        "budgetSeconds": float(budget),
        "solutionCap": int(cap),
        "branches": solver.NumBranches(),
        "conflicts": solver.NumConflicts(),
    }, cb.solutions


def add_pencils(ms, pencils):
    out=[0]*40
    for p in ms:
        for i,x in enumerate(pencils[p]): out[i]+=x
    return tuple(out)


def pencil_family(k, pencils):
    return {add_pencils(ms,pencils) for ms in itertools.combinations_with_replacement(range(40),k)}


def act_vector(e, perm):
    out=[0]*40
    for i,x in enumerate(e): out[perm[i]]=x
    return tuple(out)


def orbit_rows(solutions, pencil_vectors, lgens, complete):
    remaining=set(solutions)
    rows=[]
    while remaining:
        seed=min(remaining)
        orb={seed}; q=deque([seed])
        while q:
            x=q.popleft()
            for g in lgens:
                y=act_vector(x,g)
                if complete and y not in solutions:
                    raise AssertionError("complete census is not PSp-stable")
                if y in solutions and y not in orb:
                    orb.add(y); q.append(y)
        remaining.difference_update(orb)
        h=Counter(seed)
        rows.append({
            "orbitSizeWithinCensus":len(orb),
            "pencilGenerated":seed in pencil_vectors,
            "representative":list(seed),
            "histogram":{str(a):b for a,b in sorted(h.items())},
            "supportSize":40-h.get(0,0),
        })
    # histogram is a dict and dicts are not orderable, so sorting on it
    # raises TypeError before any census can be written. Sort on its
    # items instead; the intended grouping is unchanged.
    rows.sort(key=lambda r:(not r['pencilGenerated'],
                            sorted(r['histogram'].items()),
                            r['representative']))
    return rows


def census(k, mod, pencils, adj, lgens, *, budget, cap):
    stats, sols=enumerate_mass(k,adj,budget=budget,cap=cap)
    pencils_k=pencil_family(k,pencils)
    rows=orbit_rows(sols,pencils_k,lgens,stats['complete'])
    pg=sum(1 for x in sols if x in pencils_k)
    ex=len(sols)-pg
    if stats['complete']:
        assert pg == len(pencils_k), (pg,len(pencils_k))
        assert sum(r['orbitSizeWithinCensus'] for r in rows)==len(sols)
        assert sum(r['orbitSizeWithinCensus'] for r in rows if r['pencilGenerated'])==len(pencils_k)
    return {
        **stats,
        "pencilGeneratedFamilySize":len(pencils_k),
        "pencilGeneratedSolutionsInCensus":pg,
        "exceptionalSolutionsInCensus":ex,
        "orbitCountWithinCensus":len(rows),
        "pencilGeneratedOrbitCountWithinCensus":sum(r['pencilGenerated'] for r in rows),
        "exceptionalOrbitCountWithinCensus":sum(not r['pencilGenerated'] for r in rows),
        "orbits":rows,
    }


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--mass12-budget',type=float,default=180.0)
    ap.add_argument('--mass16-budget',type=float,default=240.0)
    ap.add_argument('--cap',type=int,default=2_000_000)
    ap.add_argument('--write',action='store_true')
    args=ap.parse_args()
    if min(args.mass12_budget,args.mass16_budget,args.cap)<=0: raise ValueError('positive budgets/cap required')
    mod,pencils,adj,lgens=load_base()
    m12=census(3,mod,pencils,adj,lgens,budget=args.mass12_budget,cap=args.cap)
    m16=census(4,mod,pencils,adj,lgens,budget=args.mass16_budget,cap=args.cap)
    out={
        "schema":"holotrade.w33-mass12-mass16-exact-orbit-census.v1",
        "status":"PASS" if m12['complete'] and m16['complete'] else "PARTIAL",
        "mass12":m12,
        "mass16":m16,
        "reading":(
            "When complete=true, the listed PSp orbits are the exhaustive axis load-excess classes for the corresponding mass. "
            "Pencil-generated and exceptional classes are labelled separately."
        ),
        "boundary":"Axis-load classification only; exact tensor-blocker feasibility still requires pairing row/column excess orbits and solving product-line gluing.",
    }
    print(json.dumps(out,indent=2,sort_keys=True))
    if args.write:
        OUT.parent.mkdir(parents=True,exist_ok=True)
        OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')

if __name__=='__main__': main()
