#!/usr/bin/env python3
"""
THE 3^(1+12)-INVARIANTS OF A8^3 AND OF MOONSHINE AGREE THROUGH WEIGHT TWO AND PART AT
WEIGHT THREE; ALONG THE WAY, INTEGRALITY FORCES THE MONSTER FUSION OF O_3(N(3B)).

4104251 left an open problem: the extraspecial 3^(1+12) generated by the three two-qutrit
Pauli groups of the Niemeier A8^3 theory empties V_1, so a non-cyclic orbifold by it is not
excluded from giving Moonshine. The most direct way it could happen is for V_{A8^3} and
V^natural to share the fixed-point subalgebra of their 3^(1+12)s, the Monster's being
O_3 of the 3B normaliser 3^(1+12).2Suz.2. This file tests that route exactly.

1. THE MONSTER SIDE IS FORCED. The noncentral elements of O_3(N(3B)) lie over the nonzero
   vectors of F3^12, and 2.Suz has exactly two orbits there, of sizes 65520 and 465920
   (computed from the ATLAS 12-dimensional F3 generators vendored in TOE
   data/atlas/2SuzG1-f3r12B0.m1/.m2; the 65520 are the 32760-point tight set of TOE
   196cc86dc, with both signs). The three central lifts of a noncentral element are
   conjugate inside 3^(1+12), so every lift over one orbit lies in a single Monster class.
   Of the nine class assignments in {3A,3B,3C}^2, exactly ONE gives non-negative integral
   invariant dimensions at every weight 0..8: 3A over the 65520 orbit, 3B over the 465920
   orbit, together with the 3B centre.

2. THE A8^3 SIDE is exact, from the twining characters of 903e1b7:
   1 identity (J + 240), 2 central (T_3B + 240), 1536000 with k = 3 (T_3B - 3),
   57600 with k = 2, and 720 with k = 1.

3. THE COMPARISON, as graded dimensions of the invariants:
       weight            0   1   2     3      4       5        6        7         8
       V_{A8^3}^H        1   0   144   1256   14148   137304   1184744  9565128   71731161
       (V^natural)^H     1   0   144   1016   8388    59544    422504   3547368   31295961
   They agree exactly at weights 0, 1 and 2, and differ from weight 3 on.

WHY WEIGHT TWO AGREES. Both weight-2 spaces are 196884-dimensional, and the centre has trace
54 on both (T_3B). So both centre-fixed parts have dimension (196884 + 2*54)/3 = 65664 =
144 + 65520, and both faithful parts have dimension 131220 = 180 * 729: the 729-dimensional
3B register of 68df33f. Weight two is fixed by the centre's trace together with the
dimension; weight three is not.

CONSEQUENCE. Moonshine and V_{A8^3} do NOT share the fixed-point subalgebra of these two
3^(1+12)s. This refutes the direct route to the open problem of 4104251. It does not refute
every construction: a non-abelian orbifold's dual symmetry is non-invertible, so V_{A8^3}^H
need not be the fixed points of a Monster subgroup inside V^natural.

SCOPE. The comparison uses exact twining series and the Conway-Norton series for J, 3A,
3B and 3C. The Monster fusion of O_3(N(3B)) is derived here by integrality alone; it is
classical group theory (Norton; the Monster's 3-local analysis) and is recovered rather
than assumed.
"""

import argparse
import importlib.util
import itertools
import json
import os
from fractions import Fraction as Fr

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
H_ORDER = 3 ** 13
SUZ_ORBITS = (65520, 465920)                   # 2.Suz on F3^12 \ 0, computed from the ATLAS generators


def load_carriers():
    spec = importlib.util.spec_from_file_location(
        "carriers", os.path.join(ROOT, "analysis", "the_a8_cubed_pauli_group_moves_between_the_w33_carriers.py"))
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    checks = {}
    car = load_carriers()
    mon = car.monster_series()
    types = {"identity": [car.ZERO] * 3, "z": [car.CENT, car.ZERO, car.ZERO],
             "k=1": [car.PZ, car.ZERO, car.ZERO], "k=2": [car.PZ, car.PZ, car.ZERO], "k=3": [car.PZ] * 3}
    tw = {k: car.twining(v) for k, v in types.items()}
    L = len(tw["identity"])
    count_A = {"identity": 1, "z": 2, "k=3": 3 * 80 ** 3, "k=2": 9 * 80 ** 2, "k=1": 9 * 80}
    checks["A8_element_counts_sum_to_3_13"] = sum(count_A.values()) == H_ORDER
    A = [Fr(sum(count_A[k] * tw[k][n] for k in count_A), H_ORDER) for n in range(L)]
    checks["A8_invariants_integral"] = all(x.denominator == 1 and x >= 0 for x in A)

    checks["suz_orbits_partition"] = 1 + 2 + 3 * sum(SUZ_ORBITS) == H_ORDER
    valid = []
    for c1, c2 in itertools.product(("3A", "3B", "3C"), repeat=2):
        dims = []
        for n in range(L):
            if n == 1:
                tot = 0                                    # V^natural_1 = 0: every trace vanishes
            else:
                tot = mon["J"][n] + 2 * mon["3B"][n] + 3 * SUZ_ORBITS[0] * mon[c1][n] + 3 * SUZ_ORBITS[1] * mon[c2][n]
            dims.append(Fr(tot, H_ORDER))
        if all(x.denominator == 1 and x >= 0 for x in dims):
            valid.append((c1, c2, dims))
    print("  Monster class assignments (65520 orbit, 465920 orbit) with nonnegative integral invariants:",
          [(c1, c2) for c1, c2, _ in valid])
    checks["monster_fusion_forced_3A_3B"] = [(c1, c2) for c1, c2, _ in valid] == [("3A", "3B")]
    M = valid[0][2] if valid else [Fr(0)] * L

    print("  weight   V_A8^3^H        V_nat^H")
    agree = []
    for n in range(L):
        print("   %d       %-14s %s %s" % (n, A[n], M[n], "" if A[n] == M[n] else "<- differ"))
        agree.append(A[n] == M[n])
    first_diff = next((n for n, ok in enumerate(agree) if not ok), None)
    checks["agree_through_weight_two"] = all(agree[:3])
    checks["first_difference_at_weight_three"] = first_diff == 3

    # the weight-2 mechanism: centre-fixed and faithful dimensions coincide
    fixed2_A = Fr(tw["identity"][2] + 2 * tw["z"][2], 3)
    fixed2_M = Fr(mon["J"][2] + 2 * mon["3B"][2], 3)
    faithful = mon["J"][2] - fixed2_M
    print("  weight-2 centre-fixed dims: A8^3 %s, V_nat %s; faithful part %s = %s x 729" % (
        fixed2_A, fixed2_M, faithful, faithful / 729))
    checks["weight2_centre_fixed_65664_both"] = fixed2_A == fixed2_M == 65664
    checks["weight2_faithful_is_180_registers"] = faithful == 131220 == 180 * 729
    checks["weight2_split_144_plus_65520"] = fixed2_M == 144 + SUZ_ORBITS[0]

    for k, v in checks.items():
        print("  %-42s %s" % (k, v))
    ok = all(checks.values())
    print("VALID:", ok)
    if args.write:
        payload = {
            "claim": "The 3^(1+12)-invariants of the Niemeier A8^3 theory (Pauli group) and of Moonshine (O_3 of the 3B "
                     "normaliser) have identical graded dimensions 1, 0, 144 at weights 0, 1, 2 and differ from weight 3 "
                     "(1256 vs 1016). So the two theories do not share the fixed-point subalgebra of these groups, "
                     "refuting the direct route to Moonshine from 4104251. Integrality alone forces the Monster fusion of "
                     "O_3(N(3B)): 3A over the 65520 orbit, 3B over the 465920 orbit.",
            "invariantDims": {"A8cubed": [int(x) for x in A], "moonshine": [int(x) for x in M]},
            "firstDifferenceWeight": first_diff,
            "monsterFusion": {"orbit_65520": "3A", "orbit_465920": "3B", "centre": "3B", "unique_integral_assignment": True},
            "weight2": {"centreFixed": 65664, "trivialPlusCharacters": "144 + 65520", "faithful": 131220,
                        "faithfulRegisters": "180 x 729"},
            "suzOrbitsOnF3_12": list(SUZ_ORBITS),
            "checks": checks, "valid": ok,
            "status": "exact computation; refutes the shared-fixed-subalgebra route only",
            "sources": ["Holotrade 4104251", "Holotrade 903e1b7", "Holotrade 68df33f", "TOE 196cc86dc",
                        "TOE data/atlas/2SuzG1-f3r12B0.m1/.m2 (ATLAS)", "Conway-Norton McKay-Thompson series"]}
        with open(os.path.join(ROOT, "data", "w33_3_1_12_invariants_a8cubed_vs_moonshine.json"), "w") as f:
            json.dump(payload, f, indent=1)
        print("written")


if __name__ == "__main__":
    main()
