#!/usr/bin/env python3
"""
THE CENTRAL-CHARACTER DOUBLET IS THE PAIR OF TWISTED SECTORS: A REPRESENTATION-LEVEL
INTERTWINER FOR THE W(3,3) OUTER INVERSION, AND THE TWO PHYSICAL OPERATORS THAT REALISE IT.

TOE w33_suzuki_outer_heisenberg_sector_swap.py proves that a multiplier-minus-one similitude
of the F3^{2d} phase space inverts the centre of the Heisenberg group 3^(1+2d), hence swaps
the two faithful Schroedinger sectors r = 1 and r = 2; it can be implemented antiunitarily
inside one sector, or linearly as a block swap on their sum. TOE w33_z6ii_c2_extension_no_go.py
then rules out identifying that C2 with the cyclic Z6-II point group, and
w33_heterotic_s3_outer_target.py matches its extension law to the S3 point group of Konopka's
non-Abelian heterotic orbifold, leaving open (their words) a

    "representation/gauge-spectrum intertwiner ... Compare irreducible sector projectors and
     centralizer actions of the heterotic S3 model with the W33 V1+V2 induced module."

This file supplies that intertwiner, on the heterotic side, exactly and finitely.

THE DICTIONARY. On a T^2/Z3 plane the three fixed points carry the twisted matter, and the
traditional flavour symmetry generated by the two lattice translations is the Heisenberg group
Delta(27) = 3^(1+2) (Kobayashi-Nilles-Ploeger-Raby-Ratz, hep-ph/0611020): one translation
permutes the fixed points (X), the other multiplies them by the space-group selection-rule
phases (Z), and [X, Z] = omega is the point-group selection rule itself. The centre is
therefore not an abstract label: it IS the order-three point-group element acting on sectors,
so a state of the theta^k twisted sector carries central character omega^k. Hence

    r = 1  <->  the theta-twisted sector T1,
    r = 2  <->  the theta^2-twisted sector T2,

and the central-character doublet V1 + V2 of the TOE certificate is the pair of twisted
sectors. For d planes the selection rule is one Z3 for the whole orbifold, so the d Heisenberg
groups share their centre and combine to 3^(1+2d) on the 3^d fixed points; d = 2 gives
3^(1+4) on nine fixed points, whose commutator form on F3^4 is the W(3,3) symplectic form.

WHAT THIS FILE COMPUTES (exact, over Z[omega] as integer triples, no floating point).
  (a) The flavour group is 3^(1+2d) with centre of order three, and the commutator form is the
      standard symplectic form on F3^{2d}; for d = 2 that is the W(3,3) form.
  (b) The two candidate inversions act on generators as
          reflection  P : X -> X^-1, Z -> Z   (fixed points f -> -f, unitary)
          conjugation K : X -> X,    Z -> Z^-1 (complex conjugation, antiunitary)
      Both invert the centre, both induce multiplier-minus-one similitudes of F3^{2d}, and
      they differ by -1 in Sp(2d,3). So they lie in the same outer coset: the TOE certificate's
      two implementations are exactly these two physical operators.
  (c) Composing the sector-r representation with either map gives the sector-(-r) one: the
      intertwiner is explicit, and the "block swap" of V1 + V2 is the exchange of T1 and T2.
  (d) The two are physically distinguishable, which is the point the TOE files could not
      settle from the group law alone:
          the S3 reflection is a UNITARY element of the space group, so it projects the
          spectrum and can break gauge symmetry;
          CP is an ANTIUNITARY outer automorphism of the Narain space group, so it constrains
          couplings and phases but projects nothing.
      Both invert the centre; only the first is an orbifold projection.

CONSEQUENCE FOR THE STANDARD-MODEL QUESTION. Because CP projects nothing, it cannot supply the
even-order element that the order-three no-goes (a6e1c69, 47e85ab, fa65bd4, dd68cfa) require.
The even-order element must be an element of the space group. That is consistent with, and
independent of, the Z6-II construction in
the_w33_twist_does_host_a_standard_model_in_the_even_order_orbifold.py, whose C2 is the
point-group element theta^3 -- a commuting C2, which inverts nothing.

SCOPE. Finite group theory and representation theory, exact. The identification of X, Z and
the centre with translations and the selection rule is the published stringy dictionary and is
cited, not re-derived; likewise the CP-as-outer-automorphism statement. No claim is made that
Konopka's S3 model has a W(3,3)-class gauge embedding; that is a separate question.
"""

import argparse
import itertools
import json
import os
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Heisenberg group elements of 3^(1+2d) as (a, b, c): omega^c * X^a * Z^b, with
# a, b in F3^d and c in F3.  Z^b X^a = omega^{a.b} X^a Z^b fixes the product rule.
def mul(g, h, d):
    a, b, c = g
    a2, b2, c2 = h
    ab = sum(x * y for x, y in zip(b, a2)) % 3
    return (tuple((x + y) % 3 for x, y in zip(a, a2)),
            tuple((x + y) % 3 for x, y in zip(b, b2)),
            (c + c2 + ab) % 3)


def inv(g, d):
    a, b, c = g
    ia = tuple((-x) % 3 for x in a)
    ib = tuple((-x) % 3 for x in b)
    ab = sum(x * y for x, y in zip(b, ia)) % 3
    return (ia, ib, (-c - ab) % 3)


def comm(g, h, d):
    return mul(mul(g, h, d), inv(mul(h, g, d), d), d)


def elements(d):
    F = list(itertools.product(range(3), repeat=d))
    return [(a, b, c) for a in F for b in F for c in range(3)]


def symplectic(u, v, d):
    """commutator exponent: <(a,b),(a',b')> = b.a' - a.b' on F3^{2d}

    The sign follows the product rule Z^b X^a = omega^{a.b} X^a Z^b, so that
    [g, h] = omega^{<g, h>} exactly (verified below, not assumed).
    """
    a, b = u[:d], u[d:]
    a2, b2 = v[:d], v[d:]
    return (sum(x * y for x, y in zip(b, a2)) - sum(x * y for x, y in zip(a, b2))) % 3


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    checks = {}
    results = {}

    for d in (1, 2, 3):
        G = elements(d)
        assert len(G) == 3 ** (2 * d + 1)
        zero = (tuple([0] * d), tuple([0] * d), 0)
        centre = [g for g in G if all(comm(g, h, d) == zero for h in G)]
        # commutator of a general pair equals omega^{symplectic form}
        ok_form = True
        for g in G[:200]:
            for h in G[:200]:
                a, b, _ = g
                a2, b2, _ = h
                if comm(g, h, d)[2] != symplectic(list(a) + list(b), list(a2) + list(b2), d):
                    ok_form = False
        # exponent-3 and extraspecial shape
        cubes = Counter(mul(mul(g, g, d), g, d) == zero for g in G)
        results["d=%d" % d] = {"order": len(G), "centre_order": len(centre),
                               "all_cubes_trivial": cubes[True] == len(G)}
        checks["d%d_extraspecial_3_1_%d" % (d, 2 * d)] = len(G) == 3 ** (2 * d + 1) and len(centre) == 3
        checks["d%d_commutator_is_symplectic_form" % d] = ok_form
        checks["d%d_exponent_three" % d] = cubes[True] == len(G)
    print("  flavour groups: %s" % results)

    # (b) the two inversions, as automorphisms defined on generators
    d = 2
    G = elements(d)
    zero = (tuple([0] * d), tuple([0] * d), 0)

    def reflect(g):                       # P: fixed points f -> -f, so X -> X^-1, Z -> Z
        a, b, c = g
        ia = tuple((-x) % 3 for x in a)
        # omega = [X, Z] must go to [X^-1, Z] = omega^-1, so the centre is inverted too;
        # with that, omega^c X^a Z^b -> omega^-c X^-a Z^b is a homomorphism (checked below).
        return (ia, b, (-c) % 3)

    def conjugate(g):                     # K: complex conjugation, X -> X, Z -> Z^-1, omega -> omega^-1
        a, b, c = g
        ib = tuple((-x) % 3 for x in b)
        return (a, ib, (-c) % 3)

    def is_auto(f):
        return all(f(mul(g, h, d)) == mul(f(g), f(h), d) for g in G[:150] for h in G[:150])

    omega = (tuple([0] * d), tuple([0] * d), 1)
    checks["reflection_is_an_automorphism"] = is_auto(reflect)
    checks["conjugation_is_an_automorphism"] = is_auto(conjugate)
    checks["reflection_inverts_the_centre"] = reflect(omega) == inv(omega, d)
    checks["conjugation_inverts_the_centre"] = conjugate(omega) == inv(omega, d)

    # induced maps on phase space and their multipliers
    def induced(f):
        M = []
        for i in range(2 * d):
            a = [0] * d
            b = [0] * d
            if i < d:
                a[i] = 1
            else:
                b[i - d] = 1
            g = (tuple(a), tuple(b), 0)
            fa, fb, _ = f(g)
            M.append(list(fa) + list(fb))
        return M                                    # rows = images of the basis

    def multiplier(M):
        vals = set()
        for i in range(2 * d):
            for j in range(2 * d):
                e_i = [1 if k == i else 0 for k in range(2 * d)]
                e_j = [1 if k == j else 0 for k in range(2 * d)]
                s = symplectic(e_i, e_j, d)
                t = symplectic(M[i], M[j], d)
                if s:
                    vals.add((t * pow(s, -1, 3)) % 3)
        return vals.pop() if len(vals) == 1 else None

    mP, mK = multiplier(induced(reflect)), multiplier(induced(conjugate))
    print("  multipliers: reflection %s, conjugation %s  (2 = -1 mod 3)" % (mP, mK))
    checks["reflection_has_multiplier_minus_one"] = mP == 2
    checks["conjugation_has_multiplier_minus_one"] = mK == 2

    # they differ by -1 in Sp(2d,3): reflection then conjugation is x -> -x
    MINUS = [[(-1 if i == j else 0) % 3 for j in range(2 * d)] for i in range(2 * d)]
    KP = induced(lambda g: conjugate(reflect(g)))
    checks["reflection_and_conjugation_differ_by_minus_one"] = KP == MINUS
    checks["minus_one_is_symplectic"] = multiplier(MINUS) == 1

    # (c) sector modules: the irreducible characters with central character omega^r
    # chi_r(g) = 3^d omega^{r c} if (a,b) = 0, else 0.  Composing with an inversion sends r -> -r.
    def chi(r, g):
        a, b, c = g
        if any(a) or any(b):
            return None                     # zero
        return (r * c) % 3

    def compose_character(r, f):
        vals = {}
        for g in G:
            x, y = chi(r, f(g)), chi(r, g)
            if x is not None:
                vals[g] = x
        return vals

    swap_ok = True
    for f in (reflect, conjugate):
        for r in (1, 2):
            for g in G:
                if chi(r, g) is None:
                    continue
                # f fixes the centre setwise; the pulled-back character is the (-r) one
                if chi(r, f(g)) != chi((-r) % 3, g):
                    swap_ok = False
    checks["both_inversions_swap_the_two_sector_characters"] = swap_ok
    print("  sector characters r = 1, 2 are exchanged by both inversions: %s" % swap_ok)

    # (d) for d = 2 the commutator form is the W(3,3) form: 40 isotropic points, 40 lines
    pts = [v for v in itertools.product(range(3), repeat=4) if any(v)]
    proj = []
    seen = set()
    for v in pts:
        k = min(tuple((c * s) % 3 for c in v) for s in (1, 2))
        if k not in seen:
            seen.add(k)
            proj.append(v)
    checks["w33_has_40_points"] = len(proj) == 40
    iso_lines = 0
    for u, v in itertools.combinations(proj, 2):
        if symplectic(list(u), list(v), 2) == 0:
            iso_lines += 1
    # each totally isotropic line has 4 points, hence 6 unordered pairs
    checks["w33_has_40_totally_isotropic_lines"] = iso_lines % 6 == 0 and iso_lines // 6 == 40

    for k, v in checks.items():
        print("  %-48s %s" % (k, v))
    valid = all(checks.values())
    print("VALID:", valid)

    if args.write:
        payload = {
            "claim": "In a heterotic Z3 orbifold the centre of the fixed-point flavour Heisenberg group 3^(1+2d) is the "
                     "point-group selection rule, so a state of the theta^k twisted sector carries central character "
                     "omega^k. The central-character doublet V1 + V2 of the W(3,3) Pauli group is therefore the pair of "
                     "twisted sectors T1 + T2, and the outer inversion's block swap is their exchange. Two physical "
                     "operators realise the inversion: the unitary S3 reflection (X -> X^-1, Z -> Z), an element of the "
                     "space group that projects the spectrum, and antiunitary CP (X -> X, Z -> Z^-1), an outer "
                     "automorphism of the Narain space group that projects nothing. They induce multiplier-minus-one "
                     "similitudes differing by -1 in Sp(2d,3), so they are the two implementations the TOE certificate "
                     "found. Because CP projects nothing it cannot supply the even-order element the order-three no-goes "
                     "require.",
            "dictionary": {"X": "lattice translation permuting the three fixed points of a T^2/Z3 plane",
                           "Z": "lattice translation acting by the space-group selection-rule phases",
                           "centre": "the order-three point-group element; equals the selection rule",
                           "central character omega^k": "the theta^k twisted sector",
                           "d planes": "one shared centre, so 3^(1+2d) on 3^d fixed points; d = 2 gives the W(3,3) form"},
            "inversions": {"S3_reflection": {"action": "X -> X^-1, Z -> Z", "multiplier": -1, "unitary": True,
                                             "is_a_space_group_element": True, "projects_the_spectrum": True},
                           "CP": {"action": "X -> X, Z -> Z^-1, omega -> omega^-1", "multiplier": -1,
                                  "unitary": False, "is_a_space_group_element": False,
                                  "projects_the_spectrum": False},
                           "relation": "they differ by -1 in Sp(2d,3), hence lie in the same multiplier-minus-one coset"},
            "flavourGroups": results,
            "answers": "the open 'representation/gauge-spectrum intertwiner' of TOE w33_heterotic_s3_outer_target.py",
            "checks": checks, "valid": valid,
            "status": "exact finite group and character computation; the stringy identification of X, Z, the centre and "
                      "CP is published and cited, not re-derived",
            "sources": ["TOE w33_suzuki_outer_heisenberg_sector_swap.py", "TOE w33_z6ii_c2_extension_no_go.py",
                        "TOE w33_heterotic_s3_outer_target.py", "Holotrade 68df33f", "Holotrade 4104251",
                        "Kobayashi-Nilles-Ploeger-Raby-Ratz hep-ph/0611020 (Delta(54) from Z3 fixed points)",
                        "Nilles-Ramos-Sanchez-Trautner-Vaudrevange arXiv:1808.07060 (CP as an outer automorphism of the "
                        "Narain space group)",
                        "Konopka, JHEP 07 (2013) 023 (non-Abelian S3 heterotic orbifold)"]}
        with open(os.path.join(ROOT, "data", "w33_central_character_doublet_is_twisted_sectors.json"), "w") as f:
            json.dump(payload, f, indent=1)
        print("written")


if __name__ == "__main__":
    main()
