#!/usr/bin/env python3
"""
The bulk 27 of W(3,3) and the 27 lines of the cubic surface are both regular
torsors of the qutrit Pauli group at a point -- but for the qutrit Clifford
group they are two of THREE inequivalent torsors, and the three are cycled by
twisting with the one-dimensional characters of SL(2,3). The identification of
the two 27s in W33-Theory Passes 370-371 is exactly such a twist.

PRIOR ART, CITED.
  * W33-Theory THE_27_FOLD_WAY.md, Passes 370-371: the 27 points opposite p0
    (the bulk) and the E6 27 are one torsor for the elation (qutrit Pauli)
    group, and both normalisers are 3^{1+2}:SL(2,3) with order-24 stabilisers
    having one involution; "both 27-point actions are the coset action ... on
    an SL(2,3) complement. Hence they are PERMUTATION-ISOMORPHIC."
  * Pass 372: the bulk collinearity graph is 8-regular while the E6 graph is
    SRG(27,10,1,5), "the identification is exactly quantum-level ... and
    provably NOT geometric".
  * Pass 386: "the two geometries differ precisely by the qutrit phase fiber".
  * Holotrade gq24_lives_inside_w33_as_its_octet_factors.py and
    the_27_factorisation_frames_carry_the_so10_weights.py (5419c27): the 27
    lines ARE present geometrically in W(3,3), as the 27 partitions of the
    points into five octets (complete factorisation frames), with the
    SRG(27,10,1,5) as "share an octet" and the full W(E6) acting.

WHAT IS COMPUTED, with G0 = Stab(p0) in PSp(4,3) (order 648) as permutations:
  1. G0 is transitive on the 27 bulk points AND on the 27 frames; the order-27
     elation group E (elements fixing every line through p0, of order 1 or 3)
     is regular on both.
  2. The subgroups of order 24 meeting E trivially -- the complements, each
     isomorphic to SL(2,3) -- are enumerated EXHAUSTIVELY (every SL(2,3) is
     generated by an element of order 4 and one of order 3): exactly 27 of
     them, in exactly THREE G0-conjugacy classes of 9.
  3. The bulk-point stabilisers form one class; the frame stabilisers form a
     DIFFERENT class. So under the substrate's own group the bulk 27 and the
     line 27 are NOT isomorphic G0-sets.
  4. The centre of G0 is the central elation group <z> of order 3, and the
     abelianisation of G0 is Z3 (it factors through SL(2,3)^ab). For the
     character chi : G0 -> Z3, the maps alpha_s(g) = g z^{s chi(g)} are
     automorphisms of G0, and they CYCLE the three complement classes:
         bulk class --alpha_1--> third class --alpha_1--> frame class.
  5. The whole stabiliser of p0 in Aut W(3,3) = W(E6) (order 1296, including
     the multiplier -1, antiunitary-type elements) FIXES each class. No element
     of the substrate's symmetry realises the twist.

THE READING.
  * Pass 371's permutation isomorphism exists, but it cannot be induced by the
    ambient W(E6): it must compose with a character twist alpha_s. Its
    uniqueness-of-module argument identifies the groups, not the complement
    classes.
  * Pass 372's "provably NOT geometric" holds for the bulk points. The E6 27 is
    geometric in W(3,3) -- as frames -- and what is not geometric is precisely
    the twist carrying one torsor to the other.
  * Pass 386's "the gap is the phase" becomes exact: the twist multiplies by
    the central qutrit phase z according to the SL(2,3) character.
  * The three torsors are indexed by the three one-dimensional characters of
    SL(2,3) = 2T. Under the McKay correspondence these are the three extremal
    nodes of the affine E6 diagram, permuted by its Z3 symmetry (the centre of
    E6). This is a structural parallel, recorded as such: W33-Theory Pass 90
    attached generations to the 2-dimensional representations instead, and
    no generation assignment is made here.

SCOPE.  Exact finite computation (exhaustive complement enumeration, exact
automorphism check on all of G0). No natural W(3,3) object was found realising
the third class among lines, hyperbolic lines, octets, spreads and frame pairs;
that negative is recorded with its search space. No physical identification.
"""

import argparse
import importlib.util
import itertools
import json
import os
from collections import Counter, deque

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
Q = 3


def frames_module():
    p = os.path.join(ROOT, "analysis", "the_27_factorisation_frames_carry_the_so10_weights.py")
    spec = importlib.util.spec_from_file_location("frames27", p)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    fm = frames_module()
    pts, idx, nm, n, tlines, octs, halves = fm.geometry()
    disj = [[not (octs[i] & octs[j]) for j in range(45)] for i in range(45)]
    frames = []

    def ext(cur, s):
        if len(cur) == 5:
            frames.append(tuple(cur))
            return
        for j in range(s, 45):
            if all(disj[j][i] for i in cur):
                ext(cur + [j], j + 1)
    ext([], 0)

    def sfv(u, v):
        return (u[0] * v[2] - u[2] * v[0] + u[1] * v[3] - u[3] * v[1]) % Q

    def mat_perm(M):
        return tuple(idx[nm(tuple(sum(M[r][c] * pts[p][c] for c in range(4)) % Q for r in range(4)))]
                     for p in range(n))

    def tv(v):
        return [[((1 if r == c else 0) + sfv(tuple(1 if k == c else 0 for k in range(4)), v) * v[r]) % Q
                 for c in range(4)] for r in range(4)]

    def comp(a, b):
        return tuple(a[b[i]] for i in range(n))

    I = tuple(range(n))

    def closure(gs, cap=None):
        H, dq = {I}, deque([I])
        while dq:
            x = dq.popleft()
            for g in gs:
                y = comp(g, x)
                if y not in H:
                    H.add(y)
                    dq.append(y)
                    if cap and len(H) > cap:
                        return None
        return frozenset(H)

    def inv(g):
        r = [0] * n
        for i, v in enumerate(g):
            r[v] = i
        return tuple(r)

    def order(g):
        k, h = 1, g
        while h != I:
            h = comp(g, h)
            k += 1
        return k

    gens = [mat_perm(tv(v)) for v in pts]
    G = closure(gens)
    SIM = mat_perm([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 2, 0], [0, 0, 0, 2]])
    Gfull = closure(gens + [SIM])
    octid = {O: i for i, O in enumerate(octs)}
    fidx = {tuple(sorted(f)): j for j, f in enumerate(frames)}

    def img_frame(g, j):
        return fidx[tuple(sorted(octid[frozenset(g[x] for x in octs[i])] for i in frames[j]))]

    p0 = 0
    bulk = [b for b in range(n) if sfv(pts[p0], pts[b]) != 0]
    G0 = [g for g in G if g[p0] == p0]
    G0full = [g for g in Gfull if g[p0] == p0]
    lines_p0 = [L for L in tlines if p0 in L]
    E = frozenset(g for g in G0 if all(frozenset(g[x] for x in L) == L for L in lines_p0) and order(g) in (1, 3))

    trans_bulk = len({g[bulk[0]] for g in G0}) == 27
    trans_frames = len({img_frame(g, 0) for g in G0}) == 27
    E_reg_bulk = len({g[bulk[0]] for g in E}) == 27
    E_reg_frames = len({img_frame(g, 0) for g in E}) == 27

    o4 = [g for g in G0 if order(g) == 4]
    o3 = [g for g in G0 if order(g) == 3 and g not in E]
    complements = set()
    for a in o4:
        for b in o3:
            H = closure([a, b], cap=24)
            if H is not None and len(H) == 24 and len(H & E) == 1:
                complements.add(H)

    def conj(g, H):
        gi = inv(g)
        return frozenset(comp(comp(g, h), gi) for h in H)
    classes = []
    for H in complements:
        if not any(H in c for c in classes):
            classes.append(frozenset(conj(g, H) for g in G0))
    class_of = {H: ci for ci, c in enumerate(classes) for H in c}

    bulk_stabs = {frozenset(g for g in G0 if g[b] == b) for b in bulk}
    frame_stabs = {frozenset(g for g in G0 if img_frame(g, j) == j) for j in range(27)}
    bulk_cls = {class_of.get(H) for H in bulk_stabs}
    frame_cls = {class_of.get(H) for H in frame_stabs}

    centre = [g for g in G0 if all(comp(g, h) == comp(h, g) for h in G0)]
    z = next(g for g in centre if order(g) == 3)
    comms = {comp(comp(inv(a), inv(b)), comp(a, b)) for a in G0 for b in G0[::9]}
    Dsub = closure(list(comms))
    g0 = next(g for g in G0 if g not in Dsub)
    powers = [I, g0, comp(g0, g0)]
    chi = {}
    for g in G0:
        chi[g] = next(k for k in range(3) if comp(inv(powers[k]), g) in Dsub)
    zp = [I, z, comp(z, z)]

    def alpha(g, s):
        return comp(g, zp[(s * chi[g]) % 3])
    alpha_is_aut = all(alpha(comp(a, b), 1) == comp(alpha(a, 1), alpha(b, 1)) for a in G0 for b in G0[::5]) \
        and len({alpha(g, 1) for g in G0}) == len(G0)
    Bst = next(iter(bulk_stabs))
    cyc = [class_of.get(frozenset(alpha(g, s) for g in Bst)) for s in (0, 1, 2)]

    full_fixes = all(class_of.get(conj(t, next(iter(c)))) == ci for ci, c in enumerate(classes)
                     for t in G0full[::37])

    print("THE TWO 27s DIFFER BY A CHARACTER TWIST")
    print("=" * 74)
    print("  |Stab(p0)| = %d, |Stab_W(E6)(p0)| = %d, elation group %d" % (len(G0), len(G0full), len(E)))
    print("  transitive on bulk / frames: %s / %s; elations regular on bulk / frames: %s / %s"
          % (trans_bulk, trans_frames, E_reg_bulk, E_reg_frames))
    print("  SL(2,3) complements of the elation group: %d, conjugacy classes %s"
          % (len(complements), [len(c) for c in classes]))
    print("  bulk-point stabilisers in class %s, frame stabilisers in class %s" % (bulk_cls, frame_cls))
    print("  centre order %d, commutator subgroup %d, abelianisation Z3; alpha_1 automorphism: %s"
          % (len(centre), len(Dsub), alpha_is_aut))
    print("  class of alpha_s(bulk stabiliser), s = 0, 1, 2: %s" % cyc)
    print("  W(E6)-stabiliser of p0 fixes every class: %s" % full_fixes)

    ok = (len(G0) == 648 and len(G0full) == 1296 and len(E) == 27 and trans_bulk and trans_frames
          and E_reg_bulk and E_reg_frames and len(complements) == 27 and sorted(len(c) for c in classes) == [9, 9, 9]
          and len(bulk_cls) == 1 and len(frame_cls) == 1 and bulk_cls != frame_cls
          and len(centre) == 3 and len(Dsub) == 216 and alpha_is_aut
          and len(set(cyc)) == 3 and cyc[0] == next(iter(bulk_cls)) and cyc[2] == next(iter(frame_cls))
          and full_fixes)
    print()
    print("VALID: %s" % ok)

    if args.write:
        assert ok, "checks failed -- refusing to write"
        rec = {
            "schema": "holotrade.two-27s-character-twist.v1",
            "valid": True,
            "stabiliserOrder": len(G0), "fullStabiliserOrder": len(G0full), "elationOrder": len(E),
            "transitiveOnBulkAndFrames": trans_bulk and trans_frames,
            "elationsRegularOnBoth": E_reg_bulk and E_reg_frames,
            "complements": len(complements), "complementClassSizes": sorted(len(c) for c in classes),
            "bulkAndFrameClassesDiffer": bulk_cls != frame_cls,
            "centreOrder": len(centre), "commutatorSubgroupOrder": len(Dsub),
            "characterTwistIsAutomorphism": alpha_is_aut,
            "twistCyclesClasses": len(set(cyc)) == 3,
            "twistTakesBulkToFramesAt": 2,
            "fullStabiliserFixesEveryClass": full_fixes,
            "priorArt": (
                "W33-Theory THE_27_FOLD_WAY.md and Passes 370-372, 386; Holotrade "
                "gq24_lives_inside_w33_as_its_octet_factors.py and 5419c27 (frames)."),
            "theorem": (
                "in Stab(p0) = 3^{1+2}:SL(2,3) the 27 SL(2,3) complements of the elation (qutrit Pauli) group fall "
                "into three conjugacy classes of 9; the bulk-point stabilisers and the frame (cubic-surface line) "
                "stabilisers lie in different classes; the automorphisms g -> g z^{s chi(g)}, chi the abelianisation "
                "character onto Z3 and z the central phase, cycle the three classes; the W(E6)-stabiliser of p0 fixes "
                "every class."),
            "reading": (
                "Pass 371's permutation isomorphism of the two 27s exists only through such a character twist and is "
                "not induced by W(E6); Pass 372's non-geometricity is a property of the bulk points, since the E6 27 "
                "is geometric as frames; Pass 386's phase gap is exactly the twist by the central qutrit phase. The "
                "three torsors are indexed by the one-dimensional characters of SL(2,3) = 2T, which McKay places at "
                "the three extremal nodes of affine E6 -- a structural parallel only; no generation assignment."),
            "boundary": (
                "exact finite computation with exhaustive complement enumeration; no natural W(3,3) object realising "
                "the third class was found among lines, hyperbolic lines, octets, spreads and frame pairs; no physical "
                "identification is made."),
        }
        pth = os.path.join(ROOT, "data", "two_27s_character_twist.json")
        with open(pth, "w", encoding="utf-8") as fh:
            json.dump(rec, fh, indent=2)
        print("written: %s" % pth)


if __name__ == "__main__":
    main()
