#!/usr/bin/env python3
"""
The section exists, is constructed here, and the eighty Gauss-sum lifts are
corrected onto it by an explicit Pauli each.

WHAT WAS LEFT.  bf6d67a settled that the eighty Gauss-sum lifts are NOT a
homomorphic section -- they generate Paulis -- and closed with "constructing a
corrected section, by adjusting each lift by a Pauli so the family closes, is
NOT attempted here". That is attempted here, and it works.

THE SECTION IS THE METAPLECTIC ONE.  The Gauss-sum lift was a natural but ad hoc
choice: a lift of T(v,lam) built inside the algebra of P_v itself. The classical
choice is different -- the Weil representation, generated by

    linear          |x> -> |Mx>              for M in GL(2,3)
    quadratic phase |x> -> w^{q(x)} |x>      for q a quadratic form
    Fourier         on either factor or both

Encoding each exactly as (S, phi) with U P_v U^dag = w^{phi(v)} P_{Sv} and
composing by (S1,phi1)(S2,phi2) = (S1 S2, phi2 + phi1 o S2) -- integer arithmetic
in F_3 throughout -- the group they generate is

    order 51,840 exactly,   Paulis inside: 0

which is |Sp(4,3)| with nothing over it. So these generators DO form a section,
and since it contains no Paulis the map S -> phi is a bijection: every symplectic
element has exactly one canonical phase function.

THE CORRECTION TABLE.  With the section in hand, each transvection T has a
canonical phase phi_canon = section[S_T]. The Gauss-sum lift has phi_gauss. The
difference is the phase of a Pauli, and solving

    phi_gauss(v) - phi_canon(v)  =  -<a, v>

for a in F_3^4 gives the correction: P_a U_gauss is the canonical lift. Every one
of the eighty is corrected this way, and the difference is verified to be linear
before a is extracted -- if it were not linear no Pauli would fix it and the
splitting would be in trouble.

WHY IT MATTERS.  The compiler's word now lifts with NO residual: emit the
transvections, take the corrected lift of each, and the product is exactly the
canonical Clifford of the target, not merely the target up to a Pauli. That is
the strong form of what d6bcf30 predicted from the splitting and 0fb6a0f could
not yet deliver.

SCOPE.  The section is constructed exactly and its order and Pauli count are
computed, not sampled. The Weil generators are the classical ones; that they
generate a section is verified here rather than cited. The corrections are
solved per transvection and each is checked to be a genuine Pauli phase. The
phases entering the encoding are read off numerically once, as cube roots of
unity to about 1e-15; everything after is integer. Only n = 2, q = 3. tau_2 is
untouched.
"""

import cmath
import collections
import itertools
import json
import os
import sys

import numpy as np

ROOT = r"C:\Repos\Holotrade"
P3 = 3
D = 4
W = cmath.exp(2j * cmath.pi / P3)


def main():
    X1 = np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]], dtype=complex)
    Z1 = np.diag([1, W, W ** 2]).astype(complex)

    def P(v):
        A = np.linalg.matrix_power(X1, v[0]) @ np.linalg.matrix_power(Z1, v[2])
        B = np.linalg.matrix_power(X1, v[1]) @ np.linalg.matrix_power(Z1, v[3])
        return np.kron(A, B)

    def form(u, v):
        return (u[0] * v[2] - u[2] * v[0] + u[1] * v[3] - u[3] * v[1]) % P3

    vecs = [v for v in itertools.product(range(P3), repeat=D) if any(v)]
    vi = {v: i for i, v in enumerate(vecs)}
    basis = [(a, b) for a in range(P3) for b in range(P3)]
    bi = {x: i for i, x in enumerate(basis)}

    def encode(U):
        Ud = U.conj().T
        img = {}
        for x in vecs:
            L = U @ P(x) @ Ud
            hit = None
            for y in vecs:
                R = P(y)
                i0 = int(np.argmax(np.abs(R) > 1e-9))
                z = L.flatten()[i0] / R.flatten()[i0]
                if np.allclose(L, z * R, atol=1e-7):
                    k = int(round((cmath.phase(z) % (2 * cmath.pi))
                                  / (2 * cmath.pi / P3))) % P3
                    hit = (y, k)
                    break
            if hit is None:
                return None
            img[x] = hit
        S = [[0] * D for _ in range(D)]
        for j in range(D):
            e = tuple(1 if k == j else 0 for k in range(D))
            for i in range(D):
                S[i][j] = img[e][0][i]
        return (tuple(map(tuple, S)), tuple(img[x][1] for x in vecs))

    # --- metaplectic generators
    gens = []
    for M in itertools.product(range(P3), repeat=4):
        if (M[0] * M[3] - M[1] * M[2]) % P3 == 0:
            continue
        U = np.zeros((9, 9), dtype=complex)
        for x in basis:
            y = ((M[0] * x[0] + M[1] * x[1]) % P3,
                 (M[2] * x[0] + M[3] * x[1]) % P3)
            U[bi[y], bi[x]] = 1
        gens.append(U)
    for a in range(P3):
        for b in range(P3):
            for c in range(P3):
                if a == b == c == 0:
                    continue
                gens.append(np.diag(
                    [W ** ((a * x[0] * x[0] + 2 * b * x[0] * x[1]
                            + c * x[1] * x[1]) % P3) for x in basis]
                ).astype(complex))
    F1 = np.array([[W ** (j * k) for k in range(P3)] for j in range(P3)],
                  dtype=complex) / np.sqrt(P3)
    I3 = np.eye(P3, dtype=complex)
    gens += [np.kron(F1, I3), np.kron(I3, F1), np.kron(F1, F1)]
    enc = [e for e in (encode(U) for U in gens) if e is not None]

    def apply(S, x):
        return tuple(sum(S[i][k] * x[k] for k in range(D)) % P3
                     for i in range(D))

    def mul(g1, g2):
        S1, f1 = g1
        S2, f2 = g2
        S = tuple(tuple(sum(S1[i][k] * S2[k][j] for k in range(D)) % P3
                        for j in range(D)) for i in range(D))
        return (S, tuple((f2[vi[x]] + f1[vi[apply(S2, x)]]) % P3 for x in vecs))

    IDS = tuple(tuple(1 if i == j else 0 for j in range(D)) for i in range(D))
    ID = (IDS, tuple([0] * len(vecs)))
    seen, fr = {ID}, [ID]
    while fr:
        nx = []
        for a in fr:
            for g in enc:
                b = mul(g, a)
                if b not in seen:
                    seen.add(b)
                    nx.append(b)
        fr = nx
    paulis = [g for g in seen if g[0] == IDS and any(g[1])]
    section = {S: f for S, f in seen}
    is_section = (len(seen) == 51840 and not paulis
                  and len(section) == len(seen))

    # --- correct the eighty Gauss-sum lifts onto the section
    def nm(v):
        i = next(k for k, x in enumerate(v) if x % P3)
        z = pow(v[i] % P3, -1, P3)
        return tuple((z * x) % P3 for x in v)

    def lift(v, lam):
        return sum((W ** ((lam * k * k) % P3))
                   * np.linalg.matrix_power(P(v), k)
                   for k in range(P3)) / np.sqrt(P3)

    table, nlin, nsolved = [], 0, 0
    for v in sorted({nm(x) for x in vecs}):
        for lam in (1, 2):
            e = encode(lift(v, lam))
            S, fg = e
            fc = section.get(S)
            d = tuple((fg[vi[x]] - fc[vi[x]]) % P3 for x in vecs)
            lin = all((d[vi[x]] + d[vi[y]]) % P3
                      == d[vi[tuple((x[k] + y[k]) % P3 for k in range(D))]]
                      for x in vecs for y in vecs
                      if any((x[k] + y[k]) % P3 for k in range(D)))
            nlin += lin
            a = None
            for cand in itertools.product(range(P3), repeat=D):
                if all(d[vi[x]] == (-form(cand, x)) % P3 for x in vecs):
                    a = cand
                    break
            nsolved += a is not None
            table.append({"v": list(v), "lam": lam,
                          "differenceIsLinear": bool(lin),
                          "pauliCorrection": list(a) if a else None})

    print("THE SECTION AND THE CORRECTION TABLE")
    print("=" * 72)
    print("  bf6d67a closed with 'constructing a corrected section ... is NOT")
    print("  attempted here'. Attempted here, and it works.")
    print()
    print("  metaplectic generators (linear, quadratic phase, Fourier): %d"
          % len(enc))
    print("  group generated, exact, mod global phase: %d" % len(seen))
    print("  |Sp(4,3)| = 51840 ; Paulis inside: %d" % len(paulis))
    print("  => THEY FORM A SECTION: %s" % is_section)
    print("     and with no Paulis, S -> phi is a bijection, so every")
    print("     symplectic element has exactly one canonical phase function.")
    print()
    print("  correcting the eighty Gauss-sum lifts onto it:")
    print("     difference phi_gauss - phi_canon is LINEAR   %d / 80" % nlin)
    print("     Pauli correction a solved from -<a,v>        %d / 80" % nsolved)
    print()
    print("  So P_a . U_gauss(v,lam) is the canonical lift, and the compiler's")
    print("  word now lifts with NO residual: the product of corrected lifts is")
    print("  exactly the canonical Clifford of the target, not merely the")
    print("  target up to a Pauli. That is the strong form d6bcf30 predicted")
    print("  from the splitting and 0fb6a0f could not yet deliver.")

    ok = (is_section and nlin == 80 and nsolved == 80 and len(enc) == 77)

    if "--write" in sys.argv:
        p = os.path.join(ROOT, "data", "section_and_correction_table.json")
        with open(p, "w") as fh:
            json.dump({
                "schema": "holotrade.section-and-correction-table.v1",
                "valid": bool(ok),
                "whatWasLeft": ("bf6d67a settled that the eighty Gauss-sum lifts "
                                "are NOT a section and closed with "
                                "'constructing a corrected section ... is NOT "
                                "attempted here'"),
                "theSection": {
                    "generators": ("linear |x> -> |Mx> for M in GL(2,3), "
                                   "quadratic phase |x> -> w^{q(x)}|x>, and "
                                   "Fourier on either factor or both"),
                    "generatorCount": len(enc),
                    "order": len(seen),
                    "spOrder": 51840,
                    "pauliCount": len(paulis),
                    "isASection": bool(is_section),
                    "consequence": ("with no Paulis the map S -> phi is a "
                                    "bijection, so every symplectic element has "
                                    "exactly one canonical phase function"),
                    "verifiedNotCited": True,
                },
                "correction": {
                    "differenceIsLinear": nlin,
                    "pauliSolved": nsolved,
                    "outOf": 80,
                    "method": ("phi_gauss(v) - phi_canon(v) = -<a,v> solved for "
                               "a in F_3^4; linearity is checked BEFORE a is "
                               "extracted, since if the difference were not "
                               "linear no Pauli would fix it"),
                },
                "whyItMatters": ("the compiler's word now lifts with NO "
                                 "residual: emit the transvections, take the "
                                 "corrected lift of each, and the product is "
                                 "exactly the canonical Clifford of the target, "
                                 "not merely the target up to a Pauli -- the "
                                 "strong form d6bcf30 predicted from the "
                                 "splitting and 0fb6a0f could not yet deliver"),
                "table": table,
                "boundary": ("the section is constructed exactly and its order "
                             "and Pauli count are computed, not sampled; that "
                             "the classical Weil generators give a section is "
                             "VERIFIED here rather than cited. Corrections are "
                             "solved per transvection and each checked to be a "
                             "genuine Pauli phase. The phases entering the "
                             "encoding are read off numerically once, as cube "
                             "roots of unity to about 1e-15; everything after "
                             "is integer. Only n = 2, q = 3. tau_2 is untouched"),
            }, fh, indent=2)
        print("\n  written: %s  (%d-entry table)"
              % (os.path.relpath(p, ROOT), len(table)))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
