#!/usr/bin/env python3
"""
The nine minimum blockers at a point of W(3,3) drop nine pencil transversals,
and those nine words are the TETRACODE. A bridge to the other track, which has
a hundred files of tetracode machinery and none of them about blocking.

WHERE THIS STARTS.  the_blocker_triples_are_the_small_orbit.py (4a45d15) shows
a minimum blocker B with centre c keeps eight of the twelve neighbours of c,
dropping a transversal of the pencil at c -- one point on each of the four
lines through c. the_minimum_blocker_labels_are_octets.py (aa42b38, 6f35762)
supplies the count: nine blockers per centre, 360 = 40 x 9 in all. So each
centre carries NINE transversals of a 4 x 3 grid, out of 3^4 = 81 available.
Which nine was never asked.

THE MEASUREMENT THAT FORCED THE QUESTION.  Over all C(360,2) = 64620 pairs of
minimum blockers, |B n B'| takes the values

    0    1    2    3    4    5    6    8
 4320 8640 18540 8640 12960 1440 8640 1440

and the value 5 occurs 1440 times -- which is exactly 40 x C(9,2), the number
of SAME-CENTRE pairs. Sorting by centre confirms it: same-centre pairs give 5
every single time with no spread at all, and 5 never occurs across centres (nor
does 7). So |B n B'| = 5 is a test for sharing a centre.

WHY THAT IS A CODING STATEMENT.  Two blockers at the same centre have disjoint
far triples, since the nine far triples partition the 27 far points, so the
whole intersection lives in the near part. Each near part is the twelve
neighbours minus a four-point transversal, so

    |B n B'| = 12 - |drop u drop'| = 4 + |drop n drop'|.

The measured constant 5 therefore says |drop n drop'| = 1 for every pair: any
two of the nine transversals agree in EXACTLY ONE of the four positions. Label
the three non-c points of each pencil line by F_3 and a transversal becomes a
word in F_3^4. Nine words, length four, pairwise Hamming distance exactly three.

THAT CODE IS THE TETRACODE.  A (4, 9, 3) code over an alphabet of size 3 meets
the Singleton bound, so it is MDS, equivalently an orthogonal array OA(9,4,3,2)
-- verified here: every pair of coordinates sees all nine symbol pairs. Such a
code is unique up to monomial equivalence, and after relabelling symbols within
each position the nine words form a LINEAR [4,2,3]_3 code which is SELF-DUAL.
The self-dual [4,2,3]_3 code is the tetracode. Checked at all 40 centres; and
PSp(4,3) is transitive on the 40 points, so one centre would have sufficed.

At centre 0 the words come out linear on the nose, generated by (0,1,1,1) and
(1,0,1,2):

    0000  0111  0222  1012  1120  1201  2021  2102  2210

CROSS-TRACK, WHICH IS THE POINT.  The tetracode appears in 102 files of the
W33-Theory track -- the BT1837 quotient hunt, the BT930 isometry matrix, the E8
selector aperture tables -- and in ZERO files of this one. Not one of those 102
mentions blockers, blocking sets or pencils. This is the join: the object that
track uses to organise E8 selector data is sitting inside the minimum blockers
of W(3,3), one copy per point, and the copy is canonical because the nine
blockers at a centre are canonical.

WHAT IS AND IS NOT CLAIMED.  The classification of the 360, the count nine per
centre, and the 45 octets are all prior work and are cited, not re-derived. The
uniqueness of a (4,9,3)_3 MDS code and its identification with the tetracode
are classical coding theory. What is new is the identification itself, the
intersection census that produced it, and the fact that |B n B'| = 5
characterises a shared centre. Searched the literature on codes and blocking
sets in generalised quadrangles and found no statement of it; that is a
negative search over a space that is large, so it is reported as such and not
as proof of novelty.

SCOPE.  Exhaustive: all 360 blockers, all 64620 pairs, all 40 centres. tau_2 is
untouched and stays open in [111, 115].
"""

import argparse
import collections
import itertools
import json
import os

Q = 3
N = 40
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def geometry():
    def nm(v):
        i = next(k for k, x in enumerate(v) if x % Q)
        z = pow(v[i] % Q, -1, Q)
        return tuple((z * x) % Q for x in v)

    def form(u, v):
        return (u[0] * v[1] - u[1] * v[0] + u[2] * v[3] - u[3] * v[2]) % Q

    pts = sorted({nm(v) for v in itertools.product(range(Q), repeat=4) if any(v)})
    idx = {v: i for i, v in enumerate(pts)}
    lines = set()
    for a, b in itertools.combinations(range(N), 2):
        if form(pts[a], pts[b]):
            continue
        S = set()
        for x in range(Q):
            for y in range(Q):
                if x or y:
                    S.add(idx[nm(tuple((x * pts[a][k] + y * pts[b][k]) % Q
                                       for k in range(4)))])
        if len(S) == 4:
            lines.add(tuple(sorted(S)))
    lines = sorted(lines)
    thru = [[i for i, L in enumerate(lines) if p in L] for p in range(N)]
    return lines, thru


def blockers_at(c, lines, thru):
    """The nine minimum blockers at c, each as (set, dropped transversal word).

    Uses the foot-collapse selector of the_blocker_triples_are_the_small_orbit.
    """
    perp = {y for i in thru[c] for y in lines[i]}
    far = sorted(set(range(N)) - perp)
    pencil = [[p for p in lines[i] if p != c] for i in thru[c]]
    pos = {p: (k, s) for k, L in enumerate(pencil) for s, p in enumerate(L)}
    edges = set()
    for L in lines:
        for x in itertools.combinations(sorted(set(L) & set(far)), 2):
            edges.add(frozenset(x))
    out = []
    for T in itertools.combinations(far, 3):
        if any(frozenset(x) in edges for x in itertools.combinations(T, 2)):
            continue
        feet = collections.Counter()
        for i in {i for p in T for i in thru[p]}:
            feet[[y for y in lines[i] if y in perp][0]] += 1
        if sorted(feet.values()) != [3, 3, 3, 3]:
            continue
        word = [None] * 4
        for x in feet:
            k, s = pos[x]
            word[k] = s
        near = [p for L in pencil for p in L if p not in set(feet)]
        B = frozenset(near) | frozenset(T)
        assert len(B) == 11 and all(B & set(L) for L in lines)
        out.append((B, tuple(word)))
    return out


def tetracode_form(words):
    """Relabel symbols within each position to make the code linear; test
    self-duality. Returns (linear, selfdual, the linear code)."""
    for origin in words:
        sh = [tuple((w[k] - origin[k]) % Q for k in range(4)) for w in words]
        for perm in itertools.product(itertools.permutations(range(Q)), repeat=4):
            if any(p[0] != 0 for p in perm):        # relabelling must fix 0
                continue
            C = {tuple(perm[k][w[k]] for k in range(4)) for w in sh}
            if len(C) != 9:
                continue
            if not all(tuple((x[k] + y[k]) % Q for k in range(4)) in C
                       for x in C for y in C):
                continue
            sd = all(sum(a[k] * b[k] for k in range(4)) % Q == 0
                     for a in C for b in C)
            return True, sd, sorted(C)
    return False, False, None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    lines, thru = geometry()
    per_centre = {c: blockers_at(c, lines, thru) for c in range(N)}
    allB = [(c, B) for c in range(N) for B, _ in per_centre[c]]
    assert len(allB) == 360 and len({B for _, B in allB}) == 360

    same, diff = collections.Counter(), collections.Counter()
    for i in range(len(allB)):
        ci, Bi = allB[i]
        for j in range(i + 1, len(allB)):
            cj, Bj = allB[j]
            (same if ci == cj else diff)[len(Bi & Bj)] += 1
    total = same + diff

    rows = []
    for c in range(N):
        w = [word for _, word in per_centre[c]]
        d = collections.Counter(sum(1 for x, y in zip(a, b) if x != y)
                                for a, b in itertools.combinations(w, 2))
        oa = all(len({(x[i], x[j]) for x in w}) == 9
                 for i, j in itertools.combinations(range(4), 2))
        lin, sd, C = tetracode_form(w)
        rows.append((len(w) == 9, set(d) == {3}, oa, lin, sd))
        if c == 0:
            first_words, first_code = sorted(w), C

    cols = list(zip(*rows))
    tetra = all(all(x) for x in cols)

    print("W(3,3): 360 minimum blockers, 40 centres, 9 each")
    print()
    print("PAIRWISE INTERSECTIONS over all %d pairs" % sum(total.values()))
    print("   size :  " + "".join("%7d" % k for k in sorted(total)))
    print("  pairs :  " + "".join("%7d" % total[k] for k in sorted(total)))
    print("   same :  " + "".join("%7d" % same.get(k, 0) for k in sorted(total)))
    print("   diff :  " + "".join("%7d" % diff.get(k, 0) for k in sorted(total)))
    print("  same-centre is ALWAYS 5: %s   (5 never occurs across centres: %s)"
          % (set(same) == {5}, 5 not in diff))
    print("  so |B n B'| = 5 detects a shared centre.")
    print()
    print("THE NINE TRANSVERSALS AT A CENTRE")
    print("  |B n B'| = 4 + |drop n drop'|, so 5 means the transversals agree")
    print("  in exactly one position -- nine words of length 4 over F_3 at")
    print("  pairwise Hamming distance 3.")
    print("  centre 0 words: " + "  ".join("".join(map(str, w))
                                           for w in first_words))
    print("  nine words, all distances 3   : %s" % all(cols[1]))
    print("  strength-2 orthogonal array   : %s" % all(cols[2]))
    print("  linear after symbol relabel   : %s" % all(cols[3]))
    print("  and SELF-DUAL [4,2,3]_3       : %s" % all(cols[4]))
    print("  a self-dual [4,2,3]_3 code is the TETRACODE, at all 40 centres.")
    print()
    print("VALID: %s" % tetra)

    if args.write:
        assert tetra, "checks failed -- refusing to write"
        rec = {
            "schema": "holotrade.blocker-transversals-tetracode.v1",
            "valid": True,
            "minimumBlockers": 360,
            "centres": N,
            "blockersPerCentre": 9,
            "pairsExamined": sum(total.values()),
            "intersectionCensus": {str(k): total[k] for k in sorted(total)},
            "sameCentreIntersections": {str(k): same[k] for k in sorted(same)},
            "diffCentreIntersections": {str(k): diff[k] for k in sorted(diff)},
            "sameCentreIsAlwaysFive": True,
            "fiveNeverOccursAcrossCentres": True,
            "sevenNeverOccurs": 7 not in total,
            "centreZeroWords": ["".join(map(str, w)) for w in first_words],
            "centreZeroLinearCode": ["".join(map(str, w)) for w in first_code],
            "allDistancesThree": True,
            "strengthTwoOrthogonalArray": True,
            "linearAfterRelabel": True,
            "selfDual": True,
            "isTheTetracode": True,
            "theResult": (
                "at every point c of W(3,3) the nine minimum blockers with "
                "centre c drop nine transversals of the pencil at c, and those "
                "nine words -- length four over F_3, one symbol per pencil line "
                "-- have pairwise Hamming distance exactly three. That makes "
                "them a (4,9,3) MDS code, equivalently an OA(9,4,3,2), and after "
                "relabelling symbols within each position the code is linear and "
                "SELF-DUAL. The self-dual [4,2,3]_3 code is the tetracode. So "
                "each of the 40 points of W(3,3) carries a canonical copy of the "
                "tetracode, canonical because the nine blockers at a centre are."),
            "howItWasFound": (
                "not by looking for it. The pairwise intersection census over "
                "all 64620 pairs of minimum blockers showed |B n B'| = 5 exactly "
                "1440 times = 40 x C(9,2), and sorting by centre showed the "
                "same-centre pairs give 5 with no spread whatever. Since "
                "same-centre far triples are disjoint, |B n B'| = 4 + |drop n "
                "drop'|, so the constant 5 says any two transversals agree in "
                "exactly one position -- a distance-3 condition, i.e. a code."),
            "sharedCentreIsDetectable": (
                "|B n B'| = 5 holds for every same-centre pair and for no other "
                "pair; 7 does not occur at all. Across centres the values are 0, "
                "1, 2, 3, 4, 6, 8. So the intersection size alone decides whether "
                "two minimum blockers share a centre."),
            "crossTrack": (
                "the tetracode appears in 102 files of the W33-Theory track -- "
                "bt1837_tetracode_quotient_hunt.py, the BT930 isometry matrix, "
                "the BT1836 E8 selector aperture table -- and in zero files of "
                "this track. None of those 102 mentions blockers, blocking sets "
                "or pencils. This is the join between the two tracks and the "
                "citation goes to them for the tetracode machinery."),
            "priorArtCited": (
                "the classification of the 360 as (c,T) and the forced 8+3 split "
                "come from every_minimum_blocker_is_a_point_and_a_triple.py; the "
                "count nine per centre and the 45 octets from "
                "the_minimum_blocker_labels_are_octets.py (aa42b38, 6f35762), "
                "where nine = q^2 is the row weight of B in N D = J + q B; the "
                "foot-collapse selector used to build the blockers here from "
                "the_blocker_triples_are_the_small_orbit.py (4a45d15). "
                "Uniqueness of a (4,9,3)_3 MDS code and its identification with "
                "the tetracode are classical coding theory, not a claim of this "
                "file."),
            "boundary": (
                "exhaustive: all 360 blockers, all 64620 pairs, all 40 centres, "
                "with the tetracode test run per centre rather than transported "
                "by the group -- though PSp(4,3) is transitive on the 40 points "
                "so one centre would have sufficed. The relabelling search is "
                "complete over the 6^4 symbol relabellings that fix 0, times all "
                "nine choices of origin. Searched the literature on codes and "
                "blocking sets in generalised quadrangles and found no statement "
                "of this identification; that is a negative search over a large "
                "space and is not proof of novelty. tau_2 is untouched and stays "
                "open in [111, 115]."),
        }
        p = os.path.join(ROOT, "data", "blocker_transversals_tetracode.json")
        with open(p, "w", encoding="utf-8") as fh:
            json.dump(rec, fh, indent=2)
        print("written: %s" % p)


if __name__ == "__main__":
    main()
