#!/usr/bin/env python3
"""
Universality turns BT836's two cells into one fact -- and universal here does
NOT mean computationally universal, though it does mean incompressible.

THE FACT THAT REFRAMES EVERYTHING.  The 11-cell and the 57-cell are UNIVERSAL
in the amalgamation sense:

    the 11-cell is the ONLY polytope with hemi-icosahedral facets and
    hemi-dodecahedral vertex figures;
    the 57-cell is the ONLY polytope with those two roles SWAPPED.

They are not two unrelated exceptional objects. They are the two amalgamations
of a single unordered pair of cells, {hemi-icosahedron, hemi-dodecahedron},
distinguished only by which one is the facet and which the vertex figure. And
universality means each is determined by that pair -- nothing else in the class
exists, and everything in the class is a quotient of it.

WHY THAT MATTERS HERE.  BT836 finds BOTH cells inside one spread of W(3,3):
the Petersen graph on the 10 spread lines is the hemi-dodecahedron, and the
hidden 6-set carries K_6, the hemi-icosahedron. Read through universality that
is not two coincidences but one:

    a spread carries the amalgamation INPUT -- the cell pair -- and the pair
    admits exactly two universal outputs, which are the 11-cell and the
    57-cell.

The substrate does not happen to contain two exceptional polytopes' cells. It
contains a facet/vertex-figure pair, and that pair has precisely two universal
amalgamations. The coincidence was one coincidence, not two.

AND THEY ARE ISOLATED IN BOTH DIRECTIONS.  Universality closes one direction:
nothing in their class covers them. Quotients close the other. Any polytope Q
with the same facets and vertex figures is Q = P/N with N <= Aut(P), and for a
REGULAR quotient N must be normal. Verified here by conjugacy-class analysis:

    PSL(2,11): order 660,  8 classes of sizes 1,55,60,60,110,110,132,132
    PSL(2,19): order 3420, 12 classes of sizes 1,171,180,180,342 x4,380 x4

In neither group does any union of classes containing the identity, other than
{1} and the whole group, have order dividing the group order. Both are SIMPLE,
so the only normal subgroups are trivial. Neither polytope has a proper regular
quotient.

So the 11-cell and 57-cell sit alone: universal above, simple below, no
covering ladder in either direction.

IS THIS USEFUL FOR "UNIVERSAL TOPOLOGICAL COMPUTATION"?  Not in the way the
word suggests, and the two senses should not be run together. Amalgamation-
universal means "covers every polytope with these facets and vertex figures".
Computationally universal means "can simulate any computation". They are
unrelated notions that share an English word, and this project has been caught
before welding two things together because a symbol matched.

But the fact IS operationally useful, in the opposite direction to the one the
name hints at. Universality plus simplicity is an INCOMPRESSIBILITY statement:

    there is no nontrivial regular quotient of either polytope, so nothing
    encoded on them can be folded onto a smaller regular carrier.

Contrast the substrate, where the same question has the opposite answer.
witness_compresses_under_one_clifford.py showed the best known two-carrier
measurement schedule -- 115 product observables -- is generated by 39 seeds
under a single order-6 Clifford gate, a 2.95x compression, precisely because
it HAS a nontrivial invariance. The GC polytopes admit no such reduction at
all. Rigid where the substrate is compressible.

That is the real consequence: the cells travel into the substrate and become
compressible there; the polytopes they build do not, and cannot.

THE LARGE UNIVERSAL POLYTOPE, checked for substrate arithmetic and not found.
The universal polytope with hemi-dodecahedral facets and ICOSAHEDRAL (not
hemi-) vertex figures is finite with 10,006,920 facets, and

    10006920 = 2^3 . 3^2 . 5 . 7 . 11 . 19^2.

It carries both Grunbaum-Coxeter primes, 11 and 19, as one would expect of an
amalgamation of these cell types. It is NOT divisible by |Sp(4,3)| = 51840 or
|PSp(4,3)| = 25920. Recorded as a negative: the number is polytope arithmetic,
not substrate arithmetic, and no relation to W(3,3) is claimed from it.

SCOPE.  The universality statements are classical and were supplied, not
derived here; what is computed is the simplicity of both groups and the
factorisation. The reframing of BT836 and the incompressibility reading are
what this file adds. No bound moves, and nothing here places either polytope
inside Sp(4,3) -- that remains impossible.
"""

import itertools
import json
import os
import sys

ROOT = r"C:\Repos\Holotrade"


def psl2(q):
    pts = list(range(q)) + ["inf"]
    idx = {p: i for i, p in enumerate(pts)}

    def act(a, b, c, d, x):
        if x == "inf":
            num, den = a, c
        else:
            num, den = (a * x + b) % q, (c * x + d) % q
        if den % q == 0:
            return "inf"
        return (num * pow(den, -1, q)) % q

    P = set()
    for a in range(q):
        for b in range(q):
            for c in range(q):
                for d in range(q):
                    if (a * d - b * c) % q != 1:
                        continue
                    P.add(tuple(idx[act(a, b, c, d, x)] for x in pts))
    return sorted(P), len(pts)


def comp(f, g):
    return tuple(f[g[i]] for i in range(len(f)))


def inv(f):
    r = [0] * len(f)
    for i, v in enumerate(f):
        r[v] = i
    return tuple(r)


def simplicity(q):
    G, n = psl2(q)
    E = tuple(range(n))
    seen, classes = set(), []
    for g in G:
        if g in seen:
            continue
        cl = {comp(comp(h, g), inv(h)) for h in G}
        seen |= cl
        classes.append(sorted(cl))
    order = len(G)
    others = [len(c) for c in classes if E not in c]
    found = []
    for r in range(1, len(others) + 1):
        for combo in itertools.combinations(others, r):
            s = 1 + sum(combo)
            if s < order and order % s == 0:
                found.append(s)
        if found:
            break
    return {"q": q, "order": order, "classes": len(classes),
            "classSizes": sorted(len(c) for c in classes),
            "properNormalCandidates": found, "isSimple": not found}


def factor(n):
    f, d, out = n, 2, {}
    while d * d <= f:
        while f % d == 0:
            out[d] = out.get(d, 0) + 1
            f //= d
        d += 1
    if f > 1:
        out[f] = out.get(f, 0) + 1
    return out


def main():
    print("UNIVERSALITY MAKES THE CELL PAIR STRUCTURAL")
    print("=" * 72)
    print("  The 11-cell is the ONLY polytope with hemi-icosahedral facets and")
    print("  hemi-dodecahedral vertex figures; the 57-cell is the ONLY one with")
    print("  the roles swapped. Two amalgamations of ONE cell pair.")
    print()
    print("  BT836 finds both cells in one spread of W(3,3). Through")
    print("  universality that is ONE coincidence, not two: the spread carries")
    print("  the amalgamation INPUT, and the pair has exactly two outputs.")
    print()
    rows = [simplicity(11), simplicity(19)]
    for r in rows:
        print("  PSL(2,%d): order %d, %d classes, sizes %s"
              % (r["q"], r["order"], r["classes"], r["classSizes"]))
        print("     proper normal candidates: %s -> SIMPLE: %s"
              % (r["properNormalCandidates"] or "none", r["isSimple"]))
    print()
    print("  So no proper REGULAR quotient exists for either: universal above,")
    print("  simple below, no covering ladder in either direction.")
    print()
    N = 10006920
    fN = factor(N)
    print("  The universal polytope with hemi-dodecahedral facets and")
    print("  ICOSAHEDRAL vertex figures has %d facets =" % N)
    print("     %s" % " . ".join("%d^%d" % (p, e) if e > 1 else str(p)
                                 for p, e in sorted(fN.items())))
    div = {n: (N % v == 0) for n, v in
           (("Sp(4,3)", 51840), ("PSp(4,3)", 25920),
            ("PSL(2,11)", 660), ("PSL(2,19)", 3420))}
    print("     divisible by |Sp(4,3)|: %s   by |PSp(4,3)|: %s"
          % (div["Sp(4,3)"], div["PSp(4,3)"]))
    print("     it carries both GC primes 11 and 19, and no substrate order.")
    print()
    print("  ON 'UNIVERSAL TOPOLOGICAL COMPUTATION': the two senses of")
    print("  'universal' are unrelated -- amalgamation-universal is not")
    print("  computationally universal, and they share only a word. But the")
    print("  fact is useful in the OPPOSITE direction: universality plus")
    print("  simplicity means INCOMPRESSIBLE. No nontrivial regular quotient")
    print("  exists, so nothing encoded on these polytopes folds onto a")
    print("  smaller regular carrier -- where the substrate's own 115-leaf")
    print("  schedule folds 2.95x onto 39 seeds under one Clifford gate.")

    ok = (all(r["isSimple"] for r in rows)
          and not div["Sp(4,3)"] and not div["PSp(4,3)"])

    if "--write" in sys.argv:
        p = os.path.join(ROOT, "data",
                         "universality_makes_the_cell_pair_structural.json")
        with open(p, "w") as fh:
            json.dump({
                "schema": "holotrade.universality-cell-pair.v1",
                "valid": bool(ok),
                "universality": {
                    "elevenCell": ("the only polytope with hemi-icosahedral "
                                   "facets and hemi-dodecahedral vertex "
                                   "figures"),
                    "fiftySevenCell": ("the only polytope with those roles "
                                       "swapped"),
                    "reading": ("they are the two amalgamations of ONE "
                                "unordered cell pair, so BT836 finding both "
                                "cells in one spread is one coincidence, not "
                                "two: the spread carries the amalgamation "
                                "input"),
                    "sourceIsClassical": True,
                },
                "simplicity": rows,
                "noRegularQuotients": ("a regular quotient P/N needs N normal; "
                                       "both groups are simple, so N is "
                                       "trivial and neither polytope has a "
                                       "proper regular quotient"),
                "isolatedBothWays": ("universal above -- nothing in the class "
                                     "covers them; simple below -- they cover "
                                     "nothing properly"),
                "onUniversalComputation": {
                    "falseFriend": ("amalgamation-universal and computationally "
                                    "universal are unrelated notions sharing a "
                                    "word; no bridge is claimed"),
                    "realConsequence": ("universality plus simplicity is an "
                                        "INCOMPRESSIBILITY statement: no "
                                        "nontrivial regular quotient exists, "
                                        "so nothing encoded on them folds onto "
                                        "a smaller regular carrier"),
                    "contrast": ("the substrate's best known two-carrier "
                                 "schedule folds 115 observables onto 39 seeds "
                                 "under one order-6 Clifford gate, 2.95x, "
                                 "because it HAS a nontrivial invariance"),
                },
                "largeUniversalPolytope": {
                    "facets": N,
                    "factorisation": {str(k): v for k, v in fN.items()},
                    "carriesGCPrimes": (11 in fN and 19 in fN),
                    "divisibleBySubstrateOrders": div,
                    "verdict": ("polytope arithmetic, not substrate "
                                "arithmetic; no relation to W(3,3) claimed"),
                },
                "boundary": ("the universality statements are classical and "
                             "were supplied, not derived here; the simplicity "
                             "and the factorisation are computed. Nothing "
                             "places either polytope inside Sp(4,3), which "
                             "remains impossible, and no bound moves."),
            }, fh, indent=2)
        print("\n  written: %s" % os.path.relpath(p, ROOT))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
