#!/usr/bin/env python3
"""Structural form of the flagship mu/exotic vacuum obstruction.

Let M be the hypergraph of singlet supports of allowed mu monomials and D the
hypergraph of singlet supports of allowed d/bd mass monomials.  For an active
VEV set T, a squarefree support monomial contributes iff its support is a subset
of T.

The following are equivalent:
  (A) every T that suppresses all mu monomials suppresses every d/bd monomial;
  (B) for every D_j in D there exists M_i in M with M_i subset D_j;
  (C) the squarefree monomial ideal I_d is contained in I_mu.

Proof A=>B: take T=D_j.  If D_j contained no mu support, T would be mu-free
while its own d monomial survives, contradicting A.
Proof B=>A: if some d monomial D_j survived in T, then its contained M_i would
also survive, contradicting mu suppression.
B<=>C is exactly monomial divisibility.

The committed aggregate certificate reports A for the flagship through total
order five, so B and C follow exactly from that measured premise.  The raw
64/144 support hyperedges are not committed, so this file does NOT claim an
independent empirical verification of B; it turns the reported exhaustive
Boolean result into the compact structural theorem that the missing raw data
should eventually verify directly.
"""
from __future__ import annotations
import itertools, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/w33_mu_exotic_monomial_ideal_containment.json'

def all_nonempty_subsets(n):
    return [frozenset(i for i in range(n) if (mask>>i)&1)
            for mask in range(1,1<<n)]

def no_go(M,D,n):
    for mask in range(1<<n):
        T=frozenset(i for i in range(n) if (mask>>i)&1)
        mu_off=all(not m.issubset(T) for m in M)
        if mu_off and any(d.issubset(T) for d in D):
            return False
    return True

def containment(M,D):
    return all(any(m.issubset(d) for m in M) for d in D)

def exhaustive_equivalence_control(n=3):
    edges=all_nonempty_subsets(n)
    hgs=[]
    for mask in range(1<<len(edges)):
        hgs.append([edges[i] for i in range(len(edges)) if (mask>>i)&1])
    checked=0
    for M in hgs:
        for D in hgs:
            assert no_go(M,D,n)==containment(M,D)
            checked+=1
    return checked

def main(write=True):
    parent=json.loads((ROOT/'data/w33_no_vacuum_suppresses_mu.json').read_text())
    measured=parent['measured']
    assert measured['mu_killing_subsets_examined']==26273
    assert measured['best_d_bd_rank_with_mu_off']==0
    assert measured['singlet_sets_are_equal'] is True
    controls=exhaustive_equivalence_control(3)
    assert controls==16384

    out={
      'schema':'holotrade.w33_mu_exotic_monomial_ideal_containment.v1',
      'status':'PASS_STRUCTURAL_DEDUCTION_FROM_MEASURED_PREMISE',
      'headline':'The reported order<=5 flagship vacuum no-go is equivalent to a compact hypergraph/monomial-ideal statement: every d/bd singlet-support hyperedge contains at least one mu-support hyperedge. Equivalently I_d is contained in I_mu, so the mu-suppressed squarefree-VEV locus V(I_mu) lies inside the d-mass-vanishing locus V(I_d).',
      'measured_premise':{
        'model':measured['model'],
        'max_total_order':measured['max_total_order'],
        'mu_couplings':measured['mu']['couplings'],
        'd_bd_couplings':measured['d_bd']['couplings'],
        'common_singlet_count':measured['mu']['singlets'],
        'mu_killing_subsets_examined':measured['mu_killing_subsets_examined'],
        'best_d_bd_rank_with_mu_off':measured['best_d_bd_rank_with_mu_off']
      },
      'equivalent_forms':{
        'vacuum':'for every active set T: if no mu support is contained in T, then no d/bd support is contained in T',
        'hypergraph':'for every d/bd support D_j there exists a mu support M_i with M_i subset D_j',
        'monomial_ideal':'I_d subset I_mu',
        'variety':'V(I_mu) subset V(I_d)'
      },
      'proof':{
        'A_implies_B':'take T=D_j; if D_j contained no mu support, T would be mu-free while D_j survives',
        'B_implies_A':'a surviving D_j contains a surviving M_i, contradicting mu suppression',
        'B_iff_C':'a squarefree monomial x^D belongs to the monomial ideal generated by x^M exactly when some M is a subset of D'
      },
      'generic_control':{
        'universe_size':3,
        'nonempty_supports':7,
        'hypergraphs':128,
        'ordered_hypergraph_pairs_checked':controls,
        'equivalence_failures':0
      },
      'physics_reading':'At support level the d-type exotic mass operators are algebraically downstream of the mu-generating support ideal: any Boolean VEV choice that zeros the mu generators also zeros every tested d/bd generator. Higher-order operators can escape only by adding support monomials not divisible by the measured mu generators.',
      'reproducibility_boundary':{
        'raw_64_mu_supports_committed':False,
        'raw_144_dbd_supports_committed':False,
        'empirical_containment_directly_replayed_here':False,
        'exact_part':'the equivalence theorem and its deduction from the committed aggregate premise',
        'next_required_artifact':'raw orbifolder coupling support export; then the no-go reduces to 144 direct subset/divisibility checks instead of a 2^19 vacuum scan'
      },
      'sources':['data/w33_no_vacuum_suppresses_mu.json','analysis/no_vacuum_suppresses_mu_without_losing_the_exotics.py'],
    }
    if write: OUT.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps(out,indent=2))
    return out

if __name__=='__main__': main(True)
