#!/usr/bin/env node
"use strict";

const crypto=require("node:crypto");
const fs=require("node:fs");
const path=require("node:path");
const {runGap}=require("../scripts/run-gap.js");
const {canonical}=require("./w33_five_front_breakthrough.js");

const ROOT=path.resolve(__dirname,"..");
const GAP_FILE=path.join(__dirname,"w33_f20_payne_five_state_atlas.g");
const GAP_INPUT=path.join(__dirname,"w33_f20_payne_five_state_input.g");
const OUT=path.join(ROOT,"data","w33_f20_payne_five_state_atlas.json");
const ROM_PATH="data/the_45_slot_rom_bijection.json";
const PAYNE_PATH="data/slow_path_is_payne_derivative.json";
const F20_PATH="data/w33_f20_qutrit_block_bridge.json";

function shaFile(file){return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");}
function oneBased(values){return values.map((value)=>Array.isArray(value)?oneBased(value):value+1);}
function gapAssignment(name,value){return `${name} := ${JSON.stringify(value)};;\n`;}
function renderInput(rom,payne,f20){
  const covers=Array.from({length:40},(_,axis)=>payne.equivariant40.covers[String(axis)]);
  const fibre=f20.fibreProductF20;
  const address=f20.cyclicQutritBlock.addressedPauliAction;
  return "# Generated by analysis/w33_f20_payne_five_state_atlas.js.\n"+
    "# GAP owns the group/action computation; this file only adapts committed JSON\n"+
    "# tables to one-based GAP lists.\n"+
    gapAssignment("GQLinesA",oneBased(rom.linesA))+
    gapAssignment("GQLinesB",oneBased(rom.linesB))+
    gapAssignment("PayneCovers",oneBased(covers))+
    gapAssignment("W33RawT",oneBased(fibre.order5GeneratorOnW33Points))+
    gapAssignment("W33RawM",oneBased(fibre.order4GeneratorOnW33Points))+
    gapAssignment("AddressT",oneBased(address.translation))+
    gapAssignment("AddressM",oneBased(address.multiplier));
}
function markerRow(stdout,marker){
  const at=stdout.indexOf(`${marker}|`);
  if(at<0)throw new Error(`GAP output missed ${marker}`);
  return stdout.slice(at).replace(/\\\r?\n/g,"").replace(/\r?\n[ \t]*/g,"").trim();
}
function fields(row){
  return Object.fromEntries(row.split("|").slice(1).map((entry)=>{
    const at=entry.indexOf("=");
    if(at<1)throw new Error(`malformed GAP field ${entry}`);
    return [entry.slice(0,at),entry.slice(at+1)];
  }));
}
function ints(value){return value.split(",").filter(Boolean).map(Number);}
function numericHistogram(value){
  return Object.fromEntries(value.split(",").filter(Boolean).map((entry)=>{
    const [key,count]=entry.split(":");return [key,Number(count)];
  }));
}
function profileHistogram(value){
  return Object.fromEntries(value.split(";").filter(Boolean).map((entry)=>{
    const at=entry.lastIndexOf(":");return [entry.slice(0,at),Number(entry.slice(at+1))];
  }));
}
function histogramOfInts(values){
  return Object.fromEntries(Object.entries(values.reduce((out,value)=>{
    out[value]=(out[value]||0)+1;return out;
  },{})).sort((a,b)=>Number(a[0])-Number(b[0])));
}
function zeroBased(value){return ints(value).map((x)=>x-1);}
function bool(value){return value==="true"||value==="1";}
function assertPermutation(values,n,label){
  if(values.length!==n||new Set(values).size!==n||Math.min(...values)!==0||Math.max(...values)!==n-1){
    throw new Error(`${label} is not a degree-${n} permutation`);
  }
}

function build({writeInput=false}={}){
  const rom=JSON.parse(fs.readFileSync(path.join(ROOT,ROM_PATH),"utf8"));
  const payne=JSON.parse(fs.readFileSync(path.join(ROOT,PAYNE_PATH),"utf8"));
  const f20=JSON.parse(fs.readFileSync(path.join(ROOT,F20_PATH),"utf8"));
  if(rom.schema!=="holotrade.45-slot-rom-bijection.v1"||rom.valid!==true||
     payne.schema!=="holotrade.slow-path-is-payne-derivative.v1"||payne.status!=="PASS"||
     f20.schema!=="holotrade.w33-f20-qutrit-block-bridge.v1"||f20.status!=="PASS"){
    throw new Error("upstream ROM, Payne, or F20 certificate is not valid");
  }
  const input=renderInput(rom,payne,f20);
  if(writeInput)fs.writeFileSync(GAP_INPUT,input);
  else if(input!==fs.readFileSync(GAP_INPUT,"utf8"))throw new Error("GAP input adapter drifted");

  const run=runGap(GAP_FILE,{cwd:ROOT,quiet:true});
  if(!run.ok||/Error,|Syntax error|Syntax warning/.test(run.stdout+run.stderr)){
    throw new Error(`F20 Payne GAP atlas failed\n${run.stdout}\n${run.stderr}`);
  }
  const g=fields(markerRow(run.stdout,"F20_PAYNE_ATLAS"));
  const addressAxis=zeroBased(g.canonicalAddressAxis);
  const siteCircuit=zeroBased(g.siteCircuitMap);
  const outerSiteLine=zeroBased(g.outerSiteLineMap);
  assertPermutation(addressAxis,40,"address-axis map");
  if(siteCircuit.length!==5||new Set(siteCircuit).size!==5)throw new Error("site-circuit map is not bijective");
  if(outerSiteLine.length!==5||new Set(outerSiteLine).size!==5)throw new Error("site-line map is not bijective");
  const covers=Array.from({length:40},(_,axis)=>payne.equivariant40.covers[String(axis)]);
  const compiler=addressAxis.map((axis,address)=>({
    address,
    site:Math.floor(address/8),
    localPauliLabel:address%8,
    w33Axis:axis,
    payneSlowCover:covers[axis],
    matchedCircuitTarget:siteCircuit[Math.floor(address/8)],
    coverContainsMatchedTarget:covers[axis].includes(siteCircuit[Math.floor(address/8)]),
  }));
  const checks={
    gapStatus:g.status==="PASS",
    fullAndInnerOrders:Number(g.autOrder)===51840&&Number(g.innerOrder)===25920,
    lineStabilizerImages:g.innerLineImage==="A5"&&g.fullLineImage==="S5"&&Number(g.lineKernelOrder)===16,
    outerF20MeetsInnerInD10:g.outerF20Structure==="C5 : C4"&&g.outerInnerIntersectionStructure==="D10"&&Number(g.outerInnerIntersectionOrder)===10,
    addressAndAxisActionsAreTwoRegularOrbits:ints(g.addressOrbits).join(",")==="20,20"&&ints(g.w33Orbits).join(",")==="20,20",
    eightHundredAddressAxisBijections:Number(g.addressAxisBijections)===800,
    fibreF20ActsInsidePSp:bool(g.payneEquivariance)&&ints(g.slowOrbits).join(",")==="5,10,10,20",
    fiveTargetOrbitIsCircuit:Number(g.slowFiveEdges)===0&&Number(g.slowFiveStabOrder)===120&&g.slowFiveStabImage==="S5"&&Number(g.slowFiveCarrierOrbit)===216,
    uniqueSiteCircuitMap:Number(g.siteCircuitMaps)===1,
    exhaustiveIncidenceNoGo:Number(g.presentationIsomorphisms)===20&&Number(g.incidenceCandidates)===16000&&Number(g.coherentIncidenceMaps)===0,
  };
  if(!Object.values(checks).every(Boolean))throw new Error(`atlas check failed: ${JSON.stringify(checks)}`);

  const body={
    schema:"holotrade.w33-f20-payne-five-state-atlas.v1",
    status:"PASS",
    evidenceClass:"EXACT_GAP_GROUP_ACTION_ATLAS",
    corpusPriorArt:{
      fullGroupNoGo:"W33-Theory Passes 7017-7024 prove Hom_PSp(C^27,C^40) is only the constant channel; this packet uses the permitted proper-subgroup escape route F20.",
      payneBridge:"HoloTrade commits a493651 through f944915 own the explicit Payne-derived 40x45 cover, its rank-25 spectral intertwiner, production catalogue, and 45 minimum-word dictionary.",
      protectedBlock:"HoloTrade ea0ce53 and 7acbb22 own the fibre-product F20 and its local-Clifford action on the cyclic [[5,1,3]]_3 block.",
      addedHere:"Places that same F20 on the Payne fast and slow carriers, builds the site-to-circuit and address-to-axis maps, identifies the inner/outer ROM-line chain, and exhausts the stronger incidence-compatible map that does not exist.",
    },
    fiveStateAtlas:{
      circuit:{
        geometry:"five pairwise noncollinear GQ(4,2) slow targets",
        slowTargets:zeroBased(g.slowFiveOrbit),
        inducedEdges:Number(g.slowFiveEdges),
        setStabilizerOrder:Number(g.slowFiveStabOrder),
        setStabilizerImage:g.slowFiveStabImage,
        carrierOrbit:Number(g.slowFiveCarrierOrbit),
        fibreF20SlowOrbits:ints(g.slowOrbits),
        fibreF20LineOrbits:ints(g.slowLineOrbits),
        qutritSiteToSlowTarget:siteCircuit,
        mapCount:Number(g.siteCircuitMaps),
        interpretation:"For the fixed F20 generator identification, the five protected-qutrit sites map uniquely and equivariantly to the unique five-target F20 orbit. Its S5 stabilizer and 216-set orbit identify it as the existing circuit carrier, not a ROM bank.",
      },
      romLine:{
        geometry:"five pairwise collinear GQ(4,2) slow targets",
        innerGroupOrder:Number(g.innerOrder),
        fullGroupOrder:Number(g.autOrder),
        innerLineStabilizer:{order:Number(g.innerLineStabOrder),kernelOrder:Number(g.lineKernelOrder),image:g.innerLineImage},
        fullLineStabilizer:{order:Number(g.fullLineStabOrder),kernelOrder:Number(g.lineKernelOrder),image:g.fullLineImage},
        outerF20:{order:Number(g.outerF20Order),structure:g.outerF20Structure,complementClasses:Number(g.outerF20ComplementClasses),vertexOrbits:ints(g.outerVertexOrbits),lineOrbits:ints(g.outerLineOrbits)},
        innerIntersection:{order:Number(g.outerInnerIntersectionOrder),structure:g.outerInnerIntersectionStructure},
        qutritSiteToRomLinePoint:outerSiteLine,
        interpretation:"The same generator-level D10<F20 chain appears as line-preserving inner versus outer symmetry: the F20 complement acts faithfully on one ROM bank, but its intersection with the inner PSp(4,3) is exactly D10. The order-four completion occupies the outer W(E6) coset in this five-state realization.",
      },
    },
    addressToPayne:{
      addressActionOrbits:ints(g.addressOrbits),
      w33AxisActionOrbits:ints(g.w33Orbits),
      basisCrosswalkOrder:Number(g.basisCrosswalkOrder),
      equivariantBijections:Number(g.addressAxisBijections),
      selectedMap:"lexicographically first under the committed address, axis, and generator orderings; reproducible but not geometrically canonical",
      addressToW33Axis:addressAxis,
      compiler,
      interpretation:"Both forty-state actions are two disjoint regular F20 torsors. Any selected equivariant bijection sends each addressed nonidentity one-qutrit Pauli to a cheap W33 axis, hence to its exact nine-target Payne slow-path cover.",
    },
    incidenceCompatibilityNoGo:{
      presentationCompatibleF20Isomorphisms:Number(g.presentationIsomorphisms),
      equivariantMapCandidates:Number(g.incidenceCandidates),
      coherentMaps:Number(g.coherentIncidenceMaps),
      overlapCensus:{
        selectedGaugePerSite:ints(g.selectedOverlapProfile),
        selectedGaugeMatchedAddresses:ints(g.selectedOverlapProfile).reduce((a,b)=>a+b,0),
        maximumMatchedAddresses:Number(g.maximumMatchedAddresses),
        bestSortedPerSiteProfiles:g.bestOverlapProfiles.split(";").filter(Boolean).map(ints),
        matchedAddressHistogram:numericHistogram(g.overlapTotalHistogram),
        sortedPerSiteProfileHistogram:profileHistogram(g.overlapProfileHistogram),
      },
      conditionTested:"For every site, the eight W33 axes assigned to its eight nonidentity local Paulis equal the eight Payne covers containing that site's matched slow target.",
      theorem:"No presentation-compatible F20 identification satisfies the site-fibre/Payne-incidence equality. The site-to-circuit and address-to-axis bridges exist separately, but F20 symmetry alone cannot weld them into that stronger incidence codec.",
    },
    oneHopRepair:{
      selectedGaugeDistanceHistogram:histogramOfInts(ints(g.selectedStageDistances)),
      selectedGaugeAllExactlyOneHop:new Set(ints(g.selectedStageDistances)).size===1&&ints(g.selectedStageDistances)[0]===1,
      interpretation:"The frozen address gauge misses the matched circuit target at all 40 addresses, but the committed Payne staging rule repairs every miss by one W33-axis hop to a cover containing that target.",
      provenance:"This composes the new F20 atlas with HoloTrade's already-owned all-1800-pair radius-one Payne staging theorem; it is not a direct F20-equivariant incidence weld.",
    },
    checks,
    sourceHashes:{
      rom:`sha256:${shaFile(path.join(ROOT,ROM_PATH))}`,
      payne:`sha256:${shaFile(path.join(ROOT,PAYNE_PATH))}`,
      f20Qutrit:`sha256:${shaFile(path.join(ROOT,F20_PATH))}`,
      gap:`sha256:${shaFile(GAP_FILE)}`,
      gapInput:`sha256:${shaFile(GAP_INPUT)}`,
    },
    boundary:"Exact finite group actions at q=3. The selected 40-address map is one of 800 equivariant choices, not canonical. The D10<F20 line chain is an explicit group-pair isomorphism, not an identification of local Clifford hardware with W(E6). The no-go excludes only the stated F20-equivariant site-fibre incidence condition; larger symmetry, nonlinear, modular, or ancilla-mediated codecs remain open. No fault-tolerant recode, calibration, timing, or physical-performance claim is made.",
  };
  return {...body,sha256:crypto.createHash("sha256").update(canonical(body)).digest("hex")};
}

function main(){
  const write=process.argv.includes("--write");
  const packet=build({writeInput:write});
  if(write)fs.writeFileSync(OUT,JSON.stringify(packet,null,2)+"\n");
  else if(canonical(packet)!==canonical(JSON.parse(fs.readFileSync(OUT,"utf8"))))throw new Error("F20 Payne atlas certificate drifted");
  process.stdout.write(JSON.stringify({status:packet.status,siteCircuit:packet.fiveStateAtlas.circuit.qutritSiteToSlowTarget,addressMaps:packet.addressToPayne.equivariantBijections,incidenceCandidates:packet.incidenceCompatibilityNoGo.equivariantMapCandidates,coherent:packet.incidenceCompatibilityNoGo.coherentMaps,sha256:packet.sha256})+"\n");
}

if(require.main===module){try{main();}catch(error){console.error(error.stack||error.message);process.exitCode=1;}}
module.exports={build,renderInput};
