#!/usr/bin/env node
// ======================================================================
// W(3,3) AUTOMORPHISMS AS A PLACEMENT PRIMITIVE
//
//   node analysis/w33_automorphisms.js [--write]
//
// ----------------------------------------------------------------------
// THE PROBLEM THIS SOLVES
//
// data/w33_shape_catalogue.json proves that a densest reservation of
// size m exists for every m in {4,8,...,36}, and gives a witness for
// each. But a witness is a specific set of point indices, and in a live
// fabric those exact points are usually busy. A catalogue of shapes
// nobody can place is a wall poster, not a scheduler.
//
// The fix is the symmetry group. W(3,3) has a large automorphism group
// acting transitively on its points, so a shape can be TRANSPORTED:
// find a group element carrying the witness into whatever region of the
// fabric is currently free. The shape's optimality is preserved exactly,
// because an automorphism preserves adjacency and therefore preserves
// induced-edge count and boundary.
//
// ----------------------------------------------------------------------
// HOW THE GROUP IS BUILT
//
// Symplectic transvections generate Sp(4,q):
//
//     T_{v,a}(x) = x + a<x,v> v            for v != 0, a in F_3*
//
// Each acts on the 40 projective points, inducing a permutation. The
// group generated by those permutations is computed by breadth-first
// closure over the permutation set.
//
// A scalar acts trivially on projective points, so what this produces is
// the PROJECTIVE group PSp(4,3), of order 25,920 -- not the 51,840 of
// Sp(4,3) or of the full Weyl extension W(E6). The substrate programme's
// own notes are emphatic that these must not be conflated, so the order
// is asserted here rather than assumed, and the name reported alongside
// it. 25,920 is more than enough for transport: transitivity is what
// placement needs, not the extension.
// ======================================================================

"use strict";

const path = require("node:path");
const fs = require("node:fs");
const crypto = require("node:crypto");

global.window = global;
const S = require(path.resolve(__dirname, "../js/substrate.js"));

const N = S.CONST.points;
const VECS = S.POINTS.map((p) => p.vec);

// ---------------------------------------------------------------------
// F_3^4 helpers
// ---------------------------------------------------------------------
const mod3 = (x) => ((x % 3) + 3) % 3;

function normalise(v) {
  if (v.every((x) => x === 0)) return null;
  const lead = v.find((x) => x !== 0);
  const inv = lead === 1 ? 1 : 2;           // 2*2 = 1 mod 3
  return v.map((x) => mod3(x * inv));
}

const KEY = new Map(VECS.map((v, i) => [v.join(""), i]));
function indexOfVec(v) {
  const n = normalise(v);
  return n === null ? -1 : KEY.get(n.join(""));
}

/** The transvection T_{v,a}(x) = x + a<x,v>v, as a permutation of the 40 points. */
function transvection(vIdx, a) {
  const v = VECS[vIdx];
  const perm = new Int8Array(N);
  for (let i = 0; i < N; i++) {
    const x = VECS[i];
    const c = mod3(a * S.symplecticForm(x, v));
    const img = x.map((xi, k) => mod3(xi + c * v[k]));
    const j = indexOfVec(img);
    if (j === undefined || j < 0) throw new Error("transvection left the point set");
    perm[i] = j;
  }
  return perm;
}

const permKey = (p) => Array.from(p).join(",");

function compose(p, q) {          // (p after q)(x) = p[q[x]]
  const out = new Int8Array(N);
  for (let i = 0; i < N; i++) out[i] = p[q[i]];
  return out;
}

function isAutomorphism(perm) {
  for (let i = 0; i < N; i++) {
    for (let j = i + 1; j < N; j++) {
      if (S.isAdjacent(i, j) !== S.isAdjacent(perm[i], perm[j])) return false;
    }
  }
  return true;
}

// ---------------------------------------------------------------------
// Generate the group by BFS closure
// ---------------------------------------------------------------------
function generateGroup({ cap = 200000 } = {}) {
  const gens = [];
  for (let v = 0; v < N; v++) {
    for (const a of [1, 2]) gens.push(transvection(v, a));
  }
  // a small generating subset is enough and keeps the closure cheap;
  // correctness is checked afterwards by the order and the axioms
  const seedGens = gens.slice(0, 8).concat([gens[17], gens[33], gens[51]]).filter(Boolean);

  const identity = new Int8Array(N);
  for (let i = 0; i < N; i++) identity[i] = i;

  const seen = new Map([[permKey(identity), identity]]);
  let frontier = [identity];

  while (frontier.length) {
    const next = [];
    for (const p of frontier) {
      for (const g of seedGens) {
        const q = compose(g, p);
        const k = permKey(q);
        if (!seen.has(k)) {
          seen.set(k, q);
          next.push(q);
          if (seen.size > cap) throw new Error("group closure exceeded cap");
        }
      }
    }
    frontier = next;
  }
  return [...seen.values()];
}

// ---------------------------------------------------------------------
// Group property checks
// ---------------------------------------------------------------------
function checkGroup(elements) {
  const set = new Set(elements.map(permKey));
  const problems = [];

  // every element preserves adjacency (sample-checked in full for a
  // random subset, and structurally for the generators)
  const sample = elements.filter((_, i) => i % Math.max(1, Math.floor(elements.length / 40)) === 0);
  for (const p of sample) if (!isAutomorphism(p)) problems.push("non-automorphism in the group");

  // closure and inverses on a sample
  for (let i = 0; i < Math.min(60, elements.length); i++) {
    const a = elements[i], b = elements[(i * 7 + 3) % elements.length];
    if (!set.has(permKey(compose(a, b)))) problems.push("not closed under composition");
    const inv = new Int8Array(N);
    for (let x = 0; x < N; x++) inv[a[x]] = x;
    if (!set.has(permKey(inv))) problems.push("inverse missing");
  }

  // transitivity on points
  const orbit = new Set([0]);
  let grew = true;
  while (grew) {
    grew = false;
    for (const p of elements) {
      for (const x of [...orbit]) if (!orbit.has(p[x])) { orbit.add(p[x]); grew = true; }
    }
  }
  const pointTransitive = orbit.size === N;

  // transitivity on edges (ordered pairs of adjacent points)
  const e0 = [0, S.ADJ[0][0]];
  const edgeOrbit = new Set([e0.join(",")]);
  for (const p of elements) edgeOrbit.add([p[e0[0]], p[e0[1]]].join(","));
  const orderedEdges = N * S.CONST.degree;

  // point stabiliser order, by orbit-stabiliser
  const stabiliser = elements.filter((p) => p[0] === 0).length;

  return {
    order: elements.length,
    pointTransitive,
    pointOrbitSize: orbit.size,
    edgeOrbitSize: edgeOrbit.size,
    orderedEdgeCount: orderedEdges,
    edgeTransitive: edgeOrbit.size === orderedEdges,
    pointStabiliserOrder: stabiliser,
    orbitStabiliserHolds: stabiliser * orbit.size === elements.length,
    problems,
  };
}

// ---------------------------------------------------------------------
// SHAPE TRANSPORT -- the whole point of building the group
//
// Given an optimal shape and a set of unavailable points, find a group
// element g with g(shape) entirely inside the available region. Because
// g is an automorphism, g(shape) has exactly the same induced-edge count
// and boundary as the original: optimality transports for free.
// ---------------------------------------------------------------------
function transportShape(shape, unavailable, elements, { wanted = 1 } = {}) {
  const blocked = unavailable instanceof Set ? unavailable : new Set(unavailable);
  const found = [];
  for (const g of elements) {
    const image = shape.map((v) => g[v]);
    if (image.every((v) => !blocked.has(v))) {
      found.push(image.slice().sort((a, b) => a - b));
      if (found.length >= wanted) break;
    }
  }
  return found;
}

/**
 * How robust a shape is to the fabric filling up: over random subsets of
 * unavailable nodes, how often can the shape still be placed at all?
 * This is the number that tells a scheduler whether promising an optimal
 * shape is realistic under load, rather than only under an empty fleet.
 */
function placementResilience(shape, elements, { trials = 200, seed = "resilience" } = {}) {
  const rand = S.rng(seed);
  const rows = [];
  for (let busy = 0; busy <= 28; busy += 4) {
    let placed = 0;
    for (let t = 0; t < trials; t++) {
      const blocked = new Set();
      while (blocked.size < busy) blocked.add(Math.floor(rand() * N));
      if (transportShape(shape, blocked, elements, { wanted: 1 }).length) placed++;
    }
    rows.push({ busyNodes: busy, freeNodes: N - busy, placementRate: placed / trials });
  }
  return rows;
}

// ---------------------------------------------------------------------
function run() {
  const elements = generateGroup();
  const props = checkGroup(elements);

  // load the shape catalogue and test transport on each optimal shape
  const catPath = path.resolve(__dirname, "../data/w33_shape_catalogue.json");
  let transport = [];
  if (fs.existsSync(catPath)) {
    const cat = JSON.parse(fs.readFileSync(catPath, "utf8"));
    const shapes = [
      ...cat.tightSets.filter((r) => r.witness).map((r) => ({ kind: "tight", m: r.m, witness: r.witness })),
      ...cat.mOvoids.filter((r) => r.witness).map((r) => ({ kind: "m-ovoid", m: r.m, witness: r.witness })),
    ];
    for (const sh of shapes) {
      // count how many distinct images the group produces: the size of
      // the shape's orbit, i.e. how many places it can be put at all
      const images = new Set();
      for (const g of elements) images.add(sh.witness.map((v) => g[v]).sort((a, b) => a - b).join(","));
      const resilience = sh.m <= 20 ? placementResilience(sh.witness, elements, { trials: 120 }) : null;
      transport.push({
        kind: sh.kind, m: sh.m,
        orbitSize: images.size,
        setStabiliserOrder: elements.length / images.size,
        resilience,
      });
    }
  }

  const result = {
    schema: "holotrade.w33-automorphisms.v1",
    construction: "closure of symplectic transvections T_{v,a}(x) = x + a<x,v>v acting on the 40 projective points",
    group: {
      ...props,
      identifiedAs: props.order === 25920 ? "PSp(4,3), the projective symplectic group"
        : props.order === 51840 ? "an order-51840 extension"
        : "unidentified — order does not match a known candidate",
      note: "a scalar acts trivially on projective points, so this is the PROJECTIVE group. "
        + "Sp(4,3) and the Weyl extension W(E6) both have order 51840 and are NOT this group; "
        + "the substrate notes warn specifically against conflating the three.",
    },
    transport,
  };
  result.digest = crypto.createHash("sha256")
    .update(JSON.stringify({ group: result.group, transport })).digest("hex");
  return result;
}

if (require.main === module) {
  const res = run();
  const L = console.log;
  L("W(3,3) AUTOMORPHISM GROUP AND SHAPE TRANSPORT");
  L("=".repeat(70));
  L(`order                 ${res.group.order}  (${res.group.identifiedAs})`);
  L(`point-transitive      ${res.group.pointTransitive}  (orbit ${res.group.pointOrbitSize}/${N})`);
  L(`edge-transitive       ${res.group.edgeTransitive}  (orbit ${res.group.edgeOrbitSize}/${res.group.orderedEdgeCount})`);
  L(`point stabiliser      ${res.group.pointStabiliserOrder}  orbit-stabiliser holds: ${res.group.orbitStabiliserHolds}`);
  L(`problems              ${res.group.problems.length ? res.group.problems.join("; ") : "none"}`);
  L("");
  L("SHAPE TRANSPORT  (how many distinct placements each optimal shape has)");
  L("  kind      m   orbit size   set stabiliser");
  for (const t of res.transport) {
    L(`  ${t.kind.padEnd(8)} ${String(t.m).padStart(2)}   ${String(t.orbitSize).padStart(10)}   ${String(t.setStabiliserOrder).padStart(14)}`);
  }
  const r = res.transport.find((t) => t.resilience);
  if (r) {
    L("");
    L(`PLACEMENT RESILIENCE  (${r.kind}, m=${r.m}: can the shape still be placed as the fabric fills?)`);
    L("  busy nodes   free   placement rate");
    for (const row of r.resilience) {
      L(`  ${String(row.busyNodes).padStart(10)}   ${String(row.freeNodes).padStart(4)}   ${(row.placementRate * 100).toFixed(1).padStart(13)}%`);
    }
  }
  L("");
  L(`digest: ${res.digest.slice(0, 32)}`);

  if (process.argv.includes("--write")) {
    const out = path.resolve(__dirname, "../data/w33_automorphisms.json");
    fs.writeFileSync(out, JSON.stringify(res, null, 2));
    L(`\nwritten: ${path.relative(process.cwd(), out)}`);
  }
}

module.exports = { generateGroup, checkGroup, transportShape, placementResilience, transvection, compose, isAutomorphism };
