#!/usr/bin/env python3
"""A5 organizer of the flagship U(1)^5 and canonical hypercharge.

Starting from the exact global SM-side algebra A2+A1+u(1)^5, let
L=(A2+A1)^perp intersect E8.  This file proves L is exactly the A5 root lattice.

An explicit simple-root basis alpha_1,...,alpha_5 has A5 Cartan Gram matrix.
The flagship hypercharge obeys
    <Y,alpha_1>=-1, <Y,alpha_i>=0 (i=2..5),
hence Y=-omega_1(A5).  Therefore
    L*/L ~= Z6,
    ord([Y])=6,
    Y^2=5/6,
and the six discriminant classes have shortest norms
    0,5/6,4/3,3/2,4/3,5/6.

Crucially, for x=sum n_i alpha_i in L,
    <Y,x>=-n_1,
so
    L intersect Y^perp = Z alpha_2+...+Z alpha_5 ~= A4.
Thus the four hypercharge-orthogonal global U(1) directions are organized by an
integral A4 root lattice, with Weyl stabilizer W(A4)=S5.  This is a structural
organizer, not yet a statement that the physical singlet vacuum Higgses all A4
directions.
"""
from __future__ import annotations
import itertools,json
from fractions import Fraction as F
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/w33_flagship_a5_hypercharge_organizer.json'

SIMPLE_E8=[
 [F(1,2),-F(1,2),-F(1,2),-F(1,2),-F(1,2),-F(1,2),-F(1,2),F(1,2)],
 [1,1,0,0,0,0,0,0],[-1,1,0,0,0,0,0,0],[0,-1,1,0,0,0,0,0],
 [0,0,-1,1,0,0,0,0],[0,0,0,-1,1,0,0,0],[0,0,0,0,-1,1,0,0],[0,0,0,0,0,-1,1,0]]
SIMPLE_E8=[[F(x) for x in r] for r in SIMPLE_E8]

# Basis of L in E8-simple-root coordinates from the previous Z6 gluing pass.
LZ=[
 [1,0,0,0,0,0,0,0],
 [0,1,0,2,3,0,0,0],
 [0,0,1,0,-1,0,0,0],
 [0,0,0,0,0,1,1,0],
 [0,0,0,0,0,1,0,1]]
# Unimodular change from LZ to an A5 simple-root basis.
A5_IN_L=[
 [-2,-3,-4,-3,-1],
 [0,0,0,1,0],
 [1,1,2,0,0],
 [0,1,1,1,1],
 [1,0,0,0,0]]
Y=(F(1,6),-F(1,6),-F(1,6),F(1,2),0,F(1,2),0,F(1,2))

def dot(a,b): return sum(x*y for x,y in zip(a,b))
def e8vec(z): return tuple(sum(F(z[i])*SIMPLE_E8[i][j] for i in range(8)) for j in range(8))
LB=[e8vec(z) for z in LZ]
def lin(vs,c): return tuple(sum(F(c[i])*vs[i][j] for i in range(len(vs))) for j in range(len(vs[0])))
A=[lin(LB,z) for z in A5_IN_L]

def det(M):
    A=[list(map(F,r)) for r in M];n=len(A);o=F(1)
    for c in range(n):
        p=next(i for i in range(c,n) if A[i][c])
        if p!=c:A[c],A[p]=A[p],A[c];o=-o
        q=A[c][c];o*=q
        for j in range(c,n):A[c][j]/=q
        for i in range(c+1,n):
            q=A[i][c]
            for j in range(c,n):A[i][j]-=q*A[c][j]
    return o

def omega(k):
    # standard A5 fundamental weight in the six-coordinate realization
    if k==0:return (F(0),)*6
    return tuple([F(6-k,6)]*k+[-F(k,6)]*(6-k))

def main(write=True):
    C=[[dot(a,b) for b in A] for a in A]
    target=[[F(2 if i==j else -1 if abs(i-j)==1 else 0) for j in range(5)] for i in range(5)]
    assert C==target and det(C)==6

    # The basis change is unimodular: determinant +1.
    assert det([[F(A5_IN_L[j][i]) for j in range(5)] for i in range(5)])==1

    # Count all norm-two vectors in L by A5 coordinates.
    roots=[]
    for z in itertools.product(range(-2,3),repeat=5):
        v=lin(A,z)
        if dot(v,v)==2: roots.append(z)
    assert len(roots)==30

    yp=[dot(Y,a) for a in A]
    assert yp==[F(-1),0,0,0,0]
    assert dot(Y,Y)==F(5,6)

    shortest=[dot(omega(k),omega(k)) for k in range(6)]
    assert shortest==[0,F(5,6),F(4,3),F(3,2),F(4,3),F(5,6)]
    primitive=[k for k in range(1,6) if __import__('math').gcd(k,6)==1]
    assert primitive==[1,5]
    assert all(shortest[k]==F(5,6) for k in primitive)

    # Integral orthogonal complement to Y is exactly alpha2..alpha5.
    # For integral A5 coordinates n_i, <Y,sum n_i alpha_i>=-n_1.
    A4=[row[1:] for row in [r[:] for r in C][1:]]
    assert det(A4)==5
    assert all(dot(Y,A[i])==0 for i in range(1,5))

    out={
      'schema':'holotrade.w33_flagship_a5_hypercharge_organizer.v1',
      'status':'PASS_A5_HYPERCHARGE_ORGANIZER',
      'headline':'The rank-five Abelian complement of the flagship global A2+A1 is exactly the A5 root lattice. Hypercharge is -omega1(A5), so it generates the Z6 discriminant with minimal norm 5/6. The integral hypercharge-orthogonal sublattice is exactly A4 generated by alpha2..alpha5; the four extra global U(1) directions are therefore one A4-organized sector rather than four unrelated axes.',
      'A5':{
        'rank':5,'root_count':30,'cartan':[[str(x) for x in r] for r in C],
        'determinant':6,'discriminant':'Z/6',
        'simple_roots_E8':[[str(x) for x in a] for a in A]},
      'hypercharge':{
        'Y':[str(x) for x in Y],'pairings_with_A5_simples':[str(x) for x in yp],
        'identification':'Y=-omega1(A5)','norm2':'5/6','kY':'5/3',
        'primitive_discriminant_classes':[1,5],
        'shortest_norms_by_class':[str(x) for x in shortest],
        'minimum_primitive_order6_norm':'5/6',
        'GUT_scale_sin2_thetaW':'3/8'},
      'extra_u1_organizer':{
        'integral_lattice':'L intersect Y^perp = A4',
        'generators':'alpha2,alpha3,alpha4,alpha5',
        'cartan_determinant':5,'root_rank':4,'weyl_stabilizer_of_Y':'W(A4)=S5',
        'continuous_split':'L tensor Q = Q*Y orthogonal_sum (A4 tensor Q)',
        'integral_warning':'Y is in L* rather than L, so this is not an integral direct-sum decomposition L=ZY+A4'},
      'physics_reading':'The five unbroken Abelian Cartan directions have a canonical A5 organization. Hypercharge is the minuscule discriminant direction; the remaining four directions form its A4 stabilizer sector. A physical vacuum still has to supply singlet charges/VEVs of rank four on that A4 sector.',
      'boundary':'Exact E8-lattice statement. It does not assert that the 132-singlet vacuum has rank four, D/F flatness, or that every A4 simple direction is Higgsed.',
      'parents':['data/w33_flagship_global_u1_closure.json','data/w33_flagship_hypercharge_z6_gluing.json'],
      'checks':{
        'A5_cartan_exact':True,'A5_roots30':True,'det6':True,'Y_minus_omega1':True,
        'primitive_Z6_min_norm_5_6':True,'kY_5_3':True,'sin2_3_8':True,
        'Y_orthogonal_integral_lattice_A4':True,'A4_det5':True}}
    if write:OUT.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps(out,indent=2))
    return out
if __name__=='__main__':main(True)
