#!/usr/bin/env python3
"""Flagship hypercharge is the generator of the E8 Z6 gluing discriminant.

For the globally unbroken Standard-Model-side root algebra A2+A1, let
  R = A2 + A1
inside the E8 root lattice, and L = R^perp intersect E8.

This file proves exactly:
* rank(L)=5 and det Gram(L)=6;
* the flagship hypercharge Y lies in L^* with Y^2=5/6;
* [Y] has exact order 6 in L^*/L, hence L^*/L ~= Z/6 and Y generates it;
* if omega2 is the A2 fundamental weight and omega is the A1 fundamental
  weight, then Y+omega2+omega is literally an E8 root of norm 2.

Thus the canonical k_Y=2Y^2=5/3 and the order-six center gluing are one E8
lattice statement.  In group language the discriminant class paired with Y is
the order-six product of the SU(3) and SU(2) center generators.  This is the
lattice mechanism underlying the familiar Z6 global quotient of the Standard
Model embedding.  It does not determine which extra U(1)s are Higgsed.
"""
from fractions import Fraction as F
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/w33_flagship_hypercharge_z6_gluing.json'

SIMPLE=[
 [F(1,2),F(-1,2),F(-1,2),F(-1,2),F(-1,2),F(-1,2),F(-1,2),F(1,2)],
 [F(1),F(1),0,0,0,0,0,0],[-1,1,0,0,0,0,0,0],[0,-1,1,0,0,0,0,0],
 [0,0,-1,1,0,0,0,0],[0,0,0,-1,1,0,0,0],[0,0,0,0,-1,1,0,0],[0,0,0,0,0,-1,1,0]]
SIMPLE=[[F(x) for x in r] for r in SIMPLE]
A2A1=[
 (F(1),F(1),0,0,0,0,0,0),
 (0,F(-1),F(1),0,0,0,0,0),
 (0,0,0,0,F(1),0,F(-1),0)]
Y=(F(1,6),F(-1,6),F(-1,6),F(1,2),0,F(1,2),0,F(1,2))

def dot(a,b): return sum(x*y for x,y in zip(a,b))
def lin(z): return tuple(sum(F(z[i])*SIMPLE[i][j] for i in range(8)) for j in range(8))
def det(A):
    A=[list(r) for r in A]; n=len(A); out=F(1)
    for c in range(n):
        p=next(i for i in range(c,n) if A[i][c])
        if p!=c:A[c],A[p]=A[p],A[c];out=-out
        q=A[c][c];out*=q
        for j in range(c,n):A[c][j]/=q
        for i in range(c+1,n):
            q=A[i][c]
            for j in range(c,n):A[i][j]-=q*A[c][j]
    return out
def e8(v):
    tw=[2*x for x in v]
    if all(x.denominator==1 and x%2==0 for x in tw):
        return sum(v).denominator==1 and int(sum(v))%2==0
    if all(x.denominator==1 and x%2!=0 for x in tw):
        return sum(v).denominator==1 and int(sum(v))%2==0
    return False

def main(write=True):
    # Integer kernel of the three orthogonality equations in the E8 simple-root basis:
    # z4=2z2, z5=3z2-z3, z6=z7+z8.
    Z=[
      [1,0,0,0,0,0,0,0],
      [0,1,0,2,3,0,0,0],
      [0,0,1,0,-1,0,0,0],
      [0,0,0,0,0,1,1,0],
      [0,0,0,0,0,1,0,1]]
    B=[lin(z) for z in Z]
    assert all(all(dot(b,r)==0 for r in A2A1) for b in B)
    G=[[dot(a,b) for b in B] for a in B]
    d=det(G); assert d==6

    pair=[dot(Y,b) for b in B]
    assert pair==[0,2,-1,0,-1]
    assert dot(Y,Y)==F(5,6)

    # Exact coordinates of Y in this L basis.
    coeff=[F(1),F(5,3),F(2),F(3,2),F(1,2)]
    rec=tuple(sum(coeff[i]*B[i][j] for i in range(5)) for j in range(8))
    assert rec==Y
    assert all((6*c).denominator==1 for c in coeff)
    assert all(any((n*c).denominator!=1 for c in coeff) for n in range(1,6))
    order=6
    # |disc L|=6 and [Y] has order6 -> cyclic discriminant generated by Y.
    assert d==order

    a1,a2,a3=A2A1
    omega2=tuple(F(1,3)*a1[i]+F(2,3)*a2[i] for i in range(8))
    omega=tuple(F(1,2)*a3[i] for i in range(8))
    glue=tuple(Y[i]+omega2[i]+omega[i] for i in range(8))
    assert e8(glue) and dot(glue,glue)==2

    out={
      'schema':'holotrade.w33_flagship_hypercharge_z6_gluing.v1',
      'status':'PASS_E8_Z6_HYPERCHARGE_GLUE',
      'headline':'For the flagship global A2+A1 gauge roots, the orthogonal complement L inside the E8 root lattice has rank5 and determinant6. Hypercharge Y is in L* with norm5/6 and exact order6 mod L, so L*/L is cyclic Z6 generated by Y. The matching A2+A1 discriminant class is omega2(A2)+omega(A1), and Y+omega2+omega is an actual E8 root of norm2.',
      'root_algebra':'A2+A1',
      'complement_lattice':{
        'rank':5,'gram':[[str(x) for x in r] for r in G],
        'determinant':6,'discriminant_group':'Z/6',
        'basis_E8_coordinates':[[str(x) for x in b] for b in B]},
      'hypercharge':{
        'Y':[str(x) for x in Y],'norm2':'5/6','kY':'5/3',
        'pairings_with_L_basis':[str(x) for x in pair],
        'coordinates_in_L_tensor_Q':[str(x) for x in coeff],
        'order_in_discriminant':6,'generates_discriminant':True},
      'glue':{
        'A2_fundamental_weight_class':'omega2=(alpha1+2 alpha2)/3',
        'A1_fundamental_weight_class':'omega=alpha/2',
        'glue_vector_Y_plus_omega2_plus_omega':[str(x) for x in glue],
        'glue_vector_is_E8_root':True,'glue_vector_norm2':'2',
        'group_reading':'the hypercharge discriminant generator is glued to the order-3 SU(3) center class and order-2 SU(2) center class, producing an order-6 center identification'},
      'physics_reading':'The canonical kY=5/3 normalization and the Z6 center gluing are not independent inputs in this embedding; they are two faces of the same unimodular E8 lattice gluing.',
      'boundary':'Exact E8 lattice theorem for the gauge embedding. It supports the familiar (SU3 x SU2 x U1)/Z6 global quotient structure, but does not by itself prove that all four additional U1 gauge bosons are removed in the final singlet-Higgsed vacuum.',
      'parents':['data/w33_flagship_global_u1_closure.json','data/w33_e8_a8_selector_holonomy_triple_intersection.json'],
      'checks':{'rank5':True,'det6':True,'Y_in_dual':True,'Y_norm_5_6':True,'Y_order6':True,'disc_is_Z6':True,'glue_is_E8_root':True}}
    if write:OUT.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps(out,indent=2))
    return out
if __name__=='__main__':main(True)
