q := 3;;
F := GF(q);; G := Sp(4, q);;
J := InvariantBilinearForm(G).matrix;;
v := [1,0,0,0] * One(F);;
pts := Orbit(G, v, OnLines);;
act := ActionHomomorphism(G, pts, OnLines);; P := Image(act);;
i0 := Position(pts, v);; S := Stabilizer(P, i0);;
N := PCore(S, q);;
cls := ComplementClassesRepresentatives(S, N);;
Print("q=", q, " |PSp|=", Size(P), " |Stab(p0)|=", Size(S), " |O_q|=", Size(N), " complement classes=", Length(cls), " |S/[S,S]|=", Index(S, DerivedSubgroup(S)), "\n");
q := 5;;
F := GF(q);; G := Sp(4, q);;
J := InvariantBilinearForm(G).matrix;;
v := [1,0,0,0] * One(F);;
pts := Orbit(G, v, OnLines);;
act := ActionHomomorphism(G, pts, OnLines);; P := Image(act);;
i0 := Position(pts, v);; S := Stabilizer(P, i0);;
N := PCore(S, q);;
cls := ComplementClassesRepresentatives(S, N);;
Print("q=", q, " |PSp|=", Size(P), " |Stab(p0)|=", Size(S), " |O_q|=", Size(N), " complement classes=", Length(cls), " |S/[S,S]|=", Index(S, DerivedSubgroup(S)), "\n");
q := 7;;
F := GF(q);; G := Sp(4, q);;
J := InvariantBilinearForm(G).matrix;;
v := [1,0,0,0] * One(F);;
pts := Orbit(G, v, OnLines);;
act := ActionHomomorphism(G, pts, OnLines);; P := Image(act);;
i0 := Position(pts, v);; S := Stabilizer(P, i0);;
N := PCore(S, q);;
cls := ComplementClassesRepresentatives(S, N);;
Print("q=", q, " |PSp|=", Size(P), " |Stab(p0)|=", Size(S), " |O_q|=", Size(N), " complement classes=", Length(cls), " |S/[S,S]|=", Index(S, DerivedSubgroup(S)), "\n");
QUIT;
