#!/usr/bin/env python3
"""
The 115-leaf measurement set is generated by 39 seeds and ONE Clifford gate.

WHY THIS IS MORE THAN A SYMMETRY REMARK.  For two qutrits the Clifford group
modulo Paulis and phases is Sp(4,3), so an element of Sp(4,3) is not an
abstract automorphism -- it is a physical gate, and the projective action on
the 40 Pauli classes is what that gate does to observables in the Heisenberg
picture.

tensor_115_resists_from_both_sides.py established that the 115-leaf depth-2
blocker -- the best known set of product observables covering every pair of
local contexts -- has stabiliser of order exactly 6 under the diagonal action,
and that a blind sweep over every cyclic class of PSp(4,3) recovers 115 from
that class and from no other. So the symmetry is not incidental to the
witness; it is the only cyclic symmetry that reaches the optimum.

Read as hardware, that says something concrete. Instead of storing 115 product
observables, store one gate and the orbit representatives, and generate the
rest by applying the gate. This file computes that compression exactly and
checks it by regeneration rather than by counting.

WHAT IS COMPUTED.

  * the order-6 generator g of the stabiliser, as an explicit 4x4 matrix over
    F_3 with g preserving the symplectic form -- so it names a Clifford coset,
    not merely a permutation;
  * its orbit decomposition on the 115 leaves;
  * the seed set, one representative per orbit;
  * a REGENERATION check: applying the diagonal action of <g> to the seeds
    must return exactly the 115 leaves, no more and no fewer, and the result
    must still block all 1,600 tiles.

The compression is the ratio 115 / (number of seeds).

HONEST FRAMING.  This compresses a specific known witness; it does not make
tau_2 smaller, and if a 114-leaf blocker exists it need not have any symmetry
at all. What it does establish is that the best schedule currently known is
not an unstructured list of 115 measurements but a single Clifford gate plus a
much shorter seed list -- which is the difference between a lookup table and a
generator on real hardware.
"""

import collections
import itertools
import json
import os
import random
import subprocess
import sys

ROOT = r"C:\Repos\Holotrade"
Q = 3
N = 40


def geometry():
    def nm(v):
        i = next(k for k, x in enumerate(v) if x % Q)
        z = pow(v[i] % Q, -1, Q)
        return tuple((z * x) % Q for x in v)

    def form(u, v):
        return (u[0] * v[1] - u[1] * v[0] + u[2] * v[3] - u[3] * v[2]) % Q

    pts = sorted({nm(v) for v in itertools.product(range(Q), repeat=4)
                  if any(v)})
    idx = {v: i for i, v in enumerate(pts)}
    lines = set()
    for a, b in itertools.combinations(range(N), 2):
        if form(pts[a], pts[b]):
            continue
        S = set()
        for x, y in itertools.product(range(Q), repeat=2):
            if x == y == 0:
                continue
            S.add(idx[nm(tuple((x * pts[a][k] + y * pts[b][k]) % Q
                               for k in range(4)))])
        if len(S) == 4:
            lines.add(tuple(sorted(S)))
    return pts, idx, sorted(lines), form, nm


def main():
    pts, idx, lines, form, nm = geometry()
    tiles = [frozenset(a * N + b for a in L for b in M)
             for L in lines for M in lines]

    W = set(json.loads(subprocess.run(
        ["node", "-e", "global.window=global;"
         "const T=require('./js/tensor-sharding.js');"
         "process.stdout.write(JSON.stringify(T.SYMMETRIC_WITNESS));"],
        cwd=ROOT, capture_output=True, text=True).stdout))

    e = [tuple(1 if k == i else 0 for k in range(4)) for i in range(4)]

    def is_sp(A):
        for i, j in itertools.combinations(range(4), 2):
            u = tuple(sum(A[r][k] * e[i][k] for k in range(4)) % Q
                      for r in range(4))
            v = tuple(sum(A[r][k] * e[j][k] for k in range(4)) % Q
                      for r in range(4))
            if form(u, v) != form(e[i], e[j]):
                return False
        return True

    def act(A, v):
        return nm(tuple(sum(A[i][k] * v[k] for k in range(4)) % Q
                        for i in range(4)))

    def perm(A):
        return tuple(idx[act(A, pts[p])] for p in range(N))

    def stabilises(p):
        return {p[v // N] * N + p[v % N] for v in W} == W

    def order_of(A):
        I = tuple(tuple(1 if i == j else 0 for j in range(4))
                  for i in range(4))
        C, o = A, 1
        while C != I:
            C = tuple(tuple(sum(C[i][k] * A[k][j] for k in range(4)) % Q
                            for j in range(4)) for i in range(4))
            o += 1
            if o > 60:
                return None
        return o

    print("ONE CLIFFORD GATE GENERATES THE 115-LEAF SCHEDULE")
    print("=" * 72)
    print("  Sp(4,3) is the two-qutrit Clifford group modulo Paulis and")
    print("  phases, so a stabilising element is a physical GATE acting on")
    print("  observables in the Heisenberg picture.")
    print()

    # search Sp(4,3) matrices for an order-6 one that stabilises the witness
    rng = random.Random(20260831)
    gate = None
    tried = 0
    while gate is None and tried < 4000000:
        tried += 1
        A = tuple(tuple(rng.randrange(Q) for _ in range(4)) for _ in range(4))
        if not is_sp(A):
            continue
        o = order_of(A)
        if o != 6:
            continue
        if stabilises(perm(A)):
            gate = A
    if gate is None:
        print("  no order-6 stabilising matrix found in the sampled budget")
        return 1

    g = perm(gate)
    print("  gate found (4x4 over F_3, symplectic, order 6):")
    for row in gate:
        print("     %s" % (list(row),))
    print("  it stabilises the witness: %s" % stabilises(g))
    print()

    # orbits of <g> on the 115 leaves, under the DIAGONAL action
    H = []
    cur = tuple(range(N))
    for _ in range(6):
        H.append(cur)
        cur = tuple(g[cur[i]] for i in range(N))
    seen, orbits = set(), []
    for v in sorted(W):
        if v in seen:
            continue
        ob = {h[v // N] * N + h[v % N] for h in H}
        seen |= ob
        orbits.append(sorted(ob))
    prof = collections.Counter(len(o) for o in orbits)
    seeds = sorted(o[0] for o in orbits)
    print("  orbit profile on the witness: %s" % dict(prof))
    print("  orbits (= seeds): %d, total leaves %d"
          % (len(orbits), sum(len(o) for o in orbits)))
    print()

    # REGENERATION: seeds + gate must rebuild exactly the witness
    rebuilt = set()
    for v in seeds:
        for h in H:
            rebuilt.add(h[v // N] * N + h[v % N])
    exact = rebuilt == W
    blocks = all(any(v in rebuilt for v in T) for T in tiles)
    print("  regenerating from %d seeds by applying the gate:" % len(seeds))
    print("     rebuilt %d leaves; equals the witness exactly: %s"
          % (len(rebuilt), exact))
    print("     and still blocks all %d tiles: %s" % (len(tiles), blocks))
    print("     compression 115 / %d = %.2fx" % (len(seeds), 115 / len(seeds)))
    print()
    print("  So the best known two-carrier measurement schedule is not a list")
    print("  of 115 observables. It is one Clifford gate and %d seeds."
          % len(seeds))
    print()
    print("  It does not make tau_2 smaller, and a 114-leaf blocker, if one")
    print("  exists, need not have any symmetry at all.")

    ok = exact and blocks and len(seeds) < 115
    if "--write" in sys.argv:
        p = os.path.join(ROOT, "data",
                         "witness_compresses_under_one_clifford.json")
        with open(p, "w") as fh:
            json.dump({
                "schema": "holotrade.witness-clifford-compression.v1",
                "valid": bool(ok),
                "why": ("Sp(4,3) is the two-qutrit Clifford group modulo "
                        "Paulis and phases, so a stabilising element is a "
                        "physical gate acting on observables"),
                "gate": [list(r) for r in gate],
                "gateOrder": 6,
                "gateIsSymplectic": True,
                "stabilisesWitness": True,
                "orbitProfile": {str(k): v for k, v in prof.items()},
                "seeds": len(seeds),
                "witnessSize": 115,
                "compression": round(115 / len(seeds), 3),
                "regeneratesExactly": exact,
                "regeneratedStillBlocks": blocks,
                "tiles": len(tiles),
                "canonicality": ("the blind cyclic-class sweep in "
                                 "tensor_115_resists_from_both_sides.py "
                                 "reaches 115 from this order-6 class and from "
                                 "no other, so the symmetry is not incidental"),
                "boundary": ("this compresses a known witness; it does not "
                             "lower tau_2, which stays open in [111, 115], and "
                             "a 114-leaf blocker need not be symmetric at all"),
            }, fh, indent=2)
        print("\n  written: %s" % os.path.relpath(p, ROOT))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
